### ISSUE TITLE
新版1.14自动开启加速启动程序本地令牌无法使用

### ISSUE THREAD

**Issue by EasyRain** [SteamTools-Team/SteamTools#101]
![image](https://user-images.githubusercontent.com/46843500/108990904-67b42100-76d2-11eb-9ba9-6d368efe5555.png)
![image](https://user-images.githubusercontent.com/46843500/108990934-6f73c580-76d2-11eb-857f-a7e0422d2c93.png)
当关闭加速与自动启动代理服务时启动程序本地令牌能够加载，但是只要是自动开启代理服务时就会报错，多次重启也无效

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
