### ISSUE TITLE
讨论区在您的地区不可用

### ISSUE THREAD

**Issue by lianghaotianabc** [SteamTools-Team/SteamTools#102]
不知道是不是我不会用……不能在个人资料留言……

**Comment by rmbadmin** [comment]
关于这一点，目前确实不能，因为这是Steam服务端的限制

**Comment by lianghaotianabc** [comment]
草光速回复，那那个不可描述……为什么也用不了呢

**Comment by lianghaotianabc** [comment]
> 关于这一点，目前确实不能，因为这是Steam服务端的限制
草光速回复，那那个不可描述……为什么也用不了呢

**Comment by lianghaotianabc** [comment]
> 关于这一点，目前确实不能，因为这是Steam服务端的限制

呃

**Comment by lianghaotianabc** [comment]
> 关于这一点，目前确实不能，因为这是Steam服务端的限制

草光速回复，那那个不可描述……为什么也用不了呢

**Comment by rmbadmin** [comment]
这个脚本也在之前已经失效了😂

**Comment by lianghaotianabc** [comment]
> 这个脚本也在之前已经失效了😂

太可惜了，要是有这个功能的话这个工具箱直接封神了呀

**Comment by lianghaotianabc** [comment]
对了，启用日志记录似乎没有默认开启，是为了保护隐私么

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
