### ISSUE TITLE
导入脚本之后必定卡死程序

### ISSUE THREAD

**Issue by lianghaotianabc** [SteamTools-Team/SteamTools#104]
如题，log无记录，不会发图片……
而且后来导入的脚本不能自启动，需要再次勾选……
再者脚本列表似乎只能识别// @name而不能识别// @name:zh-CN，油猴那边倒是可以显示出中文？

**Comment by lianghaotianabc** [comment]
如题，log无记录，不会发图片……
而且后来导入的脚本不能自启动，需要再次勾选……

**Comment by rmbadmin** [comment]
可否提供一下脚本

**Comment by lianghaotianabc** [comment]
> 可否提供一下脚本

似乎哪个脚本都会那样……不知道是不是我电脑的问题……

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。

**Comment by lianghaotianabc** [comment]
居然回访了

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月3日(星期一) 晚上8:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SteamTools-Team/SteamTools] 导入脚本之后必定卡死程序 (#104)





 
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
