### ISSUE TITLE
An error occurred during the addition of a certificate to the Trusted Root Certification Authorities store.

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#106]
反馈群用户 lincorn
环境 Windows 英文版
点击安装证书按钮
弹出错误弹窗
An error occurred during the addition of a certificate to the Trusted Root Certification Authorities store.

**Comment by rmbadmin** [comment]
此问题原因是因为在往用户电脑根证书区域添加信任证书时出现，具体原因是因为其自身系统环境，暂时没有好的解决方案。
