### ISSUE TITLE
Steam账号列表，点击昵称时异常

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#108]
反馈群用户 一只小羊886

Win32异常：拒绝访问
由 Process.Kill 引发
位于 
https://github.com/SteamTools-Team/SteamTools/blob/1.1.4/source/SteamTools/ViewModels/Page/SteamAccountPageViewModel.cs#L108

用户反馈开启 Steam 时，可以切换账号
关闭 Steam 时，出现异常

可能用户计算机上在关闭 Steam 的时候有其他的同名进程？且高于管理员权限。

修复方案，在V2项目中 更改业务逻辑
```System.Application.Services.ISteamService.Instance.KillSteamProcess()```
改为 ```bool TryKillSteamProcess()```
```false``` 弹窗提示用户手动关闭 Steam
```true``` 使用 IsRunningSteamProcess 再检测一遍，返回 ```int```(pid) 提示用户去任务管理器中结束进程，```null``` 再进行业务逻辑

**Comment by rmbadmin** [comment]
已修复
