### ISSUE TITLE
开启加速与Clash for windows 代理冲突

### ISSUE THREAD

**Issue by zeerdeer** [SteamTools-Team/SteamTools#109]
建议加速与脚本的开关单独触发，开启加速与Clash for windows 代理冲突，会自动关闭 Clash 代理。
不过还是建议这两功能分开会更好（如果可以）
如果我启动 Clash 脚本也就没效果了

**Comment by cyb233** [comment]
你是不是勾选了系统代理方式？

**Comment by zeerdeer** [comment]
> 你是不是勾选了系统代理方式？

没有的，这个问题我已经解决，直接买个软路由搞openwrt。
