### ISSUE TITLE
对于库存游戏的加载

### ISSUE THREAD

**Issue by lidawei97688** [SteamTools-Team/SteamTools#111]
在库存游戏那里，能不能添加个只显示已安装的开关？每次都加载好多自己确认没买过的游戏，一共就七八个游戏却要显示30多个，还都是没下载的，等待加载显示就要好久

**Comment by rmbadmin** [comment]
只要缓存数据存在的话，应该不会要许久，不过目前正在集中精力做2.0版，这里会改进的

**Comment by rmbadmin** [comment]
2.0版本已有已安装游戏的筛选开关
