### ISSUE TITLE
开机自启会出现“令牌同步服务器失败”的弹窗

### ISSUE THREAD

**Issue by Mr54233** [SteamTools-Team/SteamTools#112]
![image](https://user-images.githubusercontent.com/46802509/109580175-21791a80-7b35-11eb-8249-590b22a95e85.png)
如图所示，每次开机自启都会出现

**Comment by rmbadmin** [comment]
目前V1版本暂时停止更新专心重做V2了，届时会修复此问题，请耐心等待一段时间

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
