### ISSUE TITLE
加速功能卡windows更新

### ISSUE THREAD

**Issue by NGXAS** [SteamTools-Team/SteamTools#113]
反代加速时，使用windows系统代理方式会使windows系统更新补丁无法下载，这个是bug还是因为开了反代加速所以说windows更新的服务器被自动引导到了国外？

**Comment by rmbadmin** [comment]
一般来说推荐用hosts模式，windows系统代理方式是全局的所以其实并不太好用
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
