### ISSUE TITLE
希望默认加入steam创意工坊大图修复脚本（但不默认勾选）

### ISSUE THREAD

**Issue by yuijker** [SteamTools-Team/SteamTools#115]
由于众所周知的原因，创意工坊是无法直接访问的。反代只是解决了一小部分的问题，实际上工坊物品里面的大图无法访问。我在想，能不能内置一个脚本用于修复这一问题？
Greasy Fork上面有这种脚本：https://greasyfork.org/zh-CN/scripts/397666-steam-workshop-image-repair

**Comment by rmbadmin** [comment]
感谢建议，可以加入

**Comment by rmbadmin** [comment]
已经在2.1.0加入此脚本
