### ISSUE TITLE
特性请求：Github的Git同步代理

### ISSUE THREAD

**Issue by YogurtZebra** [SteamTools-Team/SteamTools#118]
最近一直抽风报403，所以请求一个代理
![image](https://user-images.githubusercontent.com/57581480/110211985-30b0ed00-7ed4-11eb-840f-352eb81de3e3.png)

**Comment by YogurtZebra** [comment]
以及启用windows系统代理方式后github访问速度明显变慢，要等很久

**Comment by Akarinnnnn** [comment]
毕竟Steam++自身升级也要用到github

**Comment by AigioL** [comment]
> 毕竟Steam++自身升级也要用到github

马上就不用了

**Comment by YogurtZebra** [comment]
以及想问一下youtube的封锁原理是什么？如果有可能代理的话另开issue

**Comment by YogurtZebra** [comment]
以及最近github似乎被墙了？正常访问能ping通但是连接一直被重置

**Comment by rmbadmin** [comment]
已经找到方法实现了，不过使用时需要让git信任windows的根证书

git 2.1.4以上版本可以使用以下设置
```
git config --global http.sslBackend schannel
```

其它平台可能是尝试使用
```
git config --global http.sslCAInfo /etc/ssl/certs/rorcz_root_cert.pem
```

具体的加速服务将在下个版本发布

**Comment by rmbadmin** [comment]
https://github.com/SteamTools-Team/SteamTools/discussions/234
