### ISSUE TITLE
部分 hosts 记录丢失

### ISSUE THREAD

**Issue by Miyakowww** [SteamTools-Team/SteamTools#119]
### 🐛 描述(Description)

如果 hosts 里原本有 example.com 的记录，并且 Steam++ 也会代理 example.com，那么开启再关闭代理后原本的记录会丢失

### 🚑 基本信息(Basic Information)

- 有问题的版本(Version with issue): v1.1.4
- 程序版本(Program Version): v1.1.4
- 系统版本号(OS Version): Windows 10.19042.804

**Comment by rmbadmin** [comment]
意思是要能还原之前原本存在的相同hosts记录吗？现在的处理逻辑确实是去掉了重复的hosts

**Comment by Miyakowww** [comment]
是啊，万一只是想试试这个软件（比如我）然后发现之前的 hosts 丢了岂不是很难受

**Comment by AigioL** [comment]
fix https://github.com/SteamTools-Team/SteamTools/commit/41faafdce2ad9b1a8cdc892ac668109c0e497b88
