### ISSUE TITLE
🐛[BUG] 测试本地反代功能的时候（用的是项目的源码），一直Exception

### ISSUE THREAD

**Issue by xmgcoffee** [SteamTools-Team/SteamTools#120]
### 🐛 描述(Description)

测试本地反代功能的时候（用的是项目的源码），一直Exception。大概可能的原因是什么？

### 📄 [异常/日志]信息([Exception/Log] Information)
   在 Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__197.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__197.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__197.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Titanium.Web.Proxy.ProxyServer.<handleClient>d__207.MoveNext()

### 🖼 截图(Screenshots)
![Screenshots](https://i.loli.net/2021/03/09/8fgKzQne74WsmLU.jpg)
![Screenshots](https://i.loli.net/2021/03/09/vMwu3HkinQhryXp.jpg)

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
