### ISSUE TITLE
👑[Enhancement] Deepin 20.1 & UOS 20 测试可用

### ISSUE THREAD

**Issue by 8MiYile** [SteamTools-Team/SteamTools#121]
### 🥰 需求描述(Description)
修改Readme.md

### 🧐 解决方案(Solution)
测试Linux方面的Deepin 20.1 与 UOS 20 都可用本程序
可在Readme.md添加这两个发行版

### 🚑 其他信息(Other Information)
无

**Comment by AigioL** [comment]
https://github.com/SteamTools-Team/SteamTools/commit/7418fd121c75fa1b1326752f7fc8bf28287da214
