### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by Rean107** [SteamTools-Team/SteamTools#125]
### 🐛 描述(Description)
国际服csgo游戏中，无法加载除自己以外的玩家头像

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):

**Comment by rmbadmin** [comment]
是否开了社区加速功能？启用了哪些加速服务？，有试过启用steam图片加速服务吗？

**Comment by Rean107** [comment]
> 是否开了社区加速功能？启用了一些加速服务？，有试过启用steam图片加速服务吗？

![QQ图片20210311212700](https://user-images.githubusercontent.com/67539759/110794393-acce7a80-82b0-11eb-8ba1-f81eb6d4eddf.png)
应该都开了

**Comment by rmbadmin** [comment]
可以尝试关掉steam图片代理功能在试试

**Comment by Rean107** [comment]
> 可以尝试关掉steam图片代理功能在试试

![QQ图片20210311213204](https://user-images.githubusercontent.com/67539759/110794993-4a29ae80-82b1-11eb-96e2-d1f41758c72f.jpg)
好像还是无法加载，看最上面那排，只有我自己的头像

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
