### ISSUE TITLE
在开启vpn以及社区加速之后，商店会随着VPN的节点而换区🧐[Question] 

### ISSUE THREAD

**Issue by xierock** [SteamTools-Team/SteamTools#126]
### 🧐 问题描述(Description)

我开了vpn挂的节点是美国的，然后我开了加速社区的服务之后，一刷新我的steam商店就立刻变成美区了，而当我的VPN的节点切换到对应国家的节点的时候，商店位置就会立刻切换到对应的国家。想请问一下这是怎么一回事，可以弄成和VPN共存吗，因为平时我都是VPN常挂着的。

**Comment by xierock** [comment]
我也不太清楚是我的问题还是软件的问题，可能是我的问题导致的，可以告诉一下怎么解决这个问题吗

**Comment by rmbadmin** [comment]
你的vpn是否开启了全局代理，代理了steam的域名？
同时你是否启用了脚本，启用了解锁不可描述商店页这个脚本吗？

可以尝试关掉这个脚本试试。

**Comment by xierock** [comment]
好像是因为我的VPN代理了steam的域名，可以帮我看看怎么取消掉steam的代理吗
![image](https://user-images.githubusercontent.com/80032731/111023574-ba5a3200-838e-11eb-9225-4d541030b039.png)
是直接在 ↓不走VPN通道↓ 下面直接写上steampowered.com就可以了吗

**Comment by rmbadmin** [comment]
> 好像是因为我的VPN代理了steam的域名，可以帮我看看怎么取消掉steam的代理吗
> ![image](https://user-images.githubusercontent.com/80032731/111023574-ba5a3200-838e-11eb-9225-4d541030b039.png)
> 是直接在 ↓不走VPN通道↓ 下面直接写上steampowered.com就可以了吗

可以参考图中写法大概是在direct_list中新起一行，复制以下内容
```
# (^|\.).steampowered\.com$
```

**Comment by xierock** [comment]
可以了！是我这边的问题，不是软件的问题，应该是VPN把steam代理了
