### ISSUE TITLE
👑[Enhancement] 希望新增本地代理支持

### ISSUE THREAD

**Issue by CallMeReznov** [SteamTools-Team/SteamTools#127]
### 🥰 需求描述(Description)

希望加入对本地代理的支持.  
很多人,比如我个人都有本地http与socks5代理服务,不知道可以卜可以直接开放使用自己提供的代理作为选项提高灵活性

PS: 另外,软件自带日志功能,建议初期默认开启日志功能,方便收集反馈,我是闪退过一次后才发现默认没开日志功能的.

**Comment by rmbadmin** [comment]
更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)

**Comment by CallMeReznov** [comment]
牛批!
