### ISSUE TITLE
👑[Enhancement] 能否在gitee上建立同步镜像？

### ISSUE THREAD

**Issue by 653448346** [SteamTools-Team/SteamTools#131]
### 🥰 需求描述(Description)
github不是很稳定，gitee的访问方便一些
### 🧐 解决方案(Solution)
这是gitee官方文档
https://gitee.com/help/articles/4284#article-header0
### 🚑 其他信息(Other Information)

**Comment by rmbadmin** [comment]
已经在添加了gitee的仓库地址
https://gitee.com/rmbgame/SteamTools

**Comment by 653448346** [comment]
看起来是gitee的搜索有问题。。直接使用steamtools 或SteamTools搜索不到仓库，需要在两个单词间加空格才行。。。
