### ISSUE TITLE
👑[Enhancement] 字体更换功能请求

### ISSUE THREAD

**Issue by YogurtZebra** [SteamTools-Team/SteamTools#132]
### 🥰 需求描述(Description)

建议增加修改页面字体的功能（总感觉默认字体丑

**Comment by AigioL** [comment]
https://user-images.githubusercontent.com/24450093/115650067-200ce700-a35b-11eb-9a80-2b0eaa65e909.mp4

fix https://github.com/SteamTools-Team/SteamTools/commit/e0a478d6ac3a7168668cd52f8e08a5ce29acda9d
