### ISSUE TITLE
👑[Enhancement] 更改hosts注释格式

### ISSUE THREAD

**Issue by YogurtZebra** [SteamTools-Team/SteamTools#135]
### 🥰 需求描述(Description)

在每一个host后都带注释有点丑，建议更改为如下格式

### 🧐 解决方案(Solution)

原来：
> 127.0.0.1 steamcommunity.com #Steam++
127.0.0.1 www.steamcommunity.com #Steam++
…

更改后：
>\# Steam++ Start
>127.0.0.1 steamcommunity.com
>127.0.0.1 www.steamcommunity.com
>...
>\# Steam++ End
### 🚑 其他信息(Other Information)

无

**Comment by AigioL** [comment]
fix https://github.com/SteamTools-Team/SteamTools/commit/41faafdce2ad9b1a8cdc892ac668109c0e497b88
