### ISSUE TITLE
🐛[BUG] 一键确认交易时出错

### ISSUE THREAD

**Issue by Hengkongchushi83** [SteamTools-Team/SteamTools#136]
在一键确认交易时报错 版本1.1.4
[20210323.log](https://github.com/SteamTools-Team/SteamTools/files/6190645/20210323.log)
![image](https://user-images.githubusercontent.com/81248614/112169259-02017900-8c2d-11eb-9a3f-3777d05fb902.png)

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
