### ISSUE TITLE
🐛[BUG] 托盘菜单无法自动适配黑暗颜色

### ISSUE THREAD

**Issue by AuroraRock** [SteamTools-Team/SteamTools#138]
### 📷 复现步骤(Steps to Reproduce)

1. 浅色模式打开程序
2. 切换深色模式
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):1.1.4
- 系统版本号(OS Version): Windows 10.19042.870

### 🖼 截图(Screenshots)

![Screenshot 2021_3_27 18_41_35](https://user-images.githubusercontent.com/35655459/112718162-18108180-8f2c-11eb-8f6d-e6c1ffff2b3b.png)

**Comment by rmbadmin** [comment]
1.x版本的托盘菜单切换后要重启程序才会生效更改
