### ISSUE TITLE
🐛[BUG] Twitch无法注册与登录

### ISSUE THREAD

**Issue by YogurtZebra** [SteamTools-Team/SteamTools#141]
### 🐛 描述(Description)

twitch可以正常访问与查看视频，但是登录时点击登录按钮无反应，注册也是一样

### 📷 复现步骤(Steps to Reproduce)

1. 打开twitch
2. 点击登录按钮，弹出登录窗口
3. 填写登录信息，点击登录按钮
4. 没有反应，注册同

### 📄 [异常/日志]信息([Exception/Log] Information)
无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 1.1.4
- 系统版本号(OS Version): 
Win10 19042

### 🖼 截图(Screenshots)

无

**Comment by rmbadmin** [comment]
2.1.0应该已经修复此问题，在我这可以正常登陆

**Comment by YogurtZebra** [comment]
> 2.1.0应该已经修复此问题，在我这可以正常登陆

问题已解决
但同时发现twitch的帮助页面（help.twitch.tv）无法访问

**Comment by AigioL** [comment]
社区加上遗漏的域名现统一在 #318 中管理，所以这边先关闭了。
