### ISSUE TITLE
更新windows无法使用

### ISSUE THREAD

**Issue by GamesDownload** [SteamTools-Team/SteamTools#142]
更新20H2的Windows系统之后，无法运行程序，报错，错误代码如下

system.IO.FileNotFoundException:系统找不到指定的文件。(异常来自HRESULT:0x80070002)
在MetroRadiance.Interop.Win32.Dwmapi.DwmGetColorizationColor(UInt32&pcrColorization, Boolean& pfOpaqueBlend)
在MetroRadiance.Platform.Accentvalue.Getvalueo
在MetroRadiance.Platform.WindowsThemevalue`1.get_Current(
在MetroRadiance.Ul.Themeservice.GetAccentResource(Accent accent)MetroRadiance.Ul.ThemeService.Register(ResourceDictionary rd, Themetheme, Accent accent)
在SteamTools.App.Onstartup(StartupEventArgs e)
在System.Windows.Application.<.ctor>b__1_o(Object unused)
在System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegatecallback, Object args, Int32 numArgs)
在System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,Delegate callback, Object args, Int32 numArgs,Delegate catchHandler)

**Comment by rmbadmin** [comment]
之后的2.0版本会修复此问题，目前来看这个问题是因为dwmapi.dll出来问题。2.0版本不再依赖此API

**Comment by GamesDownload** [comment]
好的，等待更新

**Comment by GamesDownload** [comment]
后Windows继续提示更新，将20H2的1，2，3三个累积更新包更新完成，并重启电脑之后，BUG消失，可以正常使用了

**Comment by YogurtZebra** [comment]
我也出过这个问题
dwmapi.dll本来应该是自带的，但是憨憨微软给删了
正常来讲是会有这个dll的，不必太在意

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
