### ISSUE TITLE
如何反代理GitHub网站？

### ISSUE THREAD

**Issue by lzkids** [SteamTools-Team/SteamTools#143]
### 🧐 问题描述(Description)
我在软件只找到GitHub图片资源和gist的代理服务，没看到github的代理

**Comment by rmbadmin** [comment]
目前还没有加github的反代

**Comment by YogurtZebra** [comment]
Github现在疑似被墙
已知部分地区（如福建移动）对部分主机设墙，会出现连接多次重置的现象

**Comment by rmbadmin** [comment]
> Github现在疑似被墙
> 已知部分地区（如福建移动）对部分主机设墙，会出现连接多次重置的现象

嗯，我会尝试加上github的反代支持，我研究了一下应该是可行的

**Comment by lzkids** [comment]
> 
> 
> Github现在疑似被墙
> 已知部分地区（如福建移动）对部分主机设墙，会出现连接多次重置的现象

我这边也歇菜了好像是

**Comment by lzkids** [comment]
@rmbadmin 我这边ping显示127.0.0.1了也不知道咋回事。就GitHub.com显示127.0.01

**Comment by YogurtZebra** [comment]
> @rmbadmin 我这边ping显示127.0.0.1了也不知道咋回事。就GitHub.com显示127.0.01

我这里可以ping通，显示湖南那边的dns，但是就是访问不了

**Comment by rmbadmin** [comment]
将会在下个版本添加github网站及git sync操作加速的服务

**Comment by rmbadmin** [comment]
https://github.com/SteamTools-Team/SteamTools/discussions/234
