### ISSUE TITLE
👑[Enhancement] 希望能加入对家庭共享库来源排序

### ISSUE THREAD

**Issue by arises** [SteamTools-Team/SteamTools#146]
### 🥰 需求描述(Description)

在有多个家庭共享时共享优先级比较修改比较麻烦，希望能加入可视化的修改

### 🧐 解决方案(Solution)

Steam\config文件夹下的config.vdf文件中记录了授权设备
将该文件中的"AuthorizedDevice"项目中的信息修改顺序便能实现排序
key值即为好友的steamid 能使用它读取到相关的信息

### 🚑 其他信息(Other Information)

**Comment by rmbadmin** [comment]
这个是有计划的加入的，后续有时间会加上

**Comment by rmbadmin** [comment]
2.4.9版本已经更新此功能
