### ISSUE TITLE
🐛[BUG] One or more errors occurred

### ISSUE THREAD

**Issue by wordlesswind** [SteamTools-Team/SteamTools#149]
### 🐛 描述(Description)

无法登录 Steam 帐户用于交易确认，Steam Desktop Authenticator 和 WinAuth 存在类似的问题。

[SteamDesktopAuthenticator#634](https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/634), [SteamDesktopAuthenticator#678](https://github.com/Jessecar96/SteamDesktopAuthenticator/issues/678)

### 📷 复现步骤(Steps to Reproduce)

1. 点击“交易确认”按钮
2. 输入帐户和密码
3. 等待一会，弹出错误

### 📄 [异常/日志]信息([Exception/Log] Information)

![Screenshot 2021-04-12 130748](https://user-images.githubusercontent.com/9050713/114343499-91e17580-9b90-11eb-928b-4d6f32db52d9.png)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 1.1.4
- 系统版本号(OS Version): Windows 10 OS Version 2009 (Build 19042.906)

**Comment by rmbadmin** [comment]
是否开启了社区加速的功能，这里不开加速是无法登陆的

**Comment by wordlesswind** [comment]
> 是否开启了社区加速的功能，这里不开加速是无法登陆的

不好意思，是我疏忽了，忘记了自己不是系统代理模式，希望 Steam++ 以后可以支持自定义设置 HTTP 代理或者 Socks5 代理。
然后关于帐户登录这一方面，既然交易确认是根据帐户来的，那么建议在登录框内自动填写好帐户用户名。
![Screenshot 2021-04-12 132047](https://user-images.githubusercontent.com/9050713/114344174-e9ccac00-9b91-11eb-9309-a27228b757e1.png)

**Comment by rmbadmin** [comment]
嗯，steam++应该是会默认走系统代理的，如果要自己设置http代理或者sock代理后续会加上设置提供支持。
令牌交易确认这一块在2.0会进行优化。
