### ISSUE TITLE
👑[Enhancement] 脚本相关

### ISSUE THREAD

**Issue by KIMKILL** [SteamTools-Team/SteamTools#151]
### 🥰 需求描述(Description)

steam不可描述脚本失效  前段时间去原作者的帖子看了下  说失效了 不能用了

### 🧐 解决方案(Solution)

建议删除

### 🚑 其他信息(Other Information)

希望更多大佬可以写出好用的脚本 球球了！

**Comment by rmbadmin** [comment]
steam不可描述这个脚本确实已经失效了，
在2.0版本中将会脚本将会是从服务端加载，方便脚本作者热更新维护，目前1.x版本停止维护所以没有修改。

**Comment by rmbadmin** [comment]
因steam最新的政策更新，该脚本已经无法在使用了
