### ISSUE TITLE
🐛[BUG] 除Steam以外所有代理无效（如Discord和GitHub）

### ISSUE THREAD

**Issue by xrb936** [SteamTools-Team/SteamTools#152]
除Steam以外所有代理无效（如Discord和GitHub），未尝试使用Hosts文件。

**Comment by rmbadmin** [comment]
会在2.0版本中修复失效的加速服务

**Comment by xrb936** [comment]
好的，请问2.0什么时候会发布呢？

**Comment by AigioL** [comment]
预计本月内发布 2.0 目前进度可在 2021-04 里程碑中查看 https://github.com/SteamTools-Team/SteamTools/issues/147
