### ISSUE TITLE
🧐[Question] steam客户端 -101错误怎么办

### ISSUE THREAD

**Issue by laozhou1204** [SteamTools-Team/SteamTools#154]
### 🧐 问题描述(Description)
 **steam客户端 -101错误怎么办**

![QQ图片20210424175520](https://user-images.githubusercontent.com/47948826/115954942-4e8aed80-a526-11eb-8730-46975b25f792.png)

**Comment by rmbadmin** [comment]
可能与证书有关，确认一下证书是否正常安装，可以启用程序的日志记录反馈下日志

**Comment by laozhou1204** [comment]
> 可能与证书有关，确认一下证书是否正常安装，可以启用程序的日志记录

2021-04-27 01:02:34,934 ERROR >> System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 接收时发生错误。 ---> System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 SteamTool.Core.HttpServices.<SendAsync>d__9.MoveNext()
2021-04-27 01:02:34,941 ERROR >> System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 接收时发生错误。 ---> System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   在 System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 SteamTool.Core.HttpServices.<SendAsync>d__9.MoveNext()

**Comment by rmbadmin** [comment]
这个问题看起来错误不是代理的问题，可能是获取账号头像的问题

**Comment by rmbadmin** [comment]
需要截取的日志是反代相关的，你可以先操作上复现一下反代的问题，这样就会记录对应日志

**Comment by laozhou1204** [comment]
> 需要截取的日志是反代相关的，你可以先操作上复现一下反反的问题，这样就会记录对应日志

打勾了  **windows代理方式**  恢复正常  不打勾 什么都打不开都是-101错误

**Comment by rmbadmin** [comment]
关闭一些可能已解决的历史问题，如果问题依然存在可自行恢复。
