### ISSUE TITLE
👑[Enhancement] 建议在账号切换和本地令牌里添加手动排序功能

### ISSUE THREAD

**Issue by AllureLove98** [SteamTools-Team/SteamTools#157]
### 🥰 需求描述(Description)

建议在账号切换和本地令牌里添加手动排序功能

### 🚑 其他信息(Other Information)

[![gCIRJ0.png](https://z3.ax1x.com/2021/04/28/gCIRJ0.png)](https://imgtu.com/i/gCIRJ0)

**Comment by rmbadmin** [comment]
本地令牌可右键排序，账号切换是按登录时间倒序默认排序暂不支持修改。
