### ISSUE TITLE
🐛[BUG] 社区加速按钮排版出现问题

### ISSUE THREAD

**Issue by AllureLove98** [SteamTools-Team/SteamTools#159]
### 🐛 描述(Description)

在分辨率为816*639时 社区加速里的一键加速按钮和证书设置相关设置会超出程序的大小

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

[![gCokfP.png](https://z3.ax1x.com/2021/04/28/gCokfP.png)](https://imgtu.com/i/gCokfP)
[![gCoFYt.png](https://z3.ax1x.com/2021/04/28/gCoFYt.png)](https://imgtu.com/i/gCoFYt)

**Comment by rmbadmin** [comment]
已经修复
