### ISSUE TITLE
🐛[BUG] 网络错误

### ISSUE THREAD

**Issue by AllureLove98** [SteamTools-Team/SteamTools#160]
### 🐛 描述(Description)

当打开代理软件时再打开软件 然后退出的代理软件 在登录/注册界面点击获取验证码 会提示服务端错误1006

### 📷 复现步骤(Steps to Reproduce)

1. 打开代理软件
2. 退出代理软件
3. 点击获取验证码

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-04-28.log](https://github.com/SteamTools-Team/SteamTools/files/6386660/nlog-all-2021-04-28.log)
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![0T4~Q7BHKNF {E4V7QX@15](https://user-images.githubusercontent.com/38179237/116291261-f45c8780-a7c6-11eb-9fd5-43294bc3dbc5.png)

**Comment by rmbadmin** [comment]
已经修复
