### ISSUE TITLE
🐛[BUG] 脚本配置启动脚本无效

### ISSUE THREAD

**Issue by KNBLG** [SteamTools-Team/SteamTools#162]
### 🐛 描述(Description)

脚本配置右上角齿轮设置，启动脚本无效

### 📷 复现步骤(Steps to Reproduce) 
1.启动加速，切换到脚本控制（未启动脚本）点击齿轮 启动脚本 无效果
2.关闭加速，切换到脚本控制（未启动脚本）点击齿轮 启动脚本 无效果
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/63439312/116294775-f32d5980-a7ca-11eb-805d-c96ecbe69615.png)

**Comment by AllureLove98** [comment]
可以复现此bug
