### ISSUE TITLE
🐛[BUG] 最大化窗口时会出现短暂透明度变高

### ISSUE THREAD

**Issue by KNBLG** [SteamTools-Team/SteamTools#163]
### 🐛 描述(Description)

软件最大化或者最者向下还原的时候会出现短暂透明度变高。

### 📷 复现步骤(Steps to Reproduce)

最大化或者向下还原

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/63439312/116297209-9c754f00-a7cd-11eb-896f-4f2ae55d4161.png)
正常透明度
![image](https://user-images.githubusercontent.com/63439312/116297255-a9923e00-a7cd-11eb-91a1-f4babdda4c6a.png)
非正常透明度

**Comment by AigioL** [comment]
这个问题属于一个上游问题，因为使用的 UI 框架 [AvaloniaUI](https://github.com/AvaloniaUI/Avalonia) 提供的亚克力效果实现上，在窗口大小发生变化时，停止绘制了模糊层，导致了这个问题。

这部分实现的代码在 UI 框架中，我们暂时没有空闲的时间与人手能去处理这个问题。

你可以在 UI 框架的仓库 [issue](https://github.com/AvaloniaUI/Avalonia/issues) 上使用英文提问。
