### ISSUE TITLE
🐛[BUG] 删除账号数据时会删除用户所有的配置文件

### ISSUE THREAD

**Issue by AllureLove98** [SteamTools-Team/SteamTools#165]
### 🐛 描述(Description)

在软件删除账号数据时会删除用户所有的配置文件 已知包括csgo的设置
steam++1.4和steam++beta 2.0.0都有此问题

### 📷 复现步骤(Steps to Reproduce)

1. 在软件里删除账号数据 会导致被删除的账号数据全部删除

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):steam++1.4 steam++beta 2.0.0 
- 系统版本号(OS Version):

**Comment by rmbadmin** [comment]
这是功能的机制，删除这个功能就是这么做的，会清楚账号的所有数据，提示也写明了。

**Comment by AllureLove98** [comment]
我觉得这个功能可以优化下 不然连游戏设置都删除了有点不能接受

**Comment by rmbadmin** [comment]
下个版本可以多弹一个选择是否删除用户数据的提示来自主选择是否删除帐户的配置数据
