### ISSUE TITLE
🐛[BUG] 断网状态下启动steam++加速闪退

### ISSUE THREAD

**Issue by KNBLG** [SteamTools-Team/SteamTools#166]
### 🐛 描述(Description)

断网状态下启动steam++后  社区加速界面为空白  此时点击《一键加速》闪退

### 📷 复现步骤(Steps to Reproduce)

1. 断开网络
2. 启动steam++  社区加速（此时社区加速为空白界面）  一键加速（此时发生闪退现象）
3. 断网启动后  连接网络  此时steam++ 加速界面仍为空白连接网络后不会自动刷新    点击一键加速后仍然发生闪退现象  
4. 重启软件后恢复正常

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/63439312/116372755-548f1000-a83f-11eb-92eb-f6dea59ce001.png)

**Comment by AigioL** [comment]
之前的版本应该已经修复了这些问题，如果使用最新版确认问题还能复现，可以再次打开问题。
