### ISSUE TITLE
👑[Enhancement] 加速页和令牌页右上角的设置按钮太容易被忽略

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#168]
### 🥰 需求描述(Description)
我差点以为没做开机自启反代，直到我看到了右上角的设置按钮

### 🧐 解决方案(Solution)
放到加速页主界面

顺便起始页可以像Clash for Windows那样做成快捷操作面板，操作更方便

### 🚑 其他信息(Other Information)
起始页想法：
|整行|标题|和版本|
|---|---|---|
|快捷开关1|快捷开关2|快捷开关3|
|快捷开关4|快捷开关5|快捷开关6|

![屏幕截图 2021-04-29 070912](https://user-images.githubusercontent.com/39186981/116485762-37495880-a8b6-11eb-9b90-ca7ba66d54c6.png)

之前群里还有人问是不是没开发自启加速的2333

**Comment by rmbadmin** [comment]
感谢建议

**Comment by cyb233** [comment]
> 感谢建议

faq里加上hosts和Windows代理区别说明吧，群里天天有人问，感觉没必要新提issues就在这回复了

**Comment by rmbadmin** [comment]
2.0版本已改进
