### ISSUE TITLE
🐛[BUG] 游戏成就功能

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#169]
### 🐛 描述(Description)
环境：Steam离线状态，电脑无网络
现象：未安装的游戏：提示找不到数据
已安装的游戏：Steam上运行中，且Steam++无任何窗口提示

### 📷 复现步骤(Steps to Reproduce)

1. 断网
2. 离线启动Steam，Steam++
3. 未安装/已安装游戏右击解锁成就

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-04-28.log](https://github.com/SteamTools-Team/SteamTools/files/6393101/nlog-all-2021-04-28.log)
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6393103/internal-nlog.txt)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):beta第一版，第二版我还没看
- 系统版本号(OS Version): Windows 10.19041.508

#### 🤬一些额外碎碎念
我一开始在群里说的时候被其他群员怼了，真的有毛病，你不在乎别人在乎，后来屏蔽拉黑了，是谁不说了免得说挂人，反正聊天记录搜得到

**Comment by cyb233** [comment]
beta2版
未安装的游戏：虽然无提示不过不会游戏保持运行
已安装的游戏：正常提示错误
应该算是Fixed了吧

**Comment by AigioL** [comment]
目前最新版本如果还有这些问题，可以再次打开 issue。
