### ISSUE TITLE
希望能够在游戏列表页面双击某一行来打开成就解锁对话框

### ISSUE THREAD

**Issue by ad52825196** [SteamTools-Team/SteamTools#17]
目前在游戏列表页面，要打开某个游戏的成就解锁，必须通过点击右侧的图标来完成，而在 Steam Achievement Manager 中可以通过双击来完成，希望这里也能支持双击操作，用起来会方便一点。

**Comment by rmbadmin** [comment]
因为SAM里的列表比较简单且功能只会有一个，但我预期完善的游戏列表还会有更多功能，所以还没有决定双击操作默认执行哪个功能。

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
