### ISSUE TITLE
👑[Enhancement] 脚本功能

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#172]
### 🥰 需求描述(Description)
脚本增加去重功能，我在beta1时把旧版脚本导入进了新版，随后beta2从脚本市场下载同名脚本会显示两个不同版本的

再次测试时我将v0.21的GM脚本改成0.20，提示有更新，但更新后列表同时出现0.20和0.21，且0.20继续提示更新

PS：GM脚本根据描述不应该像以前那样直接软件自带不可删除吗？

### 🧐 解决方案(Solution)
根据脚本@name和@version参数对脚本去重

**Comment by Mossimos** [comment]
现在加了如果自己添加相同名字的脚本会弹出提示框选择是否替换，不替换的话不会导入。

**Comment by cyb233** [comment]
> 现在加了如果自己添加相同名字的脚本会弹出提示框选择是否替换，不替换的话不会导入。

我在 #176 描述的我之前测试加的重复脚本GM现在删不掉了怎么办😂脚本配置储存在哪里啊，我手动删除试试看

**Comment by Mossimos** [comment]
2.1.0版本会自动移除多余的Gmjs了,要删除的话AppData\Scripts 和 Cache\Scripts 下全部文件删除就清除了
