### ISSUE TITLE
👑[Enhancement] 任务栏图标

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#175]
### 🥰 需求描述(Description)
右键增加更方便的选项，例如像winauth的复制令牌等

### 🧐 解决方案(Solution)
设想：

> 主页（打开起始页）
> 社区加速（切换开关）
> 账号切换（展开列表）

>> 账号1（点击切换）
>> 账号2

> 库存游戏（打开库存游戏页面）
> 本地令牌（展开列表）

>> 令牌1（点击复制）
>> 令牌2

> 设置（打开设置）
> 深色模式（切换开关）
> 关于（打开关于）
> 退出（退出软件）

**Comment by rmbadmin** [comment]
感谢建议，新版的托盘菜单还在制作中

**Comment by rmbadmin** [comment]
最新版2.4.12已经支持。
