### ISSUE TITLE
👑[Enhancement] 增加毛玻璃透明度

### ISSUE THREAD

**Issue by Astesai** [SteamTools-Team/SteamTools#179]
### 🥰 需求描述(Description)

增加毛玻璃透明度

### 🧐 解决方案(Solution)

增加毛玻璃透明度

### 🚑 其他信息(Other Information)

增加毛玻璃透明度

**Comment by YogurtZebra** [comment]
其实最好是加一个能自己调整的选项

**Comment by rmbadmin** [comment]
下个版本会支持自己在UI设置中调整

**Comment by YogurtZebra** [comment]
发现缩放窗口时透明度会变化
