### ISSUE TITLE
🐛[BUG] hosts代理模式安装证书后加速仍然显示证书安装失败

### ISSUE THREAD

**Issue by DVonderhaar** [SteamTools-Team/SteamTools#183]
### 🐛 描述(Description)
已按照提示安装了证书，但是开启加速后仍会显示证书安装失败。
### 📷 复现步骤(Steps to Reproduce)
1.选择hosts代理模式
2.加速
3.安装证书
4.提示证书安装失败
### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-05-01.log](https://github.com/SteamTools-Team/SteamTools/files/6409528/nlog-all-2021-05-01.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0.0.6
- 系统版本号(OS Version): Windows 10.19043.964

### 🖼 截图(Screenshots)
![捕获](https://user-images.githubusercontent.com/30433000/116782147-12253780-aaba-11eb-99fb-3aa164a7865c.PNG)

**Comment by baiuu** [comment]
我也是一样的情况 确认是bug了嘛

**Comment by DVonderhaar** [comment]
> 我也是一样的情况 确认是bug了嘛

确定是bug，用v1版本的就可以正常使用，v2的目前只能用系统代理

**Comment by rmbadmin** [comment]
下个版本会修复
