### ISSUE TITLE
🐛[BUG] 不知道怎么出现的错误，我完全看不懂（哭笑）

### ISSUE THREAD

**Issue by khronors1** [SteamTools-Team/SteamTools#184]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 📄 [异常/日志]信息([Exception/Log] Information)System.ComponentModel.Win32Exception (Ox80004005):拒绝访问.在System.Diagnostics.Process.KillO
Win32Exception(Ox80004005)：拒绝访问。在系统.诊断.过程.杀人

在SteamTool.Core.SteamToolService.KillSteamProcess0
SteamTool.Core.SteamToolService.KillSteamProcess0在

在SteamTools.ViewModels.SteamAccountPageViewModel.Steamld_OnClick(String parameter)在lambda_method(Closure , Object , Object )
SteamTools.ViewModels.SteamAccountPageViewModel.Steamld_OnClick(String参数)在lambda_在方法(闭包、对象、对象)

在Livet.Behaviors.MethodBinderWithArgument.Invoke(Object targetObject, String methodName, Object argument)在Livet.Behaviors.LivetCallMethodAction.Invoke(Object parameter)
对象、字符串方法名、对象参数)Livet.Behaviors.MethodBinderWithArgument.Invoke(Object Livet.Behaviors.LivetCallMethodAction.Invoke(Object参数)

在Microsoft.Xaml.Behaviors.TriggerBase.lInvokeActions(Object parameter)在Microsoft.Xaml.Behaviors.EventTriggerBase.OnEvent(EventArgs eventArgs)
(Microsoft.Xaml.Behaviors.TriggerBase.lInvokeActions(Object在参数)在Microsoft.Xaml.Behaviors.EventTriggerBase.OnEvent(EventArgs Event Args)

在Microsoft.Xaml.Behaviors.EventTriggerBase.OnEventlmpl(Object sender,EventArgs eventArgs)
Microsoft.Xaml.Behaviors.EventTriggerBase.OnEventlmpl(Object发送者，事件发送者(在)

在System.Windows.RoutedEventHandlerlnfo.InvokeHandler(Object target,RoutedEventArgs routedEventArgs)在System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)在System.Windows.UIElement.RaiseEventlmpl(DependencyObject sender, RoutedEventArgs args)
System.Windows.RoutedEventHandlerlnfo.InvokeHandler(Object在在，RoutedEventArgs routedEventArgs)在在源，RoutedEventArgs ARG，布尔重定位)在System.Windows.UIElement.RaiseEventlmpl(DependencyObject发件人，RoutedEventArgs)

在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
System.Windows.UIElement.RaiseEvent(RoutedEventArgs(在)

在System.Windows.Controls.Primitives.ButtonBase.OnClicko在System.Windows.Controls.Button.OnClicko
System.Windows.Controls.Primitives.ButtonBase.OnClicko在在System.Windows.Controls.Button.OnClicko

在System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)在System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
(System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs在e)在System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object发件人，MouseButtonEventArgs e)

在System.Windows.InputMouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)在System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
System.Windows.InputMouseButtonEventArgs.InvokeEventHandler(Delegate泛型处理程序，对象泛型目标)在System.Windows.RoutedEventArgs.InvokeHandler(Delegate处理程序，对象目标)

在System.Windows.RoutedEventHandlerinfo.InvokeHandler(Object target,RoutedEventArgs routedEventArgs)在System.Windows.EventRoute.InvokeHandlerslmpl(Object source, RoutedEventArgs args,Boolean reRaised)
System.Windows.RoutedEventHandlerinfo.InvokeHandler(Object在在，RoutedEventArgs routedEventArgs)在源，RoutedEventArgs ARG，布尔重新定义)

在System.Windows.UElementReRaiseEventAs(DependencyObject sender, RoutedEventArgs args,RoutedEvent newEvent)在System.Windows.UIElementOnMouseUpThunk(Object sender, MouseButtonEventArgs e)
System.Windows.UElementReRaiseEventAs(DependencyObject在发送者，RoutedEventArgs ARG，RoutedEventnewEvent)在System.Windows.UIElementOnMouseUpThunk(对象发送方，MouseButtonEventArgs)

在System.Windows.Input.MouseButtonEventArgs.lnvokeEventHandler(Delegate genericHandler, Object genericTarget)在System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
System.Windows.Input.MouseButtonEventArgs.lnvokeEventHandler(Delegate泛型处理程序，对象泛型目标)在System.Windows.RoutedEventArgs.InvokeHandler(Delegate处理程序，对象目标)

在System.Windows.RoutedEventHandlerinfo.InvokeHandler(Object target,RoutedEventArgs routedEventArgs)在System.Windows.EventRoute.nvokeHandlerslmpl(Object source, RoutedEventArgs args, Boolean reRaised)在System.Windows.UlElement.RaiseEventlmpl(DependencyObject sender,RoutedEventArgs args)
System.Windows.RoutedEventHandlerinfo.InvokeHandler(Object在在，RoutedEventArgs routedEventArgs)在在源，RoutedEventArgs ARG，布尔重定位)在System.Windows.UlElement.RaiseEventlmpl(DependencyObject发件人，RoutedEventArgs)

在System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs在)

在System.Windows.Input.InputManager.ProcessStagingArea0
System.Windows.Input.InputManager.ProcessStagingArea0在

在System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)在System.Windows.Input.InputProviderSite.Reportlnput(InputReport inputReport)
(System.Windows.Input.InputManager.ProcessInput(InputEventArgs输入)在System.Windows.Input.InputProviderSite.Reportlnput(InputReport inputReport)

在System.Windows.Interop.HwndMousenputProvidet.Reporthput(IntP'r hwnd InputMode mode, Int.2 timestamp, RawMouseActions actons lnt32x lnt2 y nt32wheel)
System.Windows.Interop.HwndMousenputProvidet.Reporthput(IntP‘r在hwnd输入模式，Int.2时间戳，RawmouseActions Actonint32xInt2ynt32轮)

在System.Windows.Interop.HwndMouselnputProvide.ilterMessage(ntPitr hwnd,WindowWMessage msg IntP'r wParam /ntPr lParam Booean& handled)在System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam IntPtTr lParam,Boolean& handled)
System.Windows.Interop.HwndMouselnputProvide.ilterMessage(ntPitr hwnd，WindowWMessage msg intp‘r wParam/ntpr lParam Booean&在)在System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd，Int 32 msg，IntPtr wParam IntPtTr lParam，布尔和在)

在MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam, Boolean& handled)
在MS.Win32.HwndWrapper.WndProc(IntPtr hwnd，Int 32 msg，IntPtr wParam，IntPtr Iparam，boole&handted)

在MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
(MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object)在)

在System.Windows.Threading.ExceptionWrapper.InternalReaiCal(Delegate callback, Object args,Int32 numArgs)
System.Windows.Threading.ExceptionWrapper.InternalReaiCal(Delegate回调，对象args，Int 32 numArgs)

在System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,Delegatecllback, Object args Int32 numArgs Delegate catchHandler)
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object在源代码，委托代理，对象ARGS Int 32 numArgs代表追赶处理程序)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):1.12
- 系统版本号(OS Version):

**Comment by AigioL** [comment]
咋还机翻上来了呢😅

**Comment by AigioL** [comment]
@rmbadmin 看起来是 V1 版本

**Comment by rmbadmin** [comment]
没有权限结束steam进程导致的

**Comment by rmbadmin** [comment]
可以尝试使用2.0版本，此问题应该已经修复
