### ISSUE TITLE
🧐[Question] Discord加速后，打开软件后一直显示更新失败

### ISSUE THREAD

**Issue by JackGlen1** [SteamTools-Team/SteamTools#185]
### 🧐 问题描述(Description)
Discord加速后，打开软件后一直显示更新失败

我从1.1.4的时候刚开始还能用，后来就无法使用了，然后等到2.0还是这个问题，是我的问题吗?还是代理没有更新

**Comment by xrb936** [comment]
DC反代看地區，一直都是有的地方可以有的地方不可以。我朋友遼寧移動就用不了。

**Comment by JackGlen1** [comment]
主要我之前是可以用的，只是在很平常的一天突然用不了了，不知道什么原因导致的。黑龙江联通




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SteamTools-Team/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月2日(星期天) 中午1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SteamTools-Team/SteamTools] 🧐[Question] Discord加速后，打开软件后一直显示更新失败 (#185)





 
DC反代看地區，一直都是有的地方可以有的地方不可以。我朋友遼寧移動就用不了。

**Comment by GodLikesYou** [comment]
建议还是挂加速器或者是"黑科技"吧
Discord 我只有在用"黑科技"后才不会出现打开软件更新失败的问题

**Comment by rmbadmin** [comment]
目前是更新下载这一块反代还有些问题，所以检测更新失败了，正在修复中

**Comment by JackGlen1** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月2日(星期天) 下午4:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SteamTools-Team/SteamTools] 🧐[Question] Discord加速后，打开软件后一直显示更新失败 (#185)





 
目前是更新下载这一块反代还有些问题，所以检测更新失败了，正在修复中
 
&mdash;

**Comment by jygxgxx** [comment]
steamcommunity_302里discord修改的hosts比较全

**Comment by JackGlen1** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        我就是因为steamcommunity_302不好使了才换的         
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                JackGlen
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年5月3日 ***@***.***> 写道： 




steamcommunity_302里discord修改的hosts比较全



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jygxgxx** [comment]
不能吧，你更新看看，302最新是V10.8.5

**Comment by rmbadmin** [comment]
2.1.0应该已经解决此问题。
