### ISSUE TITLE
🧐[Question] 如何下载老版本游戏？

### ISSUE THREAD

**Issue by NagaseYami** [SteamTools-Team/SteamTools#187]
### 🧐 问题描述(Description)

Steam++官方主页上有这么一句描述

>库存管理
该功能能够让您直接管理到 Steam 游戏库存，***不仅能够下载老版本的 Steam 游戏***，也能够对 Steam 游戏成就进行直接管理，支持解锁成就以及反解锁成就。

但我发现库存管理功能的游戏图标的右键菜单里的`安装`选项只是普通安装，并没有给我选择版本的地方
请问这个功能在哪里？

**Comment by rmbadmin** [comment]
目前并没有此功能也没有打算做此功能，确认为官网文本错误
