### ISSUE TITLE
🧐[成就管理无法弹出] 

### ISSUE THREAD

**Issue by FWshaozi** [SteamTools-Team/SteamTools#189]
### 🧐 问题描述
成就管理为什么无法弹出？点击“管理成就”之后就显示个正在启动中，任务管理器里面也显示了进程但是啥都没弹出......不知道是不是Bug所以发个问题解答吧~来个大神解答！！

### 🚑 其他信息
↓底下是截图
![1](https://user-images.githubusercontent.com/83530519/116805159-0b003700-ab57-11eb-97fa-cd16be5b7029.png)
![2](https://user-images.githubusercontent.com/83530519/116805262-b4dfc380-ab57-11eb-9e6d-059eb66fd8d3.png)

**Comment by rmbadmin** [comment]
logs文件夹是否有错误日志

**Comment by FWshaozi** [comment]
![image](https://user-images.githubusercontent.com/83530519/116807553-5e2db600-ab66-11eb-82d8-887a72533cd3.png)
没有......

**Comment by FWshaozi** [comment]
> logs文件夹是否有错误日志

它没有报错，因为任务管理器里面是存在这个任务的，但是不知道为啥它没显示......

**Comment by rmbadmin** [comment]
你能尝试一下在没有开启steam++的情况下直接用参数 
"-clt app -id 你拥有的游戏appid"
启动程序吗，看看能否正常启动

**Comment by FWshaozi** [comment]
> 你能尝试一下在没有开启steam++的情况下直接用参数
> "-clt app -id 你拥有的游戏appid"
> 启动程序吗，看看能否正常启动
emm......在哪里输这个参数啊...？

**Comment by FWshaozi** [comment]
> 你能尝试一下在没有开启steam++的情况下直接用参数
> "-clt app -id 你拥有的游戏appid"
> 启动程序吗，看看能否正常启动
emm......在哪里输这个参数啊...？

**Comment by FWshaozi** [comment]
> 你能尝试一下在没有开启steam++的情况下直接用参数
> "-clt app -id 你拥有的游戏appid"
> 启动程序吗，看看能否正常启动



emm......在哪里输这个参数啊...？

**Comment by rmbadmin** [comment]
> > 你能尝试一下在没有开启steam++的情况下直接用参数
> > "-clt app -id 你拥有的游戏appid"
> > 启动程序吗，看看能否正常启动
> > emm......在哪里输这个参数啊...？
比如直接在cmd里启动程序 然后加个空格 加入上面说的内容 就是带参数启动，这个可以稍微百度一下 有详细解释

**Comment by FWshaozi** [comment]
> > > 你能尝试一下在没有开启steam++的情况下直接用参数
> > > "-clt app -id 你拥有的游戏appid"
> > > 启动程序吗，看看能否正常启动
> > > emm......在哪里输这个参数啊...？
> 
> 比如直接在cmd里启动程序 然后加个空格 加入上面说的内容 就是带参数启动，这个可以稍微百度一下 有详细解释

没有用，我试了网上的教程也试了用cmd，都没有用

**Comment by FWshaozi** [comment]
> > > 你能尝试一下在没有开启steam++的情况下直接用参数
> > > "-clt app -id 你拥有的游戏appid"
> > > 启动程序吗，看看能否正常启动
> > > emm......在哪里输这个参数啊...？
> 
> 比如直接在cmd里启动程序 然后加个空格 加入上面说的内容 就是带参数启动，这个可以稍微百度一下 有详细解释

我试了，没有用啊......是steam的问题吗？

**Comment by rmbadmin** [comment]
> > > > 你能尝试一下在没有开启steam++的情况下直接用参数
> > > > "-clt app -id 你拥有的游戏appid"
> > > > 启动程序吗，看看能否正常启动
> > > > emm......在哪里输这个参数啊...？
> > 
> > 
> > 比如直接在cmd里启动程序 然后加个空格 加入上面说的内容 就是带参数启动，这个可以稍微百度一下 有详细解释
> 
> 我试了，没有用啊......是steam的问题吗？

应该不是，我也还没发推断出原因，暂时你也得自己找找原因，windows日志里应用程序日志 看看有没有错误日志

**Comment by FWshaozi** [comment]
> > > > > 你能尝试一下在没有开启steam++的情况下直接用参数
> > > > > "-clt app -id 你拥有的游戏appid"
> > > > > 启动程序吗，看看能否正常启动
> > > > > emm......在哪里输这个参数啊...？
> > > 
> > > 
> > > 比如直接在cmd里启动程序 然后加个空格 加入上面说的内容 就是带参数启动，这个可以稍微百度一下 有详细解释
> > 
> > 
> > 我试了，没有用啊......是steam的问题吗？
> 
> 应该不是，我也还没发推断出原因，暂时你也得自己找找原因，windows日志里应用程序日志 看看有没有错误日志

好的，我再试试看

**Comment by EasyRain** [comment]
一样的问题，点击管理成就就一个启动中就没用然后了，steam里面游戏也显示运行中

**Comment by datou1996** [comment]
刚好有一样的问题，看得到日志：
2021-05-04 11:30:26.2468|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load SteamClient
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize(Int32 appid)
期间间歇性打开了一次，然后又不行了

**Comment by FWshaozi** [comment]
> 刚好有一样的问题，看得到日志：
> 2021-05-04 11:30:26.2468|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load SteamClient
> at SAM.API.Client.Initialize(Int64 appId)
> at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize(Int32 appid)
> 期间间歇性打开了一次，然后又不行了

@rmbadmin

**Comment by rmbadmin** [comment]
问题已经找到了，今晚修复

**Comment by FWshaozi** [comment]
> 问题已经找到了，今晚修复

谢谢大佬
