### ISSUE TITLE
🐛[BUG] 进度条显示不准确

### ISSUE THREAD

**Issue by LuSuAllen** [SteamTools-Team/SteamTools#190]
### 🐛 描述(Description)

 更新时进度条显示错误，42% 显示前面多了 “0.” 导致更新快完成时，进度条才走了一点点不到

### 📷 复现步骤(Steps to Reproduce)

开始自动更新后

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

19042.928

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/38079806/116806582-f5512a00-aae2-11eb-9f4d-b27179f9bbcf.png)

**Comment by AigioL** [comment]
fix https://github.com/SteamTools-Team/SteamTools/commit/25aa1951e3564a446ae95b77b2bbd097d3690bd2

**Comment by LuSuAllen** [comment]
今天更新还是一样
![image](https://user-images.githubusercontent.com/38079806/116952881-a8836580-ac40-11eb-8c7e-2cc7931692d5.png)

**Comment by AigioL** [comment]
@LuSuAllen 从官网下载最新的版本压缩包直接解压覆盖，可能是早期版本更新 bug 没有替换关键文件。
