### ISSUE TITLE
👑[Enhancement] 443端口被占用，希望可以自定义代理端口

### ISSUE THREAD

**Issue by NULL204** [SteamTools-Team/SteamTools#191]
### 🥰 需求描述(Description)
443端口被占用，希望可以自定义代理端口
我的443端口为常用端口，与VMware Workstation Pro的虚拟网络相冲突
希望可以自定义代理端口
谢谢

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/69097698/116808294-99ca7f00-ab6a-11eb-8947-ecfcb9d9b856.png)

**Comment by rmbadmin** [comment]
如果使用hosts代理模式 那么443端口是必须的，因为更换了端口将无法监听https请求。

**Comment by NULL204** [comment]
> 如果使用hosts代理模式 那么443端口是必须的，因为更换了端口将无法监听https请求。

使用代理模式一样443报错

**Comment by rmbadmin** [comment]
> > 如果使用hosts代理模式 那么443端口是必须的，因为更换了端口将无法监听https请求。
> 
> 使用代理模式一样443报错

这个问题已知，会在下次更新修复

**Comment by NULL204** [comment]
谢谢

**Comment by NULL204** [comment]
新版本已经解决，谢谢
