### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by controller-lxl** [SteamTools-Team/SteamTools#193]
### 🐛 描述(Description)

hosts加速失败
### 📷 复现步骤(Steps to Reproduce)

1. 正常启动后hosts加速显示安全证书安装失败
2. 手动安装到受信任的根证书安装目录下仍然如此
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0.0 β rev.7
- 系统版本号(OS Version): 20H2

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/67212784/116808465-7ce27b80-ab6b-11eb-9779-2ac2c16c856b.png)
![image](https://user-images.githubusercontent.com/67212784/116808467-7f44d580-ab6b-11eb-8431-3657327be6df.png)

**Comment by rmbadmin** [comment]
2.0.0.8应该已经修复
