### ISSUE TITLE
🐛[BUG] 账号切换页面设置备注后刷新页面，备注至多保存一个

### ISSUE THREAD

**Issue by EthanMXForever** [SteamTools-Team/SteamTools#195]
### 🐛 描述(Description)

账号切换页面设置备注后刷新页面，备注至多保存一个

### 📷 复现步骤(Steps to Reproduce)

1. 设置一个账号的备注，刷新后显示正常
2. 设置第二个账号的备注，刷新后只能保存一个账号的备注
3. 更换不同账号设置备注的顺序，问题依旧存在

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.0.0 β rev.7
- 系统版本号(OS Version): Windows 10.19042.928

**Comment by rmbadmin** [comment]
2.1.0已经修复此问题
