### ISSUE TITLE
👑[Enhancement] 您好，请问mac版本放出来了吗？

### ISSUE THREAD

**Issue by LinHui88** [SteamTools-Team/SteamTools#196]
### 🥰 需求描述(Description)

您好，请问mac版本放出来了吗？在官网看到下载界面显示还是mac不可下载。

**Comment by AigioL** [comment]
现在 Linux 与 macOS 的版本有一些 UI 上的小问题，业务功能上有一些中等问题，这导致了目前版本还不能达到 测试版 的门槛，所以暂时还没有发布，目前计划等 Windows 版本开始稳定后才能在这个问题上分配人手与资源。

**Comment by LinHui88** [comment]
好的，辛苦了～

Aigio L ***@***.***>于2021年5月2日 周日22:46写道：

**Comment by simon300000** [comment]
插嘴（
如果macOS需要notarize的话，我有一个Apple开发者账号

**Comment by AigioL** [comment]
2.4.9 已发布 Beta 版本
