### ISSUE TITLE
🐛[BUG] 导入令牌的steam账号导入，若id有下划线“_”不显示且无法验证

### ISSUE THREAD

**Issue by hot-tofu-curd** [SteamTools-Team/SteamTools#197]
### 📷 复现步骤(Steps to Reproduce)

1. 点击本地令牌
2. 点击加号
3. 在Steam用户名栏输入 _

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0.0 β rev.7
- 系统版本号(OS Version): 1909

**Comment by hot-tofu-curd** [comment]
![image](https://user-images.githubusercontent.com/40805356/116816079-0eb1af00-ab93-11eb-93f1-097b1c989a11.png)

**Comment by rmbadmin** [comment]
在我这里测试好像并没有这个问题，你能在其它文本框输入_吗
![W5UJ J6Q8{3%){$3W314P U](https://user-images.githubusercontent.com/12234359/116821863-45e18980-abae-11eb-8a64-b2f061d92747.png)

**Comment by hot-tofu-curd** [comment]
> 在我这里测试好像并没有这个问题，你能在其它文本框输入_吗
> ![W5UJ J6Q8{3%){$3W314P U](https://user-images.githubusercontent.com/12234359/116821863-45e18980-abae-11eb-8a64-b2f061d92747.png)
能在其他地方打出_,steam登录框能。但是在steam++的所有文本框都不能输入_
![image](https://user-images.githubusercontent.com/40805356/116822377-154f1f00-abb1-11eb-8fdd-01eb9851a95a.png)

![image](https://user-images.githubusercontent.com/40805356/116822388-2009b400-abb1-11eb-9b85-ce6c243320a1.png)
我已尝试过重启，重装steam++都没法输入_
我的输入法是win10自带的输入法

**Comment by AigioL** [comment]
查看一下 C:\Windows\Fonts\msyh.ttc 微软雅黑字体文件版本是多少？或许和字体有关
在 Win10 20H2  中无法复现
![3`1M1%OOX%DGJ78CW13PBTT](https://user-images.githubusercontent.com/24450093/116836641-dd1ffe80-abf9-11eb-9f0f-756e3640ff62.png)

https://user-images.githubusercontent.com/24450093/116836827-9e3e7880-abfa-11eb-82a0-b20283705ff9.mp4

在 Win7 中也无法复现
![9E80 0LJDB ( UA5GUEXKQC](https://user-images.githubusercontent.com/24450093/116836863-d2b23480-abfa-11eb-9894-d36b2d95518c.png)

https://user-images.githubusercontent.com/24450093/116836927-0beaa480-abfb-11eb-85f4-ff05a3e25662.mp4

**Comment by hot-tofu-curd** [comment]
![image](https://user-images.githubusercontent.com/40805356/117163597-62700280-adf6-11eb-93a1-b1026cf7a040.png)
我好像没有微软雅黑。。。我现在系统版本是 20H2，软件版本是 2.0.0 β rev.8

**Comment by hot-tofu-curd** [comment]
![image](https://user-images.githubusercontent.com/40805356/117163991-c4c90300-adf6-11eb-8a41-261b337e3492.png)
![image](https://user-images.githubusercontent.com/40805356/117164039-d4e0e280-adf6-11eb-8cae-336c352f7928.png)

抱歉，找到了，用everything找到了
