### ISSUE TITLE
🐛[BUG] steam令牌导入失败

### ISSUE THREAD

**Issue by NULL204** [SteamTools-Team/SteamTools#199]
### 🐛 描述(Description)
steam令牌导入失败

### 📷 复现步骤(Steps to Reproduce)

1. 账号登陆
2. 提示失败

### 📄 [异常/日志]信息([Exception/Log] Information)
![image](https://user-images.githubusercontent.com/69097698/116839583-7b659180-ac05-11eb-943a-42c034d35dfa.png)
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): Beta Version:2.0.0 ß rev.7
- 系统版本号(OS Version): Microsoft Windows 10专业工作站版 版本20H2(操作系统内部版本19042.928)

**Comment by rmbadmin** [comment]
应该是没有启用社区加速或者加速有问题

**Comment by rmbadmin** [comment]
duplicate #200
