### ISSUE TITLE
🐛[BUG] steam令牌导入失败

### ISSUE THREAD

**Issue by NULL204** [SteamTools-Team/SteamTools#200]
### 🐛 描述(Description)
steam令牌导入失败

### 📷 复现步骤(Steps to Reproduce)

1. 账号导入令牌
2. 导入失败

### 📄 [异常/日志]信息([Exception/Log] Information)
![image](https://user-images.githubusercontent.com/69097698/116839963-caf88d00-ac06-11eb-880f-8ed632528611.png)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):Beta Version:2.0.0 ß rev.7
- 系统版本号(OS Version): Microsoft WindowsWindows 10专业工作站版 20H2(操作系统内部版本19042.928)

**Comment by NULL204** [comment]
我没有开任何代理

**Comment by rmbadmin** [comment]
不开代理确实无法登录，因为令牌这一块的api接口都是社区域名

**Comment by NULL204** [comment]
谢谢
