### ISSUE TITLE
🐛[BUG] 网站下载的安装包被Smart Screeen警告

### ISSUE THREAD

**Issue by zhanghua000** [SteamTools-Team/SteamTools#201]
### 🐛 描述(Description)
Windows Defender Smart Screen对下载下来的安装程序发出安全警告，提示发布者未知，需要手动选择保留。不算很影响使用，但个人还是觉得应该想办法处理一下。

### 📷 复现步骤(Steps to Reproduce)

1. 打开 https://steampp.net/download 正常下载
2. 等待下载完毕
3. Smart Screen通过Edge对下载的安装程序发出安全警告

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.0.0.7
- 系统版本号(OS Version):  Windows 10 19042.964

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/17194552/116842830-8671ef00-ac10-11eb-96db-c47d2b16ef3d.png)

**Comment by rmbadmin** [comment]
正在花钱购买数字证书来解决

**Comment by AigioL** [comment]
要过 Smart Screen 检查的证书大概要 ￥5000/年 的价格，目前正在采购 低价位的证书，应该也不能彻底解决这个弹窗警告，不过至少发布者会显示公司名。

**Comment by bysdxt** [comment]
数字证书要钱的，只要没签名的都会警告的，要不暂时下载页面里写上hash来保证文件完整性吧

**Comment by AigioL** [comment]
低价位的证书也不采购了，感觉血亏。
