### ISSUE TITLE
关于脚本的加速前提

### ISSUE THREAD

**Issue by Misaka17032** [SteamTools-Team/SteamTools#204]
在使用脚本的时候，我发现有些脚本必须加速后才能使用。
但是有时候本来就有vpn或者本来就在海外时，这个限制似乎就有点多余了。

**Comment by rmbadmin** [comment]
之后会允许单独开启脚本服务，下个版本发布时会解除选择加速的限制，交互需要以后有空时优化。

**Comment by rmbadmin** [comment]
现在已经支持仅使用脚本的功能，在加速的代理设置中启用(仅启用脚本功能)即可。
使用时仍需要启用加速，但实际不会走加速的逻辑只会执行脚本注入。
