### ISSUE TITLE
建议统一一下发版格式

### ISSUE THREAD

**Issue by chawyehsu** [SteamTools-Team/SteamTools#209]
我这边在用 [Scoop 自动追踪版本变化](https://github.com/chawyehsu/dorado/blob/master/bucket/steampp.json)，2.0 版本[打破](https://github.com/SteamTools-Team/SteamTools/releases)了之前 1.x 的发版包体格式。可否统一一下，比如用 [semver](https://semver.org/) 规范之类的。另，建议提供包体 checksums。

**Comment by rmbadmin** [comment]
现在将按照2.0.0.8开始的格式统一发布，因为要带上多平台信息了

**Comment by rmbadmin** [comment]
大致商量了一下，之后应该按照以下格式来，
如果有更好的建议可以直接回复
Steam++_win_x86_v2.1.0.7z
Steam++_win_x86_v2.1.0.exe
Steam++_linux_x64_v2.1.0.7z
Steam++_linux_x64_v2.1.0.deb
Steam++_macos_x64_v2.1.0.dmg
Steam++_macos_arm64_v2.1.0.dmg
Steam++_android_arm_v2.1.0.apk
Steam++_android_arm64_v2.1.0.apk

不使用-来分割的原因是因为+和-在一起看着比较怪异

**Comment by rmbadmin** [comment]
另外后续发布会提供 checksums
