### ISSUE TITLE
🐛[BUG] steam++闪退问题

### ISSUE THREAD

**Issue by Malygos-Light** [SteamTools-Team/SteamTools#210]
### 🐛 描述(Description)

steam++闪退问题

### 📷 复现步骤(Steps to Reproduce)

1. 启动steam++
2. 切换到库存页面
3. 下滑鼠标滚轮

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0.0 β rev.7
- 系统版本号(OS Version): windows10家庭中文版19042.867

**Comment by rmbadmin** [comment]
程序目录下logs文件夹有日志信息吗？

**Comment by Malygos-Light** [comment]
[nlog-all-2021-05-04.log](https://github.com/SteamTools-Team/SteamTools/files/6425231/nlog-all-2021-05-04.log)
[nlog-all-2021-05-05.log](https://github.com/SteamTools-Team/SteamTools/files/6425232/nlog-all-2021-05-05.log)
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6425233/internal-nlog.txt)
[nlog-all-2021-05-03.log](https://github.com/SteamTools-Team/SteamTools/files/6425234/nlog-all-2021-05-03.log)
都在这里了

**Comment by rmbadmin** [comment]
有测试过2.0.0.8版本吗？

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
