### ISSUE TITLE
🐛[BUG] 系统代理模式下社区加速 与 其他反代 冲突

### ISSUE THREAD

**Issue by bysdxt** [SteamTools-Team/SteamTools#212]
### 🐛 描述(Description)
我有自己做了反代来上github的，然后使用steampp的社区加速（系统代理模式，只勾选了steam服务）时会访问不了github
（我用steampp主要是为了史低脚本）
可以的话麻烦做下兼容，如果不行的话就算了
### 📷 复现步骤(Steps to Reproduce)

1. 启动其他反代github
2. 启动 steampp 的 社区加速（系统代理模式，不勾选github）
3. 访问github时出现空回复

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0.0 β rev.8
- 系统版本号(OS Version): Windows10 20H2(19042.928)X64
下面截图全程我自己的反代都开着的
### 🖼 截图(Screenshots)
![1](https://user-images.githubusercontent.com/13766766/117113331-e4dbd080-adbc-11eb-9efd-096e6369c92c.png)
![2](https://user-images.githubusercontent.com/13766766/117113342-e907ee00-adbc-11eb-9c39-d0bc2179799c.png)
![3](https://user-images.githubusercontent.com/13766766/117113354-eb6a4800-adbc-11eb-9a6c-a04d48f281c8.png)
![4](https://user-images.githubusercontent.com/13766766/117113356-edcca200-adbc-11eb-96f9-970ed8253e11.png)

**Comment by rmbadmin** [comment]
自己使用的反代是什么方式代理的，也是设置windows代理吗？
以及想问下为何不使用hosts代理的模式？因为与自己的反代冲突了？ 都需要443端口吗？

**Comment by bysdxt** [comment]
> 
> 
> 自己使用的反代是什么方式代理的，也是设置windows代理吗？
> 以及想问下为何不使用hosts代理的模式？因为与自己的反代冲突了？ 都需要443端口吗？

用nginx反代，127.0.0.2:443

**Comment by bysdxt** [comment]
> 
> 
> 自己使用的反代是什么方式代理的，也是设置windows代理吗？
> 以及想问下为何不使用hosts代理的模式？因为与自己的反代冲突了？ 都需要443端口吗？

是的，我自己的反代用了443，所以用不了steampp的hosts模式

**Comment by bysdxt** [comment]
> 
> 
> 自己使用的反代是什么方式代理的，也是设置windows代理吗？
> 以及想问下为何不使用hosts代理的模式？因为与自己的反代冲突了？ 都需要443端口吗？

![5](https://user-images.githubusercontent.com/13766766/117114454-78fa6780-adbe-11eb-9fbe-5f89af77b3c7.png)

**Comment by rmbadmin** [comment]
猜测应该还是访问优先走了系统代理，也就是steampp设置的代理。

改动的话目前有几个想法
一个是我这边考虑直接做上github反代的服务支持，
或者steampp内支持在将未识别的请求跳转到自定义代理上。

**Comment by bysdxt** [comment]
> 
> 
> 猜测应该还是访问优先走了系统代理，也就是steampp设置的代理。
> 
> 改动的话目前有几个想法
> 一个是我这边考虑直接做上github反代的服务支持，
> 或者steampp内支持在将未识别的请求跳转到自定义代理上。

系统代理 我不懂(＠_＠;)
麻烦你了

**Comment by AigioL** [comment]
目前已经做了 github 的反代支持，所以关闭此问题。
