### ISSUE TITLE
🐛[BUG] steam++不定时闪退

### ISSUE THREAD

**Issue by ticket-h** [SteamTools-Team/SteamTools#213]
### 🐛 描述(Description)

启动后在后台不定时闪退

### 📷 复现步骤(Steps to Reproduce)

1. 启动软件
2. 放在后台
3. 闪退

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.0.0.8
- 系统版本号(OS Version): 19042.928

log文件
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6425989/internal-nlog.txt)
[nlog-all-2021-05-05.log](https://github.com/SteamTools-Team/SteamTools/files/6425990/nlog-all-2021-05-05.log)

**Comment by ticket-h** [comment]
跟新至2.1.0.0之后问题并未改善，随附新的log文件
[nlog-all-2021-05-06.log](https://github.com/SteamTools-Team/SteamTools/files/6439937/nlog-all-2021-05-06.log)
[nlog-all-2021-05-07.log](https://github.com/SteamTools-Team/SteamTools/files/6439938/nlog-all-2021-05-07.log)
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6439939/internal-nlog.txt)
[nlog-all-2021-05-05.log](https://github.com/SteamTools-Team/SteamTools/files/6439940/nlog-all-2021-05-05.log)

**Comment by rmbadmin** [comment]
感谢反馈的日志，正在处理问题

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
