### ISSUE TITLE
🐛[BUG] 最新运行不起来，之前启动正常

### ISSUE THREAD

**Issue by dsyo2008** [SteamTools-Team/SteamTools#214]
### 🐛 描述(Description)
刚下解压并发现运行不起来，之前首发2.x打开正常，不过启动有点慢。没1.x启动快

### 📄 [异常/日志]信息([Exception/Log] Information)
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6428292/internal-nlog.txt)
[nlog-all-2021-05-05.log](https://github.com/SteamTools-Team/SteamTools/files/6428293/nlog-all-2021-05-05.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.1.0.0
- 系统版本号(OS Version): Windows 10.19043.964

**Comment by AigioL** [comment]
相比 v1.X 启动速度确实慢了很多，因为要实现跨平台，换了一个 UI 框架，目前这个 UI 框架是有这个问题，也没啥好办法。

看日志上是 OOM，这个日志的时间点，是查询打开就闪退么，然后日志直接纪录 当前时间和 System.OutOfMemoryException？
启动时直接 OOM 很不正常，除非有什么引发了死循环

最近也收到了很多类似的报告，初步调查可能是现在使用的代理库的问题，有在考虑换一个库，这个问题目前还没有解决方案

**Comment by rmbadmin** [comment]
下个版本发布的更新应该会解决此问题

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
