### ISSUE TITLE
🐛[BUG] 2.1.0.0无法启动

### ISSUE THREAD

**Issue by Naayi** [SteamTools-Team/SteamTools#215]
### 🐛 描述(Description)

程序无法启动 

### 📄 [异常/日志]信息([Exception/Log] Information)
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6430093/internal-nlog.txt)
[nlog-all-2021-05-06.log](https://github.com/SteamTools-Team/SteamTools/files/6430095/nlog-all-2021-05-06.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.1.0.0
- 系统版本号(OS Version): Windows10.0.18363.1316

**Comment by rmbadmin** [comment]
想问下是通过自动更新更新上来的吗？，尝试手动下载最新版本覆盖安装有问题吗？

**Comment by Naayi** [comment]
从1.1.4升级到2.X版本后就一直无法启动。2.1.0.0手动安装后问题依旧，在开启v2rayn全局代理，关闭火绒，程序WIN7兼容模式后小几率可以正常启动

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
