### ISSUE TITLE
🐛[BUG] 加速选择hosts模式报错

### ISSUE THREAD

**Issue by jkmiku** [SteamTools-Team/SteamTools#216]
使用管理员权限启动后点击一键加速，加速模式为hosts模式。直接报错

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.1.0 β
- 系统版本号(OS Version): WINDOWS10 20H21(9042.631)
### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/16489571/117295995-1d57d900-aea7-11eb-94a7-5b00f34a095e.png)

**Comment by AigioL** [comment]
hosts 文件属性设置的只读，并且程序无法去除只读属性 进行写入操作，就会显示这样，在下一个版本中改进了 这个错误文本的提示。

出现这个错误，需要手动去除 hosts 的只读属性，也可能是使用了一些有 hosts 防护功能的杀毒软件 锁定了 hosts 文件导致的。

**Comment by jkmiku** [comment]
> hosts 文件属性设置的只读，并且程序无法去除只读属性 进行写入操作，就会显示这样，在下一个版本中改进了 这个错误文本的提示。
> 
> 出现这个错误，需要手动去除 hosts 的只读属性，也可能是使用了一些有 hosts 防护功能的杀毒软件 锁定了 hosts 文件导致的。

謝謝，已解決
