### ISSUE TITLE
意外删除hosts文件

### ISSUE THREAD

**Issue by DrLai12club** [SteamTools-Team/SteamTools#217]
点击“一键加速”后，C:\Windows\System32\drivers\etc路径下的hosts文件会被删除，稳定复现

**Comment by DrLai12club** [comment]
经测试，选择开启steam商店加速，则会触发删除hosts

**Comment by AigioL** [comment]
程序里没有删除 hosts 的代码
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/Services/Implementation/HostsFileServiceImpl.cs

是不是开了其他加速器相关的软件删的？
可以用相关的安全工具 监控一下 hosts 文件的操作纪录

**Comment by DrLai12club** [comment]
@AigioL 用软件监测了一下，确认是steam++删除的hosts文件
![image](https://user-images.githubusercontent.com/6713511/117447917-ab4bc680-af70-11eb-98c8-9db700c0eedb.png)

![image](https://user-images.githubusercontent.com/6713511/117447811-89eada80-af70-11eb-828c-44ad95ddc77a.png)

**Comment by AigioL** [comment]
可能商店的域名被杀软有白名单保护吧，类似国内杀软的一些网银保护功能。
这种情况也没办法，后续等 数字签名证书买了，主程序签一下名或许能解决，现在也没办法，先关了问题，有解决方案可以再打开。

**Comment by bysdxt** [comment]
> 
> 
> 可能商店的域名被杀软有白名单保护吧，类似国内杀软的一些网银保护功能。
> 这种情况也没办法，后续等 数字签名证书买了，主程序签一下名或许能解决，现在也没办法，先关了问题，有解决方案可以再打开。

我自己写的反代写hosts时没这问题，我也没加白名单
