### ISSUE TITLE
👑[Enhancement] 开机自启右下角不显示托盘图标

### ISSUE THREAD

**Issue by SnowMeteors** [SteamTools-Team/SteamTools#219]
### 🥰 需求描述(Description)
win10 1709
在C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp设置开机自启，有时候右下角没有托盘图标，在任务管理器结束进程后，重启steam++，也可能没有托盘图标。

**Comment by rmbadmin** [comment]
关闭一些可能已解决的历史问题，如果问题依然存在可自行恢复。
