### ISSUE TITLE
请问为何要不断尝试访问lsass.exe？

### ISSUE THREAD

**Issue by ccboxes** [SteamTools-Team/SteamTools#220]
公司要求个人电脑也使用公司的Microsoft Defender for Endpoint杀毒，一天就跑了几百条违规。显示触发了“Block credential stealing from the Windows local security authority subsystem”这一安全策略。

请问Steam++出于什么目的去访问lsass.exe？还是说只是无脑枚举进程导致的？

附上该安全策略的文档
[https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-credential-stealing-from-the-windows-local-security-authority-subsystem](url)

@rmbadmin

**Comment by rmbadmin** [comment]
我觉得应该是枚举了所有进程导致的，程序在判断steam是否启动这个操作中，在之前确实是获取了所有进程并从进程数组中判断steam.exe，在2.1.0应该已经改进了此部分代码。

**Comment by ccboxes** [comment]
> 
> 
> 我觉得应该是枚举了所有进程导致的，程序在判断steam是否启动这个操作中，在之前确实是获取了所有进程并从进程数组中判断steam.exe，在2.1.0应该已经改进了此部分代码。

我想也是，尽量还是不要这样做，也容易被安全软件误报。
