### ISSUE TITLE
🐛[BUG] 更新进度百分比

### ISSUE THREAD

**Issue by jygxgxx** [SteamTools-Team/SteamTools#222]
### 🐛 描述(Description)

没有乘100和去小数，也不知道算不算bug

### 🖼 截图(Screenshots)

![Snipaste_2021-05-08_11-26-06](https://user-images.githubusercontent.com/24712238/117524677-edb4e800-aff0-11eb-83f7-88005106ee54.png)

**Comment by AigioL** [comment]
这个问题之前已经修复过了，不过早期版本和现有版本的 自动更新 在下载完毕后覆盖替换文件的逻辑上 有一些 bug 导致可能有一部分 程序集(dll) 没有被替换掉，目前几个版本又是二进制兼容的，所以直接运行也不会报错。

下个版本更新内容会发一个公告，下载最新版压缩包解压覆盖后应该就能彻底解决这个问题了。

**Comment by YogurtZebra** [comment]
想问一下新版本是没有手动更新的按钮吗

**Comment by rmbadmin** [comment]
> 想问一下新版本是没有手动更新的按钮吗

😂之前没有，以后发的会有

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
