### ISSUE TITLE
🐛[BUG] 打开后不定时闪退

### ISSUE THREAD

**Issue by XingChenXCxc** [SteamTools-Team/SteamTools#223]
### 🐛 描述(Description)
打开后不定时闪退
### 📷 复现步骤(Steps to Reproduce)
1. 打开
2. 最小化到托盘
3. 不定时闪退
4. 闪退后有可能伴随错误窗口

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-05-01.log](https://github.com/SteamTools-Team/SteamTools/files/6445386/nlog-all-2021-05-01.log)
[nlog-all-2021-05-05.log](https://github.com/SteamTools-Team/SteamTools/files/6445387/nlog-all-2021-05-05.log)
[nlog-all-2021-05-06.log](https://github.com/SteamTools-Team/SteamTools/files/6445388/nlog-all-2021-05-06.log)
[nlog-all-2021-05-07.log](https://github.com/SteamTools-Team/SteamTools/files/6445389/nlog-all-2021-05-07.log)
[nlog-all-2021-05-08.log](https://github.com/SteamTools-Team/SteamTools/files/6445390/nlog-all-2021-05-08.log)
[internal-nlog.txt](https://github.com/SteamTools-Team/SteamTools/files/6445391/internal-nlog.txt)
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.1.0.0
- 系统版本号(OS Version): Windows 10 19043.906

### 🖼 截图(Screenshots)
错误窗口↓
![Snipaste_2021-05-08_14-52-08](https://user-images.githubusercontent.com/63027758/117530065-b4d73c00-b00d-11eb-9095-c9dcac31cf1a.png)

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
