### ISSUE TITLE
🧐[Question] CSGO加速问题

### ISSUE THREAD

**Issue by 02200059hhh** [SteamTools-Team/SteamTools#227]
### 🧐 问题描述(Description)CSGO加速问题

以前用过1.0.5的版本一切正常，不开启加速CSGO国服也可以正常运行，更新到2.0版本后运行CSGO国服提示无法连接到任意官方服务器，只有打开加速才可以正常进入

**Comment by rmbadmin** [comment]
这应该与自身网络有关，程序的加速关了以后就不会在有任何影响，或者你可以尝试重置hosts文件 修改dns 重置lsp修复

**Comment by 02200059hhh** [comment]
> 这应该与自身网络有关，程序的加速关了以后就不会在有任何影响，或者你可以尝试重置hosts文件 修改dns 重置lsp修复

感谢，问题已解决
