### ISSUE TITLE
🧐[Question] 软件许可协议问题

### ISSUE THREAD

**Issue by 71e6fd52** [SteamTools-Team/SteamTools#228]
### 🧐 问题描述(Description)

在 https://steampp.net/ 上下载 Steam++ 时的《Steam++软件许可条款》与 [Github 上的 License](https://github.com/SteamTools-Team/SteamTools/blob/develop/LICENSE) 不一致。从软件中关于栏的“开放源代码许可”来看，有用到 GPL-3 的代码，那么就只能使用 GPL-3 发布，《Steam++软件许可条款》应该是无效的。
（不是律师，没有利益相关，只是看到了想杠）

**Comment by AigioL** [comment]
fix
