### ISSUE TITLE
🐛[BUG] 2.2.0版本社区加速列表消失，加速失效

### ISSUE THREAD

**Issue by Mr54233** [SteamTools-Team/SteamTools#229]
### 🐛 描述(Description)

就打开之后社区加速下面的加速列表消失了，加速也失效了，steam显示-118

### 📷 复现步骤(Steps to Reproduce)

1. 从2.1.0直接覆盖升上来
2. 开机自启
3. 有概率出现

### 📄 [异常/日志]信息([Exception/Log] Information)
无异常弹出
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.2.0
- 系统版本号(OS Version):   19042.928

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/46802509/117675081-d50a2500-b1de-11eb-86f9-b2e553e25284.png)
![image](https://user-images.githubusercontent.com/46802509/117675101-db000600-b1de-11eb-84a7-6638e932f6cf.png)
![image](https://user-images.githubusercontent.com/46802509/117675421-1f8ba180-b1df-11eb-83d2-4d0acd4e363b.png)

**Comment by Mr54233** [comment]
重启软件解决问题

**Comment by rmbadmin** [comment]
应该是开机时网络状况不正常导致加载加速列表出问题，右上角齿轮的刷新应该也可以解决这个问题，以后加上缓存的话就不会再有此问题。

**Comment by Mr54233** [comment]
> 应该是开机时网络状况不正常导致加载加速列表出问题，右上角齿轮的刷新应该也可以解决这个问题，以后加上缓存的话就不会再有此问题。

![image](https://user-images.githubusercontent.com/46802509/119757047-f9e8e280-bed6-11eb-80dd-931e22688e08.png)
![image](https://user-images.githubusercontent.com/46802509/119757062-fead9680-bed6-11eb-8165-c02b5339e8f0.png)
最新2.30版本依旧如此，开机加速列表消失

**Comment by AigioL** [comment]
2.4.1 中 改进了社区加速列表数据的获取，应该能解决这个问题。

**Comment by Mr54233** [comment]
> 2.4.1 中 改进了社区加速列表数据的获取，应该能解决这个问题。

确实，更新之后就没有再现了
