### ISSUE TITLE
希望能增加steam商店可以看国区无法查看的隐藏内容的功能或脚本

### ISSUE THREAD

**Issue by DarknessLeaf** [SteamTools-Team/SteamTools#230]
### 🥰 需求描述(Description)
希望能增加steam商店可以看在国区无法查看的隐藏内容的功能或脚本

### 🚑 其他信息(Other Information)
我对这方面的技术一无所知，只是表达一下希望，如果无法实现或者有其他问题就算了

**Comment by rmbadmin** [comment]
因为steam政策的更新，这个功能目前没有办法实现了
