### ISSUE TITLE
👑[Enhancement] 请求增加展柜图片域名反代

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#232]
### 🥰 需求描述(Description)
增加`https://steamuserimages-a.akamaihd.net/`域名的反代，以显示展柜图片

### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/39186981/117971262-3d324580-b35c-11eb-9e88-6b007f2c220a.png)

**Comment by rmbadmin** [comment]
其实目前是有steamuserimages-a.akamaihd.net的反代的，在steam图片这个选项开启后就会生效

**Comment by cyb233** [comment]
> 其实目前是有steamuserimages-a.akamaihd.net的反代的，在steam图片这个选项开启后就会生效

奇怪，我++的反代是全开的，但展柜的steamuserimages-a.akamaihd.net图片请求都是`ERR_CONNECTION_REFUSED`

**Comment by cyb233** [comment]
host里发现了以前用usbeam添加的相关内容，删除host清除dns缓存后折腾了会儿ok了
