### ISSUE TITLE
🐛[BUG] 界面的小问题

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#233]
### 🐛 描述(Description)
右上个人按钮总共三个选项却出现了滚动条？

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/39186981/118000285-416c5c00-b378-11eb-885a-b744f3b895f7.png)

**Comment by AigioL** [comment]
这个滚动条很迷，大概率是 UI 框架的 Bug，目前不能在我们的机子上复现，可以试试目前最新版本 2.4.1，如果使用最新版本还能复现，可以再次打开此问题。

**Comment by cyb233** [comment]
> 这个滚动条很迷，大概率是 UI 框架的 Bug，目前不能在我们的机子上复现，可以试试目前最新版本 2.4.1，如果使用最新版本还能复现，可以再次打开此问题。

2.4.1仍有此问题，那我就reopen了

**Comment by cyb233** [comment]
我好像没法reopen……

**Comment by AigioL** [comment]
> 我好像没法reopen……

已经是打开的了。

**Comment by AigioL** [comment]
目前开发分支中在这个地方 禁用了滚动，下个版本发布应该就能彻底解决。

**Comment by AigioL** [comment]
2.4.9 已发布

**Comment by cyb233** [comment]
> 2.4.9 已发布

使用反馈：滚动条确实没了，虽然依然能滚动

**Comment by AigioL** [comment]
> > 2.4.9 已发布
> 
> 使用反馈：滚动条确实没了，虽然依然能滚动

@rmbadmin

**Comment by rmbadmin** [comment]
> > 2.4.9 已发布
> 
> 使用反馈：滚动条确实没了，虽然依然能滚动

是否启用了显示缩放，显示设备的分辨率和dpi是多少？

**Comment by cyb233** [comment]
> > > 2.4.9 已发布
> > 
> > 
> > 使用反馈：滚动条确实没了，虽然依然能滚动
> 
> 是否启用了显示缩放，显示设备的分辨率和dpi是多少？

缩放125%，分辨率1920*1080

**Comment by AigioL** [comment]
2.4.10 中 UI 改动，去除了右上角区域，移到左上角，应该彻底解决这个问题了。

**Comment by cyb233** [comment]
> 2.4.10 中 UI 改动，去除了右上角区域，移到左上角，应该彻底解决这个问题了。

已确认确实将会解决此问题，包括2.4.9的错误换行等问题均已解决
