### ISSUE TITLE
🐛[BUG] 关闭后托盘不显示图标

### ISSUE THREAD

**Issue by KNBLG** [SteamTools-Team/SteamTools#235]
### 🐛 描述(Description)

最新版本直接点X后托盘不显示图标但是程序还在运行，任务管理器能看到进程

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/63439312/118173817-a26f5f00-b460-11eb-9d11-f2d312e63007.png)

**Comment by AigioL** [comment]
目前最新版本应该已修复这个问题。
