### ISSUE TITLE
👑[Enhancement] 配色调整

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#236]
### 🥰 需求描述(Description)
透明度调整后，当背景为深色时，软件中的白色就过于不搭了

### 🧐 解决方案(Solution)
背景及透明度修改为与软件整体一致或适度增加些灰色？我也不确定怎么调整比较好，难以解决的话就算了

### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/39186981/118219057-4bdb4280-b4ab-11eb-8dcc-8d8168f8093d.png)

**Comment by rmbadmin** [comment]
关闭一些可能已解决的历史问题，如果问题依然存在可自行恢复。
