### ISSUE TITLE
🐛[BUG] 软件重启后，社区加速的项目全部消失不见

### ISSUE THREAD

**Issue by mrjtleong** [SteamTools-Team/SteamTools#239]
### 🐛 描述(Description)
第一次安装完软件后，打开软件，功能都可以正常使用，完全退出软件后，再次打开，社区加速里面的项目就消失了。
截图比较好理解，看看截图！

### 📷 复现步骤(Steps to Reproduce)

1. 二次打开软件
2. 点击社区加速

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): Version 2.2.0
- 系统版本号(OS Version): Windows 10.1909

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/54793164/118387108-e0ca7100-b64e-11eb-8abd-d8cc9218dcf8.png)

**Comment by walkonbothsides** [comment]
![图片](https://user-images.githubusercontent.com/35983178/120094107-ffe9f800-c150-11eb-95ee-22e33bc4724d.png)
相同情况

**Comment by AigioL** [comment]
2.4.1 中 改进了社区加速列表数据的获取，应该能解决这个问题。
