### ISSUE TITLE
🐛[BUG] 操作 hosts错误 Unauthorizedaccess Odenied Path,C: WINDOWS\system32 drivers\etc\hosts

### ISSUE THREAD

**Issue by Flolady** [SteamTools-Team/SteamTools#241]
![bsertbre](https://user-images.githubusercontent.com/60363224/118494462-c2e73400-b754-11eb-9fac-d40473f3bd4f.png)

**Comment by AigioL** [comment]
hosts 文件属性为只读，且无法取消只读属性时，会出现这个提示，已经在最新版改了错误文本的内容。
也有可能是杀毒软件有 hosts 防护功能导致。
