### ISSUE TITLE
🧐[Question] 第一次使用过host加速测试discord连接和延迟再手动关闭加速 再切回fq软件就无法连上

### ISSUE THREAD

**Issue by Reopeko** [SteamTools-Team/SteamTools#242]
### 🧐 问题描述(Description)

如题 因为我discord是走代理端口的 没试steam++之前是正常能检测升级以及使用 然后关掉steam++的加速之后就不能连上 过不了检测升级

### 🚑 其他信息(Other Information)

![QQ截图20210518180216](https://user-images.githubusercontent.com/83240751/118633037-8fda8a00-b7c0-11eb-897a-0df0aeb1b16f.png)
![QQ截图20210518180715](https://user-images.githubusercontent.com/83240751/118633406-fb245c00-b7c0-11eb-9d8e-7889560e6437.png)
![QQ截图20210518180804](https://user-images.githubusercontent.com/83240751/118633409-fc558900-b7c0-11eb-94a7-5fde20ecc162.png)

**Comment by rmbadmin** [comment]
问题可能在于加速修改的hosts配置没有还原，
v2.4.12更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)
