### ISSUE TITLE
👑[Enhancement] C:\Users\用户名\AppData\Local里的<长沙次元超越科技有限公司>文件夹能不能改成英语。强迫症实在是受不了

### ISSUE THREAD

**Issue by Superce1l** [SteamTools-Team/SteamTools#243]
### 🥰 需求描述(Description)
如题，求大佬关爱一下强迫症患者

**Comment by AigioL** [comment]
看了一下目录，腾讯的 ```微信web开发者工具``` 也是用的中文，看起来是 [AppCenter](https://appcenter.ms) 写了这个目录。

待会找下源码看看改一下

**Comment by AigioL** [comment]
https://github.com/SteamTools-Team/appcenter-sdk-dotnet/blob/4.1.0-exclude-winforms/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DefaultApplicationSettings.cs#L137

https://docs.microsoft.com/zh-cn/dotnet/api/system.configuration.configurationmanager.openexeconfiguration?view=net-5.0#System_Configuration_ConfigurationManager_OpenExeConfiguration_System_Configuration_ConfigurationUserLevel_

```
var userConfig = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoamingAndLocal);
```

貌似没有公开的API可以改动目录

https://github.com/microsoft/appcenter-sdk-dotnet/issues/1409

源仓库上有一个相关的问题，确实这个目录创建了很多文件夹，配置就写了一个安装ID，升级也被视作重新安装。

看起来可以反射更改这个字段值，解决这个问题
https://github.com/SteamTools-Team/appcenter-sdk-dotnet/blob/4.1.0-exclude-winforms/SDK/AppCenter/Microsoft.AppCenter.Windows.Shared/AppCenter.cs#L37

**Comment by AigioL** [comment]
下一个版本开始，这个目录 ```C:\Users\用户名\AppData\Local\长沙次元超越科技有限公司``` 不会再写入内容了，之后就可以手动删除了。
