### ISSUE TITLE
🐛[BUG] 程序运行过程中闪退

### ISSUE THREAD

**Issue by 1592363624** [SteamTools-Team/SteamTools#246]
### 🐛 描述(Description)
打开后过段时间就会闪退

### 📷 复现步骤(Steps to Reproduce)

1. 打开后过段时间就会闪退
2.启动账号的时候还会关闭其他有steam标题的窗口，就很离谱

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-05-19.log](https://github.com/SteamTools-Team/SteamTools/files/6507692/nlog-all-2021-05-19.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):

**Comment by AigioL** [comment]
账号切换是需要 关闭当前的 Steam 进程，启动新的 Steam 进程的，所以已经打开的窗口是会关闭的。

**Comment by AigioL** [comment]
程序运行中闪退的问题，之前早期版本有可能因为 OOM，目前最新版本改进了可能导致闪退的问题，可以从官网上下载最新版本再试试。
