### ISSUE TITLE
🐛[BUG] 切换账号界面保存的批注莫名其妙消失了

### ISSUE THREAD

**Issue by 1592363624** [SteamTools-Team/SteamTools#247]
### 🐛 描述(Description)

切换账号界面保存的批注莫名其妙消失了
### 📷 复现步骤(Steps to Reproduce)
切换账号界面保存的批注莫名其妙消失了

1. 切换账号界面保存的批注莫名其妙消失了
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
