### ISSUE TITLE
🧐[Question] 市场增强脚本运行问题

### ISSUE THREAD

**Issue by SawSaw233** [SteamTools-Team/SteamTools#249]
### 🧐 问题描述(Description)
按照教程设置了，但是

Steam Economy Enhancer脚本运行了但是未生效

### 🚑 其他信息(Other Information)
![$M`IBLJFYXTF}GB3Q8YVP8F](https://user-images.githubusercontent.com/84638015/119235482-5c538300-bb65-11eb-8f66-c892503e41e7.jpg)
![B0MTKLM7H4)2D13D)6YY092](https://user-images.githubusercontent.com/84638015/119235488-5fe70a00-bb65-11eb-980d-bbc06271e158.png)

**Comment by Mossimos** [comment]
看看程序根目录下 \Steam\Cache\Scripts 里面打开看里面 内容是Gmjs的内容看看是否被 (function () { })包起来。 如果没有的话。能否吧缓存打包好的js内容开头截图一下。
![示例](https://user-images.githubusercontent.com/26396340/119260151-1b5e7b80-bc04-11eb-8c50-4dfc92c53661.png)

**Comment by SawSaw233** [comment]
> 看看程序根目录下 \Steam\Cache\Scripts 里面打开看里面 内容是Gmjs的内容看看是否被 (function () { })包起来。 如果没有的话。能否吧缓存打包好的js内容开头截图一下。
> ![示例](https://user-images.githubusercontent.com/26396340/119260151-1b5e7b80-bc04-11eb-8c50-4dfc92c53661.png)

![image](https://user-images.githubusercontent.com/84638015/119260598-1ef30200-bc06-11eb-9ba5-91d5246a3f3e.png)
![image](https://user-images.githubusercontent.com/84638015/119260611-287c6a00-bc06-11eb-9a24-efab099a7c30.png)

**Comment by Mossimos** [comment]
GM脚本是正常的，看起来这个脚本也正常不应该会没效果。确定没有开比如梯子什么的冲突掉了吗？

**Comment by SawSaw233** [comment]
没开梯子，连UU加速器都没用，开机后直接就运行的Steam++，然后开始加速，但是打开steam社区市场后不显示，但是另一个批量上架的脚本却能够正常生效。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SteamTools-Team/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SteamTools-Team/SteamTools] 🧐[Question] 市场增强脚本运行问题 (#249)





 
GM脚本是正常的，看起来这个脚本也正常不应该会没效果。确定没有开比如梯子什么的冲突掉了吗？

**Comment by Mossimos** [comment]
那你尝试下点击脚本的刷新按钮再试试不行就删除重下试试。可能是SEE脚本 内部依赖是从Github下载的打包的时候连接不上Github出现问题。（下个版本直接下服务器打包好的算了不在客户端执行打包操作[手动添加除外]）

**Comment by SawSaw233** [comment]
已经解决了，我通过使用群内的卸载软件完全卸载Steam++后，再重新安装。并按照流程下载安装运行脚本，成功了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SteamTools-Team/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月26日(星期三) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SteamTools-Team/SteamTools] 🧐[Question] 市场增强脚本运行问题 (#249)





 
那你尝试下点击脚本的刷新按钮再试试不行就删除重下试试。可能是SEE脚本 内部依赖是从Github下载的打包的时候连接不上Github出现问题。（下个版本直接下服务器打包好的算了不在客户端执行打包操作[手动添加除外]）
