### ISSUE TITLE
👑[Enhancement] 当前版本内存占用过大

### ISSUE THREAD

**Issue by DVonderhaar** [SteamTools-Team/SteamTools#250]
### 🥰 需求描述(Description)
当前版本的steam++内存占用过大，连chrome和新版edge都没占用这么大（
### 🧐 解决方案(Solution)
nope
### 🚑 其他信息(Other Information)
![捕获](https://user-images.githubusercontent.com/30433000/119264756-f6bfcf00-bc16-11eb-9e96-f1936d2ee683.PNG)

**Comment by rmbadmin** [comment]
主要是在库存游戏拥有过多游戏时会加载太多的图片导致的，如果在启动后不曾点开过库存游戏tab的话应该就不会有这么大占用。

**Comment by AigioL** [comment]
内存占用 大多都是 非托管内存占的，与 CEF 的占用，目前没有好的解决方案。
等 .NET 6 AOT/R2R/Crossgen2 可用时，应该才能解决这些问题，包括目前程序冷启动非常慢的问题。

**Comment by rmbadmin** [comment]
目前已经初步解决，目前程序启动后的正常占用应该是150MB左右。
点开库存游戏时会根据游戏库存的数量多增加一定的内存占用，这是正常情况。
