### ISSUE TITLE
🐛[BUG] pixiv加速功能无法关注和标红心

### ISSUE THREAD

**Issue by xitieshiz2** [SteamTools-Team/SteamTools#251]
### 🐛 描述(Description)

pixiv加速功能开启后可以正常访问pixiv主站，但不能加红心和加关注，应该是红心和关注使用的服务器不是pixiv.net
### 📷 复现步骤(Steps to Reproduce)

1. 开启pixiv加速功能
2. 试图加关注或红心
3. 失败

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.2.0
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/75575551/119266594-fa0a8900-bc1d-11eb-91a3-8dfb11182449.png)

**Comment by Janet-Baker** [comment]
反代没处理完全，漏了几个域名……
我这干脆就上不去pixiv

**Comment by AigioL** [comment]
> 反代没处理完全，漏了几个域名……
> 我这干脆就上不去pixiv

关注与标红心，在 @rmbadmin  的机子上是正常工作的。
遗漏了几个域名的话，是哪些？可以在 #318 中回复

目前社区加速遗漏的域名现统一在 #318 中管理，所以这边先关闭了。

**Comment by Time-bug** [comment]
是因为账号被停用吗？我现在也是同样的问题，我的账号被停用以后解封，然后就点不了红心和关注了
