### ISSUE TITLE
🧐[Question] 我需要重装电脑，备份哪些文件可以节省搞回3个账号的切换，和令牌的功夫？

### ISSUE THREAD

**Issue by conmor** [SteamTools-Team/SteamTools#253]
### 🧐 问题描述(Description)
我需要重装电脑，备份哪些文件可以节省搞回3个账号的切换，和令牌的功夫？

或者未来新版本能不能增加个备份数据的功能也行

**Comment by rmbadmin** [comment]
账号切换的数据都是来自steam，只要steam没有删除重装就不会有问题，如果删了只要steam在重新登录一遍这些账号就行。
令牌数据的话导出将会在今天发布的2.3.0版本中上线，在此之前最好不要重装，因为之前的令牌数据都启用了仅本机保护，重装系统后数据将会无法解密，可以更新了今晚的新版本后导出备份一遍令牌数据在重装。
