### ISSUE TITLE
开机无网络托盘图标消失🐛[BUG] 

### ISSUE THREAD

**Issue by EasyRain** [SteamTools-Team/SteamTools#254]
我电脑连的是校园网，开机需要一段时间认证身份才能上网，因为开机运行的缘故程序右下角托盘程序会不出现，任务管理器里是能找到程序是正在运行的，而且因为开机后有段时间无网络打开程序加速主界面是空白的必须刷新一下才能重新出现，在任务管理器里面强制杀掉程序重新启动托盘图标能显示。

**Comment by AigioL** [comment]
之前早期版本可能因这种情况受到影响的应该只有 社区加速功能，前几个版本中改进了这方面，可能也能适应这种情况。

如果还是不行的话，可以尝试将 计划任务中，加入延时
操作方法如下所示：
1. Win + R 打开运行 输入 taskschd.msc 回车
2. 在 左侧菜单选择任务计划程序库，中间的列表中可以找到名称为 Steam++ 的项 双击该项
3. 在 左上角的 Tab 中选择 触发器，编辑登录时触发器
4. 在 高级设置 中勾上延时任务时间(K): 可以设置为 30 秒或一分钟
