### ISSUE TITLE
steam++希望能与代理共存👑[Enhancement] 

### ISSUE THREAD

**Issue by EasyRain** [SteamTools-Team/SteamTools#255]
steam++正常运行的时候启用加速或者不启用都一个问题，我启动clash或者ssr程序有概率会自己退掉，希望steam++能与代理共存

**Comment by Au3C2** [comment]
同求

**Comment by rmbadmin** [comment]
v2.4.12更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)

> 同求
