### ISSUE TITLE
🐛[BUG] 加速时长出现错误

### ISSUE THREAD

**Issue by TeaLion** [SteamTools-Team/SteamTools#256]
### 🐛 描述(Description)

Steam++ 2.2.0加速时长出现错误

### 📷 复现步骤(Steps to Reproduce)

1. 正常启动加速
2. 加速过程中可见时间跳秒出现异常

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.2.0
- 系统版本号(OS Version): Windows 10-19042.985-20H2

### 🖼 截图(Screenshots)

[https://imgtu.com/i/gz6hes](https://imgtu.com/i/gz6hes)

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
