### ISSUE TITLE
👑[Enhancement] 先整个简陋的安卓出来吧

### ISSUE THREAD

**Issue by Passerby1011** [SteamTools-Team/SteamTools#258]
绝大部分手机没法root导致steam令牌只能在一个客户端使用，非常的蛋疼

安卓端暂时可以不需要任何其他功能，能和电脑一起用令牌就行

**Comment by rmbadmin** [comment]
已经尽快准备了，预计6月份应该可以发布

**Comment by HAHH9527** [comment]
> 已经尽快准备了，预计6月份应该可以发布

是已经在开发了嘛，我是个Android程序员，如需帮助可尽绵薄之力

**Comment by rmbadmin** [comment]
> > 已经尽快准备了，预计6月份应该可以发布
> 
> 是已经在开发了嘛，我是个Android程序员，如需帮助可尽绵薄之力

谢谢，android计划用C# + Xamarin.Forms实现，因为这样可以直接共用现在桌面端的部分代码。
如果在这方面依然可以提供帮助的话，欢迎直接提 Pull requests 。
总之十分感谢心意。

**Comment by AigioL** [comment]
2.4.9 已发布 Alpha 版本
