### ISSUE TITLE
不想修改hosts文件，希望添加自定义选项👑[Enhancement] 

### ISSUE THREAD

**Issue by IXIPXIXI** [SteamTools-Team/SteamTools#259]

**Comment by rmbadmin** [comment]
具体是指什么自定义？

**Comment by IXIPXIXI** [comment]
如果不需要相应的加速功能
可以在软件选择不修改hosts文件
或者说可不可以添加选项一键恢复原配置
小白真的不懂怎么改回来

**Comment by rmbadmin** [comment]
> 如果不需要相应的加速功能
> 可以在软件选择不修改hosts文件
> 或者说可不可以添加选项一键恢复原配置
> 小白真的不懂怎么改回来

如果不需要加速功能，不启用加速就不会改hosts。
关于hosts还原，关闭加速就会自动还原。
hosts也只会更改选择的加速项目，你勾选了哪些加速项目就只会改对应项目的hosts，
如果一个都不需要就全部取消勾选就行了。

**Comment by IXIPXIXI** [comment]
每次退出应用时，火绒会提示修改hosts
这一步选择永久禁用会不会有什么影响
谢谢

**Comment by HAHH9527** [comment]
> 每次退出应用时，火绒会提示修改hosts
> 这一步选择永久禁用会不会有什么影响
> 谢谢

退出应用时，会还原steam++修改的hosts（删除增加的hosts）
如果永久禁用，可能导致的问题是hosts无法正常还原，单独启动steam并未启动steam++及加速功能时，可能导致加速项目变成无法访问

**Comment by AigioL** [comment]
相比 V1 版本，https://github.com/SteamTools-Team/SteamTools/blob/develop/source/SteamTool.Core/HostsService.cs#L216
hosts 清除写入内容的逻辑发生了一些变化，导致目前即使没有写入数据时，也将重新写入一次 hosts 文件。
在 程序退出时 尝试执行了一次清理操作，所以这引发了一些安全软件上的提示。

现在实现了一个简单的解决方案，在写入hosts之后插入一个flag，当flag有值时候，在相关的清理操作中才去操作 hosts，否则不操作。

最佳的实现方案还是更改 
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/Services/Implementation/HostsFileServiceImpl.cs#L589
先读文件，没有要清理时不执行写入，但是改起来头大，先用简单的方案解决。

**Comment by AigioL** [comment]
相比 V1 版本，https://github.com/SteamTools-Team/SteamTools/blob/develop/source/SteamTool.Core/HostsService.cs#L216
hosts 清除写入内容的逻辑发生了一些变化，导致目前即使没有写入数据时，也将重新写入一次 hosts 文件。
在 程序退出时 尝试执行了一次清理操作，所以这引发了一些安全软件上的提示。

现在实现了一个简单的解决方案，在写入hosts之后插入一个flag，当flag有值时候，在相关的清理操作中才去操作 hosts，否则不操作。

最佳的实现方案还是更改 
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/Services/Implementation/HostsFileServiceImpl.cs#L589
先读文件，没有要清理时不执行写入，但是改起来头大，先用简单的方案解决。

**Comment by AigioL** [comment]
已发布 2.4.1 修复
