### ISSUE TITLE
🐛[BUG] 未登录steam时 点击库存游戏会闪退

### ISSUE THREAD

**Issue by HAHH9527** [SteamTools-Team/SteamTools#260]
### 🐛 描述(Description)

未登录steam时 点击库存游戏会闪退

### 📷 复现步骤(Steps to Reproduce)

1.新安装steam++
2.打开steam++
3.在未登录steam时，点击steam++中的游戏库存

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.3.0
- 系统版本号(OS Version): WIN10专业版 20H2 19042.928

### 🖼 截图(Screenshots)

无

**Comment by rmbadmin** [comment]
程序目录下logs文件夹有日志吗？
猜测原因有可能是加载的游戏过多导致内存溢出。因为在未启用steam的情况下将加载steam缓存的所有游戏数据。

**Comment by HAHH9527** [comment]
> 程序目录下logs文件夹有日志吗？
> 猜测原因有可能是加载的游戏过多导致内存溢出。因为在未启用steam的情况下将加载steam缓存的所有游戏数据。

logs被覆盖了，请问数据文件在哪呢，刚刚卸载重装并没法复现

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
