### ISSUE TITLE
🐛[BUG] 点击一键加速后立马卡死无响应

### ISSUE THREAD

**Issue by BJY666** [SteamTools-Team/SteamTools#261]
### 🐛 描述(Description)

2.3.0的免安装和安装包都试过一次，打开软件后点击一键加速（不管加速的是什么选项），程序会第一时间就卡死，无响应。

### 📷 复现步骤(Steps to Reproduce)

1. 双击steam++.exe
2. 点击一键加速
3. 卡死

### 📄 [异常/日志]信息([Exception/Log] Information)
2021-05-27 13:26:37.2277|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to load SteamClient
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.3.0
- 系统版本号(OS Version): 
Windows 10 专业教育版 20H2
### 🖼 截图(Screenshots)

![QQ图片20210527133758](https://user-images.githubusercontent.com/51154133/119771773-cb780100-bef0-11eb-84d3-9cd83fceb1fd.png)

**Comment by BJY666** [comment]
实测2.2.0可以正常使用，2.3.0加速就卡死

**Comment by fugenb** [comment]
我也是这个问题

**Comment by rmbadmin** [comment]
@fugenb @BJY666  麻烦在测试一下如果启用windows代理模式也会未响应吗？以及能否提供一下windows日志里的应用程序日志，

steam++在windows日志中会被记录.NET Runtime和 Applocation Error错误的异常

**Comment by BJY666** [comment]
> @fugenb @BJY666 麻烦在测试一下如果启用windows代理模式也会未响应吗？以及能否提供一下windows日志里的应用程序日志，
> 
> steam++在windows日志中会被记录.NET Runtime和 Applocation Error错误的异常

**Comment by BJY666** [comment]
> @fugenb @BJY666 麻烦在测试一下如果启用windows代理模式也会未响应吗？以及能否提供一下windows日志里的应用程序日志，
> 
> steam++在windows日志中会被记录.NET Runtime和 Applocation Error错误的异常

系统代理的话不会卡死，但是几乎无法使用（打不开社区），另外日志如下：
日志名称:          Application
来源:            Application Hang
日期:            2021/6/1 19:47:42
事件 ID:         1002
任务类别:          (101)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-95U86EM
描述:
程序 Steam++.exe 版本 2.3.0.0 已停止与 Windows 交互并关闭。若要查看是否有关于该问题的详细信息，请检查“安全性与维护”控制面板中的问题历史记录。
 进程 ID: 31bc
 开始时间: 01d756dbb8044de4
 终止时间: 8
 应用程序路径: K:\game\Steam  2.3.0免安装版\Steam++.exe
 报告 ID: 3313df3d-7d64-4c33-81fb-52dd0dfb28f2
 错误程序包全名: 
 错误程序包相关应用程序 ID: 
 挂起类型: Unknown

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>101</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-06-01T11:47:42.8627244Z" />
    <EventRecordID>13719</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-95U86EM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Steam++.exe</Data>
    <Data>2.3.0.0</Data>
    <Data>31bc</Data>
    <Data>01d756dbb8044de4</Data>
    <Data>8</Data>
    <Data>K:\game\Steam  2.3.0免安装版\Steam++.exe</Data>
    <Data>3313df3d-7d64-4c33-81fb-52dd0dfb28f2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>Unknown</Data>
    <Binary>55006E006B006E006F0077006E0000000000</Binary>
  </EventData>
</Event>

**Comment by BJY666** [comment]
> @fugenb @BJY666 麻烦在测试一下如果启用windows代理模式也会未响应吗？以及能否提供一下windows日志里的应用程序日志，
> 
> steam++在windows日志中会被记录.NET Runtime和 Applocation Error错误的异常

抱歉，重新上传一份txt格式的
[日志.txt](https://github.com/SteamTools-Team/SteamTools/files/6576011/default.txt)

**Comment by fugenb** [comment]
@rmbadmin 日志文件：
[新建文本文档.txt](https://github.com/SteamTools-Team/SteamTools/files/6582591/default.txt)

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
