### ISSUE TITLE
🐛[BUG] 生成了大量的日志

### ISSUE THREAD

**Issue by guoraymon** [SteamTools-Team/SteamTools#263]
### 🐛 描述(Description)

分析C盘空间发现的，存在大量空间占用的日志（约13G）

### 📷 复现步骤(Steps to Reproduce)
无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.1.0 β
- 系统版本号(OS Version):  Windows 10.19042.985

### 🖼 截图(Screenshots)
![~TR27{6C$_4S~NGJV}YOKX8](https://user-images.githubusercontent.com/13381989/120059071-9fd85080-c081-11eb-8155-f030fe5eb51f.png)

![VV952ML K(Y0@GW4)9Q_O9E](https://user-images.githubusercontent.com/13381989/120058994-31938e00-c081-11eb-92e7-4fed2e2979e7.png)

**Comment by rmbadmin** [comment]
这个确实是早期版本的问题，在当前版本之后已经不会在有这个情况了，同时之后也会把清除日志缓存的功能给做上的。目前是因为开发时间关系暂时还没做。
