### ISSUE TITLE
🐛[BUG] Win7开机自启动后，社区加速项目空白并且无效

### ISSUE THREAD

**Issue by abbw** [SteamTools-Team/SteamTools#264]
### 🐛 描述(Description)

Win7下开机自启动后，社区加速页面内容空白，虽然显示已加速成功，但没任何效果。必须退出重开软件才能生效

### 📷 复现步骤(Steps to Reproduce)

1. Win7设置开机自启动
2. 设置程序启动自动加速

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.3.0
- 系统版本号(OS Version): Windows7

### 🖼 截图(Screenshots)

![捕获](https://user-images.githubusercontent.com/15247793/120069222-5571c680-c0b7-11eb-9b3a-118451979c3b.PNG)

**Comment by zhanghua000** [comment]
Win10也有一样的问题，不过我没有设置开机自启，手动启动结果也是这样，加速服务列表为空。并且退出重开在Win10上没有效果。

**Comment by rmbadmin** [comment]
> Win10也有一样的问题，不过我没有设置开机自启，手动启动结果也是这样，加速服务列表为空。并且退出重开在Win10上没有效果。而且启动加速后虽然提示加速成功，但经测试发现未成功加速，steamcommunity无法访问。

该问题与win7 win10无关 问题是因为无法连接上我们的api.steampp.net服务器 无法获取到加速的项目

**Comment by zhanghua000** [comment]
> > Win10 也有一样的问题，不过我没有设置开机自启，手动启动结果也是这样，加速服务列表为空。并且退出重开在 Win10 上没有效果。而且启动加速后虽然提示加速成功，但经测试发现未成功加速，steamcommunity 无法访问。
> 
> 该问题与 win7 win10 无关 问题是因为无法连接上我们的 api.steampp.net 服务器 无法获取到加速的项目

啊我试了一下，浏览器可以打开 api.steampp.net 的网页，但ping请求超时。请问这是服务器的问题还是我这里的问题呢

**Comment by rmbadmin** [comment]
> > > Win10 也有一样的问题，不过我没有设置开机自启，手动启动结果也是这样，加速服务列表为空。并且退出重开在 Win10 上没有效果。而且启动加速后虽然提示加速成功，但经测试发现未成功加速，steamcommunity 无法访问。
> > 
> > 
> > 该问题与 win7 win10 无关 问题是因为无法连接上我们的 api.steampp.net 服务器 无法获取到加速的项目
> 
> 啊我试了一下，浏览器可以打开 api.steampp.net 的网页，但ping请求超时。请问这是服务器的问题还是我这里的问题呢

服务器是不允许ping的，所以ping不通，问题是在于程序内的web请求失败了，具体原因因为我们自己无法复现此问题所以也还在找，你可以看看程序目录下logs文件夹是否有相关日志 可以反馈上来。

**Comment by zhanghua000** [comment]
> > > > Win10 也有一样的问题，不过我没有设置开机自启，手动启动结果也是这样，加速服务列表为空。并且退出重开在 Win10 上没有效果。而且启动加速后虽然提示加速成功，但经测试发现未成功加速，steamcommunity 无法访问。
> > > 
> > > 
> > > 该问题与 win7 win10 无关 问题是因为无法连接上我们的 api.steampp.net 服务器 无法获取到加速的项目
> > 
> > 
> > 啊我试了一下，浏览器可以打开 api.steampp.net 的网页，但 ping 请求超时。请问这是服务器的问题还是我这里的问题呢
> 
> 服务器是不允许 ping 的，所以 ping 不通，问题是在于程序内的 web 请求失败了，具体原因因为我们自己无法复现此问题所以也还在找，你可以看看程序目录下 logs 文件夹是否有相关日志 可以反馈上来。

```
2021-06-02 19:34:45.5971|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```
整个日志文件只有这一行

**Comment by abbw** [comment]
我上传了刚触发的日志，麻烦看下
[nlog-all-2021-06-05.log](https://github.com/SteamTools-Team/SteamTools/files/6602152/nlog-all-2021-06-05.log)

**Comment by AigioL** [comment]
> 我上传了刚触发的日志，麻烦看下
> [nlog-all-2021-06-05.log](https://github.com/SteamTools-Team/SteamTools/files/6602152/nlog-all-2021-06-05.log)

 ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。
根据日志推断是 DNS 没能解析出 api.steampp.net:443 的 IP 地址

社区加速项目空白的问题，之前早期版本报告了很多例，能用浏览器访问 steampp.net 或 api.steampp.net 但是程序内不能正常访问，原因目前也没能查出来，最近几个版本中加入了出错时继续重试，可能能缓解这个问题。

也许在 Windows 上还是使用 [WinHttpHttpHandler](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.http.winhttphandler?view=dotnet-plat-ext-5.0) 比 [SocketsHttpHandler](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.http.socketshttphandler?view=net-5.0) 更稳定些。

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
