### ISSUE TITLE
🐛[BUG] 手动检查更新时弹出两个更新窗口

### ISSUE THREAD

**Issue by YogurtZebra** [SteamTools-Team/SteamTools#265]
### 🐛 描述(Description)

每点一下出两个

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.3.0
- 系统版本号(OS Version):

**Comment by AigioL** [comment]
已发布 2.4.1 修复
