### ISSUE TITLE
🐛[BUG] 通过Xbox登录的Steam++账户注销后在手机账户绑定显示占用，再用Xbox登录显示账户已被封禁

### ISSUE THREAD

**Issue by xitieshiz2** [SteamTools-Team/SteamTools#267]
### 🐛 描述(Description)

在“关于-此软件-注销账户”中注销使用Xbox登录的账户后再尝试用手机账户绑定显示账户已被占用，再尝试用Xbox登录Steam++显示账户已被封禁
### 📷 复现步骤(Steps to Reproduce)

1. 使用Xbox登录Steam++
2. 注销账户
3. 使用手机登录Steam++
4. 绑定之前的Xbox账户
5. 显示被占用
6. 尝试用Xbox登录Steam++
7. 显示“账户已被封禁”

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.3.0
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/75575551/120104476-304c8900-c187-11eb-808b-7d645bd14e59.png)
![image](https://user-images.githubusercontent.com/75575551/120104524-6ab62600-c187-11eb-80a3-0b30bd156414.png)

**Comment by AigioL** [comment]
@xitieshiz2  已修复
