### ISSUE TITLE
🐛[BUG] 即使开启了Steam社区加速，也不能使用steam快速登录

### ISSUE THREAD

**Issue by xitieshiz2** [SteamTools-Team/SteamTools#268]
### 🐛 描述(Description)

即使开启了Steam社区加速，并且在浏览器和Steam客户端中能正常使用社区，但使用steam快速登录也会提示“无法连接至Steam社区
### 📷 复现步骤(Steps to Reproduce)

1. 开启Steam社区加速
2. 进行Steam快速登录
3. 登录失败

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.3.0
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/75575551/120104865-33e10f80-c189-11eb-95f7-92fbdbfc5c6c.png)
![image](https://user-images.githubusercontent.com/75575551/120104869-3b081d80-c189-11eb-931f-5f8ce4f0e386.png)

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
