### ISSUE TITLE
证书问题  希望改成可以用自己的证书

### ISSUE THREAD

**Issue by gdf159159** [SteamTools-Team/SteamTools#27]
证书问题  希望改成可以用自己的证书

用fiddler发现的 window的证书在手机上 有兼容问题 

或者把证书目的改成所有

**Comment by rmbadmin** [comment]
生成的pfx证书是可以自己用openssl或者windows的证书导出功能自己转一份cer的证书的，然后给手机导入cer证书试试

**Comment by gdf159159** [comment]
> 生成的pfx证书是可以自己用openssl或者windows的证书导出功能自己转一份cer的证书的，然后给手机导入cer证书试试，
> 用自己的证书的话，功能可以实现，不过要之后有空在弄

证书目的现在有限制是服务验证的 手机上用不了 还是会提示 证书错误 

所有目的的证书 才能在手机上用

![QQ截图20201229195927](https://user-images.githubusercontent.com/8487256/103282363-81a5f000-4a10-11eb-94c0-f6a06cd269ce.png)
![QQ截图20201229195933](https://user-images.githubusercontent.com/8487256/103282367-836fb380-4a10-11eb-9313-553004f2fcef.png)

**Comment by rmbadmin** [comment]
1.0.5版本给生成的证书多添加了一个客户端验证的目的，你可以试一下能否解决此问题
需要把1.0.4的证书手动删除程序目录下的文件
之后重新用1.0.5的程序生成证书

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
