### ISSUE TITLE
启用加速不会自动解除对浏览器代理的占用🐛[BUG] 

### ISSUE THREAD

**Issue by ErPurE** [SteamTools-Team/SteamTools#274]
### 🐛 描述(Description)
启用加速之后似乎会占用浏览器的代理端口，并且不会自动解除占用，导致其他代理无法连接

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):

**Comment by rmbadmin** [comment]
启用的什么加速模式？ 
 浏览器代理端口是指哪个端口？  hosts代理模式占用的是443与其它系统代理不会冲突。
 系统代理模式占用的是随机未被占用端口

**Comment by ErPurE** [comment]
启用的是host代理。我通过排除法发现不是steam++占用的端口，不好意思.

**Comment by rmbadmin** [comment]
好的，没有问题的话就关闭此问题了。如果有问题可以随时恢复。
