### ISSUE TITLE
🐛[BUG] steam社区加速后不显示图片

### ISSUE THREAD

**Issue by DVonderhaar** [SteamTools-Team/SteamTools#275]
### 🐛 描述(Description)
用steam++加速steam社区后，社区内大量图片例如头像、成就图标、商品缩略图无法显示
### 📷 复现步骤(Steps to Reproduce)
1.steam++加速steam社区
2.用steam客户端打开社区动态或个人资料等
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version): Windows 10 21H2 19043.1052

### 🖼 截图(Screenshots)
![捕获](https://user-images.githubusercontent.com/30433000/121699017-24ef4b00-cb01-11eb-8569-bd41b863a192.PNG)
![捕获1](https://user-images.githubusercontent.com/30433000/121699360-70a1f480-cb01-11eb-9b87-0749ff2d1559.PNG)

**Comment by rmbadmin** [comment]
是否有加速steam图片这个选项？

**Comment by DVonderhaar** [comment]
有，我还试着用羽翼城大佬的usbeam hosts editor添加了相关hosts，但加了hosts以及删了hosts都没有用，图片依旧刷不出来

**Comment by cyb233** [comment]
我以前用usbeam改过的hosts影响过后来Steam++的反代，清除完hosts后使用命令提示簿清理DNS缓存再看看？参考issue： #232 
清理DNS指令： ipconfig /flushdns

**Comment by DVonderhaar** [comment]
> 我以前用usbeam改过的hosts影响过后来Steam++的反代，清除完hosts后使用命令提示簿清理DNS缓存再看看？参考issue： #232
> 清理DNS指令： ipconfig /flushdns

我清理DNS缓存了，但还是不行，成就图标依旧是截图里那样

**Comment by DVonderhaar** [comment]
我重装了系统后就正常了，看来是win10的bug
