### ISSUE TITLE
🐛[BUG] 2.4.1版本开机无法自启

### ISSUE THREAD

**Issue by DVonderhaar** [SteamTools-Team/SteamTools#276]
### 🐛 描述(Description)
已在设置打开了开机自启动的开关，但是每次开机都没有自启
### 📷 复现步骤(Steps to Reproduce)
1.在设置中打开开机自启动
2.重启
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version): Windows 10 21H1 19043.1052

### 🖼 截图(Screenshots)
![捕获](https://user-images.githubusercontent.com/30433000/121700397-72b88300-cb02-11eb-8781-2eedbc9f2838.PNG)

**Comment by AigioL** [comment]
https://github.com/SteamTools-Team/SteamTools/commit/c3fbeb3c4abfe091993a20d62f5076baad2b216e#r51870163

因为 2.4.0 ~ 2.4.1 更改目录结构 加入 Bin 文件夹 导致开机启动项写入位置不正确

目前开发分支上改了一些内容还没测试，暂时还不能发新版修复这个问题

可以先手动在 ```计算机管理(本地) - 系统工具 - 任务计划程序 - 任务计划程序库``` 中 找到名称为 ``Steam++`` 的项 双击打开 顶部 Tab 切换到 操作，编辑列表中唯一的操作项 在 ```起始于(可选)(T):``` 将目录末尾的 ```\Bin``` 删除即可
