### ISSUE TITLE
🐛[BUG] 程序运行过程中闪退(v2.3.0)

### ISSUE THREAD

**Issue by Kulahala** [SteamTools-Team/SteamTools#277]
steam++无故闪退，双击任务栏的steam++也会出现闪退
版本：Current Version: 2.3.0

**Comment by rmbadmin** [comment]
试试2.4.1版本吧，闪退问题在此版本应该得到解决。

**Comment by AigioL** [comment]
目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
