### ISSUE TITLE
👑[Enhancement] 希望支持本地代理工具，开发方向保持游戏工具的单纯性

### ISSUE THREAD

**Issue by lilyblessing** [SteamTools-Team/SteamTools#278]
### 🥰 需求描述(Description)
希望能直接使用本地代理而非兼容去做其他网站的反代加速，保持游戏工具箱的单纯性，这是游戏工具而非翻墙工具。

**Comment by Lutra-Fs** [comment]
可以把反向代理模块化? 然后作为可选项

**Comment by AigioL** [comment]
工具箱中大部分功能其实都依赖**社区加速**功能，因为需要本地能访问 Steam社区 的API接口，像脚本功能是需要通过本地反代来实现脚本注入的。

之后功能多了是需要模块化的，要实现模块化改动还挺大的，而且也有一些弊端。

**Comment by rmbadmin** [comment]
v2.4.12更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)
