### ISSUE TITLE
👑[Enhancement] 库存游戏右键菜单改进 & 成就管理风险不再提示

### ISSUE THREAD

**Issue by WinMEMZqwq** [SteamTools-Team/SteamTools#279]
### 🥰 需求描述(Description)

steam++开发组 你们好
作为一个从第一代版本发布以来就开始使用工具箱的老用户
请允许我向尊敬的开发组提些建议 希望能采纳呀~
接下来是建议产生的原因
首先 在工具箱的库存游戏页面 个人觉得打开菜单需要用右键其实不是很好
当然其实这是我自己的原因 之前体育课摔了一跤 按右键的中指软组织炸了 使不上力 按不了右键 很难受;w;
另外 对于我这种无能成就作弊的咸鱼 为了在好友面前炫耀自己 肯定不少会用到右键菜单的管理成就功能
不过这个风险提示弹窗还是挺影响体验的 : (

### 🧐 解决方案(Solution)

关于右键菜单的解决方案 我的建议是 使用左键弹出抽屉式菜单来替代右键
另外成就管理的这个风险提示 我建议是在确定按钮的左边加上一个"不再提示"的选项 来方便我们这种臭咸鱼XD

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/85821597/121799761-6c401d80-cc60-11eb-80d1-e8c813ab1940.png)
大概感觉的效果是这样的 谢谢你们( •̀ ω •́ )✧

**Comment by AigioL** [comment]
@rmbadmin 吧不再显示的 CheckBox 做了吧

**Comment by rmbadmin** [comment]
其实左键原本是有其它的互动但是还没做完所以暂时屏蔽了左键功能。

下次不在提示这个窗口也是在计划内不过因为没有时间所以暂时没做。

之后会加上的，感谢反馈。

**Comment by cyb233** [comment]
> 其实左键原本是有其它的互动但是还没做完所以暂时屏蔽了左键功能。
> 
> 下次不在提示这个窗口也是在计划内不过因为没有时间所以暂时没做。
> 
> 之后会加上的，感谢反馈。

让我猜猜，左键涉及了计划中的ASF？

**Comment by AigioL** [comment]
2.4.9 已发布
