### ISSUE TITLE
🐛[BUG] 每次开启程序一段时间后就会卡死无响应

### ISSUE THREAD

**Issue by aqukin** [SteamTools-Team/SteamTools#280]
### 🐛 描述(Description)
每次开启程序一段时间后就会卡死无响应

### 📷 复现步骤(Steps to Reproduce)

1. 打开程序
2. 开启加速
3. 启动steam
4.等待一段时间后就无响应了
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):1809
- 系统版本号(OS Version): windows10.17763.1217

**Comment by rmbadmin** [comment]
程序版本？

**Comment by aqukin** [comment]
> 程序版本？

2.3.0

**Comment by rmbadmin** [comment]
更新到2.4.1，已经修复此问题

**Comment by aqukin** [comment]
> 更新到2.4.1，已经修复此问题

程序里面的检查更新都说我是最新版本hh

**Comment by rmbadmin** [comment]
> > 更新到2.4.1，已经修复此问题
> 
> 程序里面的检查更新都说我是最新版本hh

因为升级64位版本的问题，之前做了一个32位无法检测64位更新的逻辑

**Comment by AigioL** [comment]
因为 2.4 之前的版本 更新逻辑在客户端方有一些 bug，导致无法更新到 2.4 之后的版本。

目前最新版本 2.4.1 应该已修复这个问题，如果使用最新版本还能复现，可以再次打开此问题。
