### ISSUE TITLE
👑家庭共享的功能建议

### ISSUE THREAD

**Issue by 1779587460** [SteamTools-Team/SteamTools#281]
### 🥰 需求描述(Description)
建议添加个防steam杀游戏进程的功能

想和朋友一起玩消逝的光芒，只能共享着玩，共享主一启动游戏玩着的人就会在几分钟后被强制退出，建议整个防杀进程的功能或者整一个不检测库主占用库的

**Comment by cyb233** [comment]
爱玩就快去买啊~

**Comment by rmbadmin** [comment]
这个功能会违反steam的政策故不会实现
