### ISSUE TITLE
🐛[BUG] 以一种访问权限不允许的方式做了一个访问套接字的尝试

### ISSUE THREAD

**Issue by MaxwellBao** [SteamTools-Team/SteamTools#282]
### 🐛 描述(Description)

显示服务端错误1006（详见截图问题2），尝试卸载和改版本都无效。不管是按加速还是检查更新都显示这个

### 🚑 基本信息(Basic Information)

用的是校园网，版本2.4.1和2.4.0都不行

### 🖼 截图(Screenshots)
![问题1](https://user-images.githubusercontent.com/85878012/121886522-1181f100-cd48-11eb-9671-ee3e10e6e519.png)
![问题2](https://user-images.githubusercontent.com/85878012/121886543-1777d200-cd48-11eb-9e22-2c69ea33ef26.png)

**Comment by AigioL** [comment]
这个问题应该是网络被拦截了，可能和杀毒软件或者有关系，也有可能是防火墙拦截了。
