### ISSUE TITLE
🐛[BUG] Steam++ 2.4.1 切换账号闪退

### ISSUE THREAD

**Issue by Astraios-A** [SteamTools-Team/SteamTools#286]
### 🐛 描述(Description)

Steam++2.2版本开始点击账号切换会出现闪退，其他功能正常。目前使用2.4.1点击切换账号也会闪退
### 📷 复现步骤(Steps to Reproduce)

1. 启动Steam++ 2.4.1
2. 点击切换账号
3. 闪退

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version): windows10 企业版 19041.173

### 🖼 截图(Screenshots)

无

**Comment by rmbadmin** [comment]
目录下logs文件夹没有生成错误日志吗？

**Comment by Astraios-A** [comment]
没有发现生成错误日志

**Comment by AigioL** [comment]
也许 AppCenter 中捕获到了闪退的日志，目前掌握的信息太少，还无法解决。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
