### ISSUE TITLE
🧐[问题] 社区加速占用内存过多，卡顿

### ISSUE THREAD

**Issue by sgrdhrd** [SteamTools-Team/SteamTools#287]
### 🧐 问题描述(Description)

你好，我在使用steam++加速的时候，突然内存就到400多，并且还有十分卡顿的现象，关闭了加速之后再开启加速就没事了，已经不止一次出现这种情况了，希望能解决

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/86065335/122420072-f7e9df00-cfbd-11eb-88fd-943c384578d1.png)

**Comment by AigioL** [comment]
使用的是那个版本的程序？

https://steampp.net/ 目前最新版 2.4.1 是有优化内存使用率的。

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/123418100-39484300-d5eb-11eb-9a34-e0530a642ff0.png)

相同问题，也是只开了加速。

**Comment by Mossimos** [comment]
是否能提供下日志.

**Comment by CKylinMC** [comment]
> 是否能提供下日志.

[Logs.zip](https://github.com/SteamTools-Team/SteamTools/files/6719623/Logs.zip)

这似乎是当天某个时间集中产生了大量日志。

如果其中包含敏感数据，请提醒我删除。

**Comment by Mossimos** [comment]
是否能回忆起当时访问的部分网站或者host里有其他指向本地的域名或资源引用可能导致了重复访问不存在的资源死循环

**Comment by CKylinMC** [comment]
> 是否能回忆起当时访问的部分网站或者host里有其他指向本地的域名或资源引用可能导致了重复访问不存在的资源死循环

我曾使用过UsbEAm Hosts Editor，而且里面部分记录现在仍然用得到，这会和Steam++冲突吗？

**Comment by Mossimos** [comment]
能否提供下用到的项我这边测试下是否会有冲突。

**Comment by CKylinMC** [comment]
> 能否提供下用到的项我这边测试下是否会有冲突。

我只能提供我现在的Hosts文件。
[hosts.txt](https://github.com/SteamTools-Team/SteamTools/files/6725525/hosts.txt)

**Comment by Mossimos** [comment]
Host文件里面有一些指向127.0.0.1的地址。问下是否程序运行了较长一段时间 ，一直在访问程序代理的网站。（可能是一些旧项目代码未更新导致端口所占用未释放 得等待排查）
还有日志种的错误出在 
steamcdn-a.akamaihd.net  应该是Steam在下载速度很快  内存暴涨来不及释放以及端口占用过多

**Comment by CKylinMC** [comment]
> Host文件里面有一些指向127.0.0.1的地址。问下是否程序运行了较长一段时间 ，一直在访问程序代理的网站。（可能是一些旧项目代码未更新导致端口所占用未释放 得等待排查）
> 还有日志种的错误出在
> steamcdn-a.akamaihd.net ~应该是Steam在下载速度很快~ 内存暴涨来不及释放以及端口占用过多
> 是在浏览市场吧
> Titanium-Web-Proxy库流未释放
> ![7N}YGQT_VB3AN5NJ4` K7 8](https://user-images.githubusercontent.com/26396340/123752530-73fff300-d8eb-11eb-8f9a-84858c0e1a70.png)


Steam++在后台时间确实时间比较长了，应该至少有两三个小时了（其实是放虚拟桌面忘了），直到开任务管理器看到内存占用偏高才看到这个的。

其实用了Steam++有一段时间了，但是一直用的并非是加速功能。前两天加速器到期了，临时用了一阵子才发现有这个问题的。

关于hosts中指向127.0.0.1的地址，有一些是以前去除验证留下的，有一些好像是其他程序加的。（其实大部分指向127.0.0.1的都已经不用了。）

确实有浏览市场和下载。

另外，hosts代理的端口希望可以修改，因为我在给同学推荐的时候经常遇到443端口冲突（例如VMware虚拟机，虽然也是可以关闭的）。

**Comment by moeshin** [comment]
我 HOST 里没有其他重定向。电脑是不关的，一般五六个小时就会出问题，有时一两天都没事，运行环境都是一样的。
出问题后，QQ 会报错闪退，不知道有没有关联。

**Comment by rmbadmin** [comment]
> 另外，hosts代理的端口希望可以修改，因为我在给同学推荐的时候经常遇到443端口冲突（例如VMware虚拟机，虽然也是可以关闭的）。
hosts代理模式端口是无法修改的，因为改了以后就无法监听了。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
