### ISSUE TITLE
🐛[BUG] 托盘菜单在任务栏处于顶部时不能正常呼出

### ISSUE THREAD

**Issue by HarlanZhang** [SteamTools-Team/SteamTools#288]
### 🐛 描述(Description)

右键单击Steam++托盘图标不能正常完整显示菜单。（本人的Windows任务栏是置于顶部的。）

### 📷 复现步骤(Steps to Reproduce)

1. 右键单击托盘图标
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):v.2.4.1
- 系统版本号(OS Version): Win10(20H2)  19042.1052

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/13798273/122489675-c4856f80-d012-11eb-8b48-2da34ce5a216.png)

**Comment by HarlanZhang** [comment]
当系统任务栏置于下方时，菜单显示是正常的。

**Comment by rmbadmin** [comment]
会在下个版本修复

**Comment by AigioL** [comment]
2.4.9 已发布
