### ISSUE TITLE
id.twitch.tv加速无效

### ISSUE THREAD

**Issue by SurveyorCangMing** [SteamTools-Team/SteamTools#289]
twitch第三方关联登录的加速无效（id.twitch.tv）
会404
其他twitch加速都正常

**Comment by YogurtZebra** [comment]
help.twitch.tv同样无效

**Comment by SurveyorCangMing** [comment]
> help.twitch.tv同样无效

help.twitch.tv没有提供加速

**Comment by AigioL** [comment]
社区加速遗漏的域名现统一在 #318 中管理，所以这边先关闭了。
