### ISSUE TITLE
🧐[Question] 点了成就管理就让重新登录，登录后还会弹出让登录，无限登录死循环

### ISSUE THREAD

**Issue by TT-IPIP** [SteamTools-Team/SteamTools#292]
点了成就管理就让重新登录，登录后还会弹出让登录，无限登录死循环

**Comment by rmbadmin** [comment]
是指提示启动steam吗？成就管理不需要登录steam++账号，但需要启动并登录steam。

**Comment by TT-IPIP** [comment]
是登录steam，点了成就管理就让重新登录steam，登录steam后还会弹出让登录steam。。。。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
