### ISSUE TITLE
🧐[Question] 启动加速服务失败，证书安装失败

### ISSUE THREAD

**Issue by lzltommy0805** [SteamTools-Team/SteamTools#293]
### 🧐 问题描述(Description)
2.4.1安装版，win10系统20H2，证书安装失败，重新安装证书还是不行。

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/73727342/122957752-d2d9df80-d3b4-11eb-9027-b04caed1f1b1.png)
![image](https://user-images.githubusercontent.com/73727342/122957806-e08f6500-d3b4-11eb-8433-ad849c77bdf9.png)

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
