### ISSUE TITLE
🧐[Question] host 文件访问被拒绝，没有权限

### ISSUE THREAD

**Issue by LuoYuLose** [SteamTools-Team/SteamTools#294]
### 🧐 问题描述(Description)

host代理出现了这个提示，前几天还能用

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/86318370/122973116-78944b00-d3c3-11eb-8e37-4bcfad9472ec.png)

**Comment by AigioL** [comment]
可能有其他软件占用了 hosts 文件，也可能是杀毒软件拦截了，就会出现这个提示
