### ISSUE TITLE
🧐[Question] Steam++ for macOS 发布日期

### ISSUE THREAD

**Issue by L1cardo** [SteamTools-Team/SteamTools#296]
### 🧐 问题描述(Description)

距离之前说的2.5.0发布日期（6.20）已经过去3天了，然后没有任何消息，之前说6.15发，延期了一次，但是这次又没能发。
对于开发中遇到的问题能理解，但是希望至少能表个态，说明一下是什么原因，还需要等几天

本人Mac用户，等2.5.0的macOS版本很久了

**Comment by AigioL** [comment]
macOS 上问题比较多，这导致了我们可能未来一段时间内还是无法发行版本。

社区加速功能需要添加证书到受信任的根目录上，目前在 Windows 上是要求了直接以管理员权限启动，在 macOS 上，有尝试过通过控制台 su 提权，但是还是抛出了拒绝访问的异常。
这影响了**社区加速**功能与**脚本配置**

启动进程的实现，像 Windows 上直接路径，后缀名 .exe，在 macOS 上好像是 .app 启动进程貌似也有点问题。
这影响了**账号切换**功能

游戏工具中目前的功能，肯定只是 Windows Only 了

整个程序很不稳定，有可能和 CEF 模块有关，也没找到原因，经常莫名其妙崩溃，这是个重点问题。

一些界面 UI 元素 大小有问题，这应该和 UI 框架有关。

目标框架(TFM) 相关的问题 net6.0-macos 无法引用 xamarin.mac ，导致 AppCenter 模块不能工作，这个也许 net6.0 正式版才能解决，不过也可以暂时不用这个。

可能还有一些其他问题，@Mossimos 可以继续补充一下

**Comment by L1cardo** [comment]
或者能否说明一下 怎么自己编译？
我根本不懂.net    编译的时候一直遇到错误，根本没有头绪

**Comment by AigioL** [comment]
在 Windows 上编译
使用 Visual Studio 2019 16.10
在左上角的工具栏中 切换 Release
右键 3_SteamTools_Libs\ST.Client.Desktop.Mac 重新生成
右键 ST.Client.Desktop.Avalonia.App 发布，左上角选择 ```osx-x64.pubxml``` 或 ```osx-arm64.pubxml``` 点击发布按钮
还要将 CEF 包附加进来，@Mossimos 吧步骤贴上
将目标位置生成的文件打包成app https://docs.avaloniaui.net/docs/distribution-publishing/macos

在 macOS 上编译
pubxml的发布好像只能在 Windows 上的 Visual Studio 中进行，Visual Studio for Mac 不行
安装 [JetBrains Rider](https://www.jetbrains.com/rider)
git克隆当前仓库
git克隆子模块
使用 Rider 打开 ```SteamToolsV2+.Mac.sln```
选择 ST.Client.Desktop.Avalonia.App 调试启动

**Comment by L1cardo** [comment]
我放弃了，解决了一个问题，又出现另一个问题

不知道是不是macOS Monterey的问题还是M1芯片的问题

**Comment by L1cardo** [comment]
> 启动进程的实现，像 Windows 上直接路径，后缀名 .exe，在 macOS 上好像是 .app 启动进程貌似也有点问题。
这影响了账号切换功能

如果要用参数启动macOS的app，好像是启动.app里面的文件，而不是.app文件本身，例如：
`/Applications/Steam.app/Contents/MacOS/steam_osx --参数`

**Comment by Mossimos** [comment]
/Applications/Steam.app这里的只是Steam的更新程序软连接到这个目录
Steam真正的目录是在如下路径种的 我们是启动的这里面的steam_osx  
/Users/用户名/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS
目前加入ASF会导致macos无法编译还在解决.

**Comment by Mossimos** [comment]
Mac版目前可以暂时测试下了。已知 的部分UI BUG  另外推荐使用系统代理模式 减少需要输入密码。
ASF部分暂不可用，  挂时常等 不可用。
可能出现部分UI卡死
加速 ，脚本，令牌 可用
可以在这里下载

[https://pan.mossimo.net:5212/s/KOfM](url)
[https://85.nl77.seedit4.me/filebrowser/share/WOXgOH_O](url)
[https://pan.baidu.com/s/1m0CV0x5ASu234w9INWPFpw](url)  提取码: casx 

M1 Mac上的运行情况未知

**Comment by Mossimos** [comment]
macOS 12 bate3 已知 打包成.app的包闪退无法运行  将app内macos文件夹 复制出来终端运行 ./steam++可正常运行

**Comment by L1cardo** [comment]
M1上可以运行，并没有出现这个情况

> macOS 12 bate3 已知 打包成.app的包闪退无法运行 将app内macos文件夹 复制出来终端运行 ./steam++可正常运行

问题
1. 字体有点模糊
2. 有时会闪退
3. 脚本功能测试了csgo查看磨损值，但是没效果，不知道其余脚本怎么样
4. 通过steam登录steam++无效，手机号可以登录

正常:
1. 令牌功能正常（我用的最多的）

未测试：
1. 加速功能没测试，我是用代理，加速功能我也不用
2. 账号切换
3. 设置里面的项目均没测试

**Comment by Mossimos** [comment]
脚本需要先用前置加速功能才能生效的。
steam登录目前在修改登录方式之后会调用系统浏览器。
字体模糊目前还不清楚什么引起的，在测试机器上字体未出现模糊但是 另外几个机器都出现模糊。

**Comment by AigioL** [comment]
macos beta 版本目前已经发布，和之前的版本相比，更改了根目录下的文件夹重定向到

https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop.Mac/FileSystemDesktopMac.cs#L18

  ```AppData 目录重定向到``` [NSSearchPathDirectory.LibraryDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nslibrarydirectory)
  ```Cache 目录重定向到``` [NSSearchPathDirectory.CachesDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nscachesdirectory)
