### ISSUE TITLE
🧐[Question] Steam++ for Android 发布日期

### ISSUE THREAD

**Issue by lanyani** [SteamTools-Team/SteamTools#297]
如题！
Windows版和Android版能否先出一个测试版？
我太期待Android版了！

**Comment by AigioL** [comment]
Android 版现在大概就 30% 左右，还需要一段时间。
之后还要再研究 ASF + Vue那套WebUI 跑在 Android 上，需要挂个服务，涉及通知栏以及安卓后台限制等，看要搞个新进程来跑服务

2.5 要看 @rmbadmin  啥时候能吧 ASF Plus 整完了


上面这些内容全部完成后

还要测试新的下载更新方式，改动了增量更新升级的逻辑，要么不测了发 beta 版得了。

**Comment by lanyani** [comment]
beta版肯定要比自己测试好!使用的人多了那些微小的bug就很容易全部找出来!像我这种有bug就会第一时间反映!等你觉得效果可以beta体验的时候完全可以放出来!

**Comment by AigioL** [comment]
2.4.9 已发布 Alpha 版本
