### ISSUE TITLE
🐛[BUG] 手机导入的令牌会闪退

### ISSUE THREAD

**Issue by cero-ss** [SteamTools-Team/SteamTools#298]
### 🐛 描述(Description)

2.3的时候我用手机令牌导入是可以用的，但是升级到2.4.1后导入就直接闪退

### 📷 复现步骤(Steps to Reproduce)

1. 按说明导入后点击确认导入，软件就闪退
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version):

**Comment by rmbadmin** [comment]
logs文件夹是否有日志？有的话麻烦提交一下，谢谢

**Comment by cero-ss** [comment]
> 日志记录器次日志？？，当之以"金德"

好像是我没填令牌名称导致的，随便填了个名字就不闪退了
