### ISSUE TITLE
Steam++添加iOS本地令牌方法（无需越狱！！！）

### ISSUE THREAD

**Issue by L1cardo** [SteamTools-Team/SteamTools#299]
1. 将手机上的 Steam App 降级到 `2.0.16`，其他版本没有测试，反正 App Store 里最新版是不行的。因为 Steam 更新以后，将验证码存放在了更安全的地方。具体怎么安装旧版的 App，自己百度。

2. 利用 iTunes 备份 iPhone，备份的时候**不要选**加密备份。备份完确保这个路径下确实有备份文件  
 - Windows
`C:\Users\用户名\AppData\Roaming\Apple Computer\MobileSync\Backup\`
- macOS
`/Users/用户名/Library/Application Support/MobileSync/Backup/`

3. 下载 [工具](https://github.com/AigioL/ios-steamguard-extractor/releases/tag/v1.11) 解压后进行下一步
- Windows
  - 如果你的系统是 64 位，则下载 win-x64.7z
  - 如果你不知道你的系统是不是 64 位或者你的系统是 32 位，则下载 win-x86.7z
  - 如果你使用 ARM 芯片的 PC（较为稀有），例如 [Surface Pro X](https://www.microsoftstore.com.cn/surface/surface-pro-x)，则下载 win-arm64.7z
- macOS/OSX
  - 下载 osx-x64.7z
- linux
  - 如果你 CPU 是 Intel/AMD 的 x86 芯片（较为普遍），则下载 linux-x64.7z
  - 如果你 CPU 是 ARM 芯片，例如 树莓派，则下载 linux-arm64.7z

4. 运行工具，然后点击最下的按钮，选择备份文件所在的目录，默认会定向到上面的路径，点击确定，会看到如下的信息
![image](https://user-images.githubusercontent.com/33802186/123431177-92b86e00-d5fb-11eb-92df-3dd8257d636f.png)

5. 然后在Steam++中导入即可。`android`字样也要复制，下面的`{}`符号也要复制
<img width="643" alt="image" src="https://user-images.githubusercontent.com/33802186/123431117-7e747100-d5fb-11eb-99b4-eb538c91b19e.png">

参考自：https://github.com/CaitSith2/ios-steamguard-extractor/issues/4#issuecomment-817247572

**Comment by AigioL** [comment]
这个工具 WinForms 写的，可以用 Mono 跑在 Mac/Linux 上应该也没问题

装 Mono 后应该在终端中输入 mono xxx.exe 应该能跑
https://www.mono-project.com/download/stable/#download-mac

**Comment by L1cardo** [comment]
刚测试了，在我的m1 Mac上不能运行这个app，而且这个app读取的备份文件的路径也写死了

**Comment by AigioL** [comment]
iTunes备份iPhone 在 macOS 上的默认目录值是什么？之后我看改一下他这个项目

**Comment by AigioL** [comment]
命令行是可以，只是 GUI 比较方便，.net 在 macOS ARM64 上还没有正式版，M1 问题肯定不少

**Comment by L1cardo** [comment]
> iTunes备份iPhone 在 macOS 上的默认目录值是什么？之后我看改一下他这个项目

`/Users/licardo/Library/Application Support/MobileSync/Backup/`
在这个路径

其实最好的是可以用户输入路径，但是写死对小白用户也好

**Comment by AigioL** [comment]
可以试试 https://github.com/AigioL/ios-steamguard-extractor/releases/tag/v1.06

改成点击按钮弹窗选择目录，默认目录存在时定位到默认目录上

他这拿目录遍历找文件，要是手动选了个文件夹多的目录，计算量就大了

好像是在主线程上遍历目录的，可能会卡，懒得优化了

**Comment by AigioL** [comment]
发布的程序 没有后缀名的文件，看能不能用终端打开，这个没后缀名的文件，我在 VM 虚拟机上他默认是终端打开，能用，但是另一台黑苹果上，默认打开方式是文本阅读器，选终端也打不开。

要是打不开只能按这个文档，整个 .app 的文件夹了 https://docs.avaloniaui.net/docs/distribution-publishing/macos

linux 上倒是直接能执行

**Comment by L1cardo** [comment]
`chmod 755 /iOSSteamGuardExtractor` 执行这个命令可以转换为直接终端可运行的`Unix可执行文件`文件
但是我碰到一些问题：
1. 你昨天发的arm版本不能打开，x64可以，可能就是.net没有适配m1 Mac
2. 打开app提示无法连接数据库
<img width="740" alt="image" src="https://user-images.githubusercontent.com/33802186/123531705-6b67bb00-d739-11eb-8632-b6d9a0c67634.png">

**Comment by AigioL** [comment]
刚通过 SHA1 比对了下 ```libAvaloniaNative.dylib, libHarfBuzzSharp.dylib, libSkiaSharp.dylib``` 
这3个文件 x64 和 arm64 上居然是一样的

看来是 AvaloniaUI 这个 UI 框架没适配 macOS ARM64

.Net 6 macOS ARM64 应该是原生支持的

他这个库 Sqlite 用的 ```System.Data.SQLite.Core```，我改成了 ```Microsoft.Data.Sqlite.Core```
https://github.com/AigioL/ios-steamguard-extractor/blob/v1.08/iOSSteamGuardExtractor/MainWindow.axaml.cs#L198
连接字符串中 Version=3 这部分在 ```Microsoft.Data.Sqlite.Core``` 上不支持，删掉这部分重新编译后

https://github.com/AigioL/ios-steamguard-extractor/releases/download/v1.09/osx-x64.7z
你再试试 @L1cardo

**Comment by L1cardo** [comment]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/33802186/123532680-dc12d580-d741-11eb-8887-78116a02a1ba.png">
哈哈  又是另外的错误

**Comment by AigioL** [comment]
https://github.com/AigioL/ios-steamguard-extractor/releases/download/v1.10/osx-x64.7z

这次应该 🆗 了
@L1cardo

**Comment by L1cardo** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/33802186/123533407-de782e00-d747-11eb-8ed4-f85317cd29a9.png">
这次是真的OK了！！
但是信息会显示两遍，不过无伤大雅！！

**Comment by HUD-A** [comment]
Processing backup: THUD-Ipad version 15.0
An Exception occurred while processing: Connection string keyword 'version' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.Done
我试了1.6以上所有包，都有问题，v1.10以上直接运行不了

**Comment by AigioL** [comment]
> Processing backup: THUD-Ipad version 15.0
> An Exception occurred while processing: Connection string keyword 'version' is not supported. For a possible alternative, see https://go.microsoft.com/fwlink/?linkid=2142181.Done
> 我试了1.6以上所有包，都有问题，v1.10以上直接运行不了

这个错误是之前版本有bug无法正常使用，v1.10 开始才能正常使用

系统版本是多少，不能运行有什么错误提示弹窗吗？可以试一下 Windows 版本的

https://github.com/AigioL/ios-steamguard-extractor/releases/download/v1.11/win-x64.7z

**Comment by rmbadmin** [comment]
后续会在Discussions中归档一下教程类的问题，现在暂时关闭。

**Comment by soy-bottle** [comment]
现在还能用吗？winx64和x86都打不开，没有反应

**Comment by DondurmaCat** [comment]
> winx64和x86都打不开，没有反应

我也遇到了这个问题，打开之后没有反应。
而且我的IOS备份文件的位置是C:\Users\用户名\Apple\MobileSync\Backup

**Comment by AigioL** [comment]
> > winx64和x86都打不开，没有反应
> 
> 我也遇到了这个问题，打开之后没有反应。 而且我的IOS备份文件的位置是C:\Users\用户名\Apple\MobileSync\Backup

@soy-bottle @DondurmaCat 刚编译了新的版本
https://github.com/AigioL/ios-steamguard-extractor/releases/tag/v1.3.0
可以尝试使用 .NET Framework 4.8  的版本，```win-netfx.7z```
在 Windows 10 2019 年 5 月更新 之后的版本中已包含 .NET Framework 4.8 运行库
https://docs.microsoft.com/zh-cn/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-48

**Comment by DondurmaCat** [comment]
> 
遇到了新的问题，软件显示“Directory 00 is not in a recognized backup format.
Listing contents of this directory.  Please open an issue and paste this listing as well as the Version of ios and itunes you are using.”

**Comment by L1cardo** [comment]
> 遇到了新的问题，软件显示“Directory 00 is not in a recognized backup format.
> Listing contents of this directory. Please open an issue and paste this listing as well as the Version of ios and itunes you are using.”

你要选上级目录

**Comment by Nebulosa-Cat** [comment]
似乎終究是失效了，選擇上級目錄依然顯示Skip

**Comment by L1cardo** [comment]
截止`2022年6月23日`，此方法依旧有效，楼上失败的注意仔细阅读操作步骤
<img width="580" alt="image" src="https://user-images.githubusercontent.com/33802186/175295278-e9ed81c6-1c3d-4cdc-a3c3-ed85b806cbad.png">

**Comment by L1cardo** [comment]
@AigioL 只是提取出来的JSON文件好像数据错位了，麻烦看一下
<img width="576" alt="image" src="https://user-images.githubusercontent.com/33802186/175297273-cc32b79e-28ab-408a-936b-00d4a0e2dd8e.png">

**Comment by HexYoF** [comment]
这是怎么回事？
![image](https://user-images.githubusercontent.com/86894853/179248895-6bb27cd9-330e-4b12-9fc2-96cf41666747.png)

**Comment by RwangToo** [comment]
steam 2.0.16现在好像无法登录了
