### ISSUE TITLE
长时间睡眠并唤醒后程序自动退出。

### ISSUE THREAD

**Issue by ccboxes** [SteamTools-Team/SteamTools#3]
如题，与302一样的毛病。PC睡眠一夜后唤醒发现程序已经退出，需要手动启动。

**Comment by rmbadmin** [comment]
我昨天测试了一夜和今天出门测试了一下长时间睡眠程序没有闪退，问题无法复现暂时不好解决，可以问一下你程序闪退能查找windowsr日志应用程序日志里是否能看到有steam++的异常日志吗？

**Comment by ccboxes** [comment]
> 
> 
> 我昨天测试了一夜和今天出门测试了一下长时间睡眠程序没有闪退，问题无法复现暂时不好解决，可以问一下你程序闪退能查找windowsr日志应用程序日志里是否能看到有steam++的异常日志吗？

我昨天也反复试了，现在的结论是笔记本在使用电池时休眠，有小概率复现，事件查看器里并没有发现任何相关日志。

**Comment by firsdrea** [comment]
> 应用程序: Steam++.exe
> Framework 版本: v4.0.30319
> 说明: 由于未经处理的异常，进程终止。
> 异常信息: System.OutOfMemoryException

> 错误应用程序名称: Steam++.exe，版本: 1.0.2.0，时间戳: 0xd108fe12
> 错误模块名称: KERNELBASE.dll，版本: 10.0.19041.662，时间戳: 0xe6477cce
> 异常代码: 0xe0434352
> 错误偏移量: 0x0012a892
> 错误进程 ID: 0x6ab4
> 错误应用程序启动时间: 0x01d6da0e5c798852
> 错误应用程序路径: D:\Steam++\Steam++.exe
> 错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
> 报告 ID: 1464b416-9770-4f78-84db-16d60a36543c
> 错误程序包全名: 
> 错误程序包相对应用程序 ID: 

我遇到了相同问题，错误报告如上，不清楚是否还需要其它信息。
我的情况是台式机手动添加了休眠模式，长时间（未测试短时间是否会触发）使用休眠模式（未测试睡眠模式是否会触发）后会发生这个情况。
系统是Windows 10 20H2。

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
