### ISSUE TITLE
🧐[Question] 英文翻译问题

### ISSUE THREAD

**Issue by L1cardo** [SteamTools-Team/SteamTools#300]
### 🧐 问题描述(Description)
刚好奇瞥了一眼英文翻译，真的是辣眼睛，比机翻还差，请问怎么可以对翻译做贡献？

**Comment by AigioL** [comment]
比机翻还差应该不至于，毕竟就是机翻

英文翻译有一份贡献值翻译的数据，其他翻译的文本好像也有，但是还没校对，所以也没放上来，目前在开发中也一直在新增文本内容。

要优化一下 Resx 翻译工具
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Tools.Translate/Program.cs

这部分功能要改进一下
- 读取 .resx 文件生成 excel 表格
- 读取翻译后的 xlsx 文件写入 .resx 文件，目前的实现写入了重复项，对于已有的项，要进行比对或替换

之后可以用此工具，将 resx 导出成 xlsx 表格，翻译后导入

**Comment by AigioL** [comment]
2.4.9 已发布
