### ISSUE TITLE
🐛[BUG] 程序加速过程中崩溃后，社区/游戏服务器无法连接

### ISSUE THREAD

**Issue by oneoness** [SteamTools-Team/SteamTools#303]
### 🐛 描述(Description)
1. 如题。需要补充的是，账号可以登录，但是最开始连好友服务器也连接不上，账户明细点进去是无法验证服务器。
使用其他加速器加速社区后进入**steam客服**验证账号后“永久”解决了以上问题，即不开任何加速器也能成功连接。
而下面的才是最折磨的。
2. **所有游戏**，能进去，能看到好友状态，能搜索到其他人开的房间。但是就是不能进去，会提示连接服务器失败。
如果是csgo的话，搜索游戏约5秒后会直接变成黄色，提示无法连接到任何官方服务器。（重装steam无法解决问题）
但是开加速器（包括steam++）后，游戏服务器的问题将不会存在（关了又会有）。而很多小众的游戏，加速器是没有服务的，这是这个bug最难受的地方。
3. 我另一个不幸也触发了这个bug的朋友，在重装了steam++（v2.3.0换成了v2.4.1）后，使用steam++加速也无法解决游戏服务器的问题

根据触发这个bug的过程（即下面的复现步骤），我猜测是由于加速过程使用了反向代理，而程序卡死并且用任务管理器关闭程序后，导致反向代理的一些配置出现了问题。尝试过清理DNS缓存然而并没有效果。

我希望作者能找到这个bug产生的原因以及解决方式，因为玩任何游戏得开加速器而且有的游戏没有加速器，这真的非常难受。谢谢。

### 📷 复现步骤(Steps to Reproduce)

1.  启动steam++的加速功能（启动了就行，不一定是要开始启动的时候）
2.  因各种原因（可能是电脑卡，或者别的原因）导致steam++卡死。对没错只有steam++卡死了
3.  使用任务管理器关闭steam++

### 📄 [异常/日志]信息([Exception/Log] Information)
2021-06-28 15:43:04.5505|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

这条异常应该影响不大，因为在触发这个bug之前的日志就有，而这个bug的触发并没有任何其他的日志信息，可能因为触发时卡死的缘故？
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.3.0
- 系统版本号(OS Version): win10

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/65436764/123617362-bff25f80-d839-11eb-97de-9e66b0f8e718.png)
![image](https://user-images.githubusercontent.com/65436764/123617533-efa16780-d839-11eb-8d21-a9cda9dd538c.png)

**Comment by Tansty** [comment]
我就是另外一个不幸的bug触发者，我不是像上面所说的方式触发的bug，我刚开始hosts加速提示443端口被占用，关闭了443端口后，短时间服务全部正常，过了一段时间引发了这个bug，也就是像上面所说的所有的服务器连接异常问题。
   我的异常报错信息：
2021-06-28 17:35:28.2729|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId) in SAM.API.dll:token 0x600001f+0xee
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize() in System.Application.SteamTools.Client.Desktop.Windows.dll:token 0x60008bc+0x27

**Comment by oneoness** [comment]
@Tansty 上面所说的关闭443端口，并不是关闭端口，其实是关闭了占用端口的另一个程序

**Comment by rmbadmin** [comment]
> 我就是另外一个不幸的bug触发者，我不是像上面所说的方式触发的bug，我刚开始hosts加速提示443端口被占用，关闭了443端口后，短时间服务全部正常，过了一段时间引发了这个bug，也就是像上面所说的所有的服务器连接异常问题。
> 我的异常报错信息：
> 2021-06-28 17:35:28.2729|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
> at SAM.API.Client.Initialize(Int64 appId) in SAM.API.dll:token 0x600001f+0xee
> at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize() in System.Application.SteamTools.Client.Desktop.Windows.dll:token 0x60008bc+0x27

这个日志是因为steam启动过程中steam++注入产生的，但是不会有任何影响，也与加速不相关。

**Comment by rmbadmin** [comment]
崩溃后无网络的问题，是因为加速和停止加速本来有正常的逻辑要执行，因为在加速中将程序强退了，所以停止加速的逻辑没执行，也就没还原加速所修改的配置导致的。

遇到这个问题可以尝试还原hosts文件，关闭windows系统代理，重置网络服务

**Comment by oneoness** [comment]
通过重置网络服务（修复lsp）已完美解决这个问题

**Comment by rmbadmin** [comment]
> 通过重置网络服务（修复lsp）已完美解决这个问题

好的，后续会将这个功能做到steam++内，并且在程序异常结束后下次运行时自动执行还原来修复此问题。

**Comment by Tansty** [comment]
通过重置网络服务（修复lsp）已完美解决这个问题(还需要一个好的网络)

**Comment by AigioL** [comment]
使用 https://github.com/SteamTools-Team/SteamTools/issues/302 方案后应该能彻底解决此问题。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
