### ISSUE TITLE
👑[Enhancement] 创意工坊请求适配划词翻译脚本

### ISSUE THREAD

**Issue by izANTM** [SteamTools-Team/SteamTools#304]
### 🥰 需求描述(Description)

创意工坊一大堆看不懂，我每次都复制到网页翻译。我自己试着导入了Greasy Fork的几个脚本，但是翻译结果都是只能显示英文，中文都是“?????”问号。球球了，适配一个吧！

**Comment by Mossimos** [comment]
是哪几个脚本提供下地址啊啊👀

**Comment by izANTM** [comment]
https://greasyfork.org/zh-CN/scripts/399313-%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91-%E5%86%BB%E7%8C%AB-%E4%BF%AE%E6%94%B9%E7%89%88

**Comment by izANTM** [comment]
https://greasyfork.org/zh-CN/scripts/35251-%E6%99%BA%E8%83%BD%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91

**Comment by Mossimos** [comment]
👀已经兼容了
https://greasyfork.org/zh-CN/scripts/399313-%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91-%E5%86%BB%E7%8C%AB-%E4%BF%AE%E6%94%B9%E7%89%88
这份 需要先更新下Gm.js 后去脚本工坊安装这个就行了
自己添加 本地 的话 吧脚本里面 
(function() {

})();
这个括起来的删掉再添加也行

**Comment by izANTM** [comment]
> 👀已经兼容了
> https://greasyfork.org/zh-CN/scripts/399313-%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91-%E5%86%BB%E7%8C%AB-%E4%BF%AE%E6%94%B9%E7%89%88
> 这份 需要先更新下Gm.js 后去脚本工坊安装这个就行了
> 自己添加 本地文件 的话 吧脚本里面
> (function() {
> 
> })();
> 这个括起来的删掉再添加也行

更新了，安装工坊里的脚本，还是只能显示英文和"????"

**Comment by izANTM** [comment]
![S_2021-06-30_37](https://user-images.githubusercontent.com/35513144/123899263-6b65f600-d999-11eb-9911-32930248ba53.jpg)

**Comment by Mossimos** [comment]
需要更新程序 之前没有正确的识别 Content-Type 中的字符编码得等下个版本了

**Comment by AigioL** [comment]
@Mossimos 2.4.9 已发布，确认一下数据库里是不是启用了该脚本，没问题的话关闭此 issue
