### ISSUE TITLE
🐛[BUG] 【过时版本注意】 2.3.0版本应用内检查更新无效 && 账号切换功能不可用

### ISSUE THREAD

**Issue by ClementLevi** [SteamTools-Team/SteamTools#305]
### 🐛 描述(Description)

虽然官网已经开放了2.4.1版本下载，但客户端无法检测

此外，账号切换功能也不可用（提示未检测到账号数据）

初步推测是版本过旧导致。你们应该已经修了对吧

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.3.0 **_过时版本注意_**
- 系统版本号(OS Version):  Windows 10.19042.1052

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/35921237/123732417-77d04d00-d8cc-11eb-88b6-d777b7dfa49c.png)
![image](https://user-images.githubusercontent.com/35921237/123732444-80c11e80-d8cc-11eb-8382-e09e80a60c4c.png)

**Comment by AigioL** [comment]
2.4 之前的版本客户端上的更新逻辑有一些 bug，导致没法更新到 2.4 以上的版本，这个问题因为在客户端上的，所以修了也不会影响之前已发布了的客户端版本。

账号切换没有读取到数据这个问题 @rmbadmin  或 @Mossimos  看看

**Comment by rmbadmin** [comment]
> 账号切换没有读取到数据这个问题 @rmbadmin 或 @Mossimos 看看

可能是steam注册表信息没有正确获取，尝试覆盖重装steam

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
