### ISSUE TITLE
🐛[BUG] 创建本地令牌报错

### ISSUE THREAD

**Issue by AlexCZhou** [SteamTools-Team/SteamTools#306]
### 🐛 描述(Description)
移除手机Steam客户端的令牌后，在steam++创建本地令牌结果报错
报错如下

### 📷 复现步骤(Steps to Reproduce)

1. 移除手机steam客户端的令牌
2. steam++令牌导入
3. 从steam账号导入
4. 报错如图

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version): Windows10 19041.1052

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/33609801/123739541-62adeb00-d8d9-11eb-9657-ff5af36b9a4c.png)

**Comment by SakuraSayaka** [comment]
same

**Comment by AigioL** [comment]
可能与 #200 相同 @rmbadmin

**Comment by AlexCZhou** [comment]
> 可能与 #200 相同 @rmbadmin

但是我确实开了代理，通过Steam++开的

**Comment by AigioL** [comment]
可能开了代理也连不上社区

可以试一下能不能访问 https://steamcommunity.com

```远程主机强迫关闭了一个现有的连接``` 这个可能是网络状态切换时导致的，具体原因也不清楚

**Comment by AlexCZhou** [comment]
今天试了一下成功把令牌导入进去了，发生这个问题的时候确确实实是开了代理的，别说steam社区了、Google、Youtube都是秒开。

总之我先把这个Issue关闭了，因为我已经没法再复现这个问题了。
