### ISSUE TITLE
🐛[BUG] 设置开机自启后，开启无法自启

### ISSUE THREAD

**Issue by znwuyi** [SteamTools-Team/SteamTools#308]
### 🐛 描述(Description)

设置开机自启后，开启无法自启，启动列表中没有Steam++

### 📷 复现步骤(Steps to Reproduce)
设置开机自启后，开启无法自启，启动列表中没有Steam++

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

2.4.1- 程序版本(Program Version):
Windows 11 22000.51- 系统版本号(OS Version):

**Comment by znwuyi** [comment]
> ### 🐛 描述(Description)
> 设置开机自启后，开启无法自启，启动列表中没有Steam++
> 
> ### 📷 复现步骤(Steps to Reproduce)
> 设置开机自启后，开启无法自启，启动列表中没有Steam++
> 
> 
> ### 📄 [异常/日志]信息([Exception/Log] Information)
> ### 🚑 基本信息(Basic Information)
>- 程序版本(Program Version): 2.4.1
> - 系统版本号(OS Version):Windows 11 22000.51
> 
> ### 🖼 截图(Screenshots)

**Comment by znwuyi** [comment]
解决方法:
计划任务勾选最高权限运行;
![image](https://user-images.githubusercontent.com/58579685/124016994-c4c13a00-da18-11eb-8d18-2e7eb0dda26f.png)
右键Steam++属性勾选以管理员身份启动
![image](https://user-images.githubusercontent.com/58579685/124017076-ddc9eb00-da18-11eb-9a53-76ac5e9db480.png)

**Comment by moeshin** [comment]
我的 Win11 自启项经常都是随缘启动，不止 Steam++
看了任务计划里 Steam++ 的权限默认是有的，但是启动路径错了：`Steam++\Bin`

**Comment by rmbadmin** [comment]
> 我的 Win11 自启项经常都是随缘启动，不止 Steam++
> 看了任务计划里 Steam++ 的权限默认是有的，但是启动路径错了：`Steam++\Bin`

是的，因为2.4.1修改了程序目录结构，但是开机自启这里的路径忘记更改了，下个版本发布时就会修复

**Comment by moeshin** [comment]
> 我的 Win11 自启项经常都是随缘启动，不是指 Steam++
> 看了任务计划里 Steam++ 的权限默认是有的，但是启动路径错了：`Steam++\Bin`

> 可以先手动在 `计算机管理(本地) - 系统工具 - 任务计划程序 - 任务计划程序库` 中 找到名称为 `Steam++` 的项 双击打开 顶部 Tab 切换到 操作，编辑列表中唯一的操作项 在 `起始于(可选)(T):` 将目录末尾的 `\Bin` 删除即可

https://github.com/SteamTools-Team/SteamTools/issues/276#issuecomment-859630434

**Comment by AigioL** [comment]
2.4.9 已发布
