### ISSUE TITLE
求Linux版

### ISSUE THREAD

**Issue by SituChengxiang** [SteamTools-Team/SteamTools#31]
单独给个代理也可以啊~

**Comment by rmbadmin** [comment]
因为目前预期的功能都还没有做完，所以暂时没法分心做其它平台的。

**Comment by SituChengxiang** [comment]
嗯好的，我先自己看看有没有其他解决方案吧，谢谢回复

**Comment by 8MiYile** [comment]
> 因为目前预期的功能都还没有做完，所以暂时没法分心做其它平台的。

建议换个开发架构 Qt之类的

**Comment by AigioL** [comment]
2.4.9 已发布 Alpha 版本
