### ISSUE TITLE
👑[Enhancement] Better Migrate From MileStone to Project

### ISSUE THREAD

**Issue by Lutra-Fs** [SteamTools-Team/SteamTools#311]
### 🥰 需求描述(Description)

最好将任务组织形式从MileStone迁移到Project,现有的Milestone有点不美观 或者针对每个功能需求开issue
### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/36790218/124065889-fec32800-da7a-11eb-8c89-d10a03da4e9b.png)

https://github.com/microsoft/winget-cli/milestone/35
![image](https://user-images.githubusercontent.com/36790218/124066312-cbcd6400-da7b-11eb-815f-ac93b975f688.png)

**Comment by AigioL** [comment]
https://github.com/SteamTools-Team/SteamTools/milestone/3
