### ISSUE TITLE
ASF Plus

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#313]
- [x] 分离 NLog
- [x] 控制台文本框控件
- [x] UI
    - [x] ASF 控制台
    - [x] ASF Web UI
    - [x] Bot 配置
    - [x] ASF 配置

**Comment by L1cardo** [comment]
能否增加对自建asf的管理？

**Comment by AigioL** [comment]
> 能否增加对自建asf的管理？

配置文件是相同的，可以配置后将配置文件移动到 自建 ASF 中，配置文件存储在 AppData 目录上

**Comment by L1cardo** [comment]
我的意思是，自建的ASF跑在服务器，可以通过Steam++来进行服务器上的ASF的管理

**Comment by rmbadmin** [comment]
> 我的意思是，自建的ASF跑在服务器，可以通过Steam++来进行服务器上的ASF的管理

服务器上可以自行使用ipc后台管理，后续看情况可能会添加支持远程ipc的管理
