### ISSUE TITLE
翻译工具

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#316]
- [x] WriteCommand
    - [x]  读取 resx 文件
    - [x]  自动机翻
    - [x]  写入 xlsx 文件
- [x] ProofreadCommand
    - [x]  读取 xlsx 文件
    - [x] 对译文机翻回原文用作校对
- [x] WriteCommand
    - [x]  读取 xlsx 文件
    - [x] 写入 xlsx 文件

**Comment by Lutra-Fs** [comment]
社区翻译？

**Comment by AigioL** [comment]
> 社区翻译？

我们目前有 西班牙语、英语、意大利语、日语方面的贡献者

计划是有贡献者 可以加入 QQ 群

然后我们通过这个 翻译工具，生成 xlsx 表格文件，供贡献值翻译

翻译与校对后可以直接导入到程序项目中

**Comment by Lutra-Fs** [comment]
我感觉可能开一个存储库来管理会好一些 QQ群可能不是每个人都可用
另外使用 json csv 等格式可能会便于版本管理

**Comment by AigioL** [comment]
resx 的格式实际上是 XML，已经在git版本管理中，对于生成的表格数据，没必要再管理一份，还可能导致两份数据可能还存在不一样。

像 json 格式，对于非开发者来说其实并不友好

csv 格式 没办法控制表格样式，比如宽度

主要是翻译工具目前用了 Azure 的翻译 API，需要 Azure 的 Key，这一步骤目前是写成必须的，用作生成机翻做参考，虽然这一步确实可有可无。

这一步骤如果跳过，或者使用自己的 Key 则可以直接编译【翻译工具】项目来生成 xlsx 文件

我们目前的翻译贡献者，都是非软件行业的，像版本管理这些东西还是太专业化了

对于软件行业的开发者而言，其实可以直接改 resx 文件，再 PR 上来，也没什么问题，只是工具能实现一些自动化的审阅工作，省一点人工成本。

目前的计划还是 贡献值联系 https://space.bilibili.com/30031316 加入翻译的QQ群，或者之后弄其他的社交平台。

**Comment by L1cardo** [comment]
可以看看crowdin 或者 poeditor等本地化工具

**Comment by AigioL** [comment]
> 可以看看crowdin 或者 poeditor等本地化工具

看了一下
crowdin 整体价格还是很高的，而且也不支持 resx 文件格式
poeditor 倒是支持，免费级别只有 1000 个字符串，也暂时够用

但是这些工具还是满足不了项目的需求，还是自己写的最合适。
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Tools.Translate/README.md

可以克隆仓库，编译 ST.Tools.Translate 项目
生成命令行工具
使用命令导出 xlsx 文件，或者 加群从群文件下载定期生成好的文件
填写上翻译内容与作者名
再使用命令导入进 resx 文件提交上来就行了

xlsx 都是临时文件，resx 文件可以受到 git 版本管理的

resx 格式就是 xml
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/UI/Resx/AppResources.resx

目前除了一些字符串写在了 resx 里，也有一些其他的资源也放进去了，这部分资源是不用翻译的，比如这个地方
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/Properties/SR.resx#L132
