### ISSUE TITLE
👑[Enhancement] 应只为当前用户开机自启

### ISSUE THREAD

**Issue by Lutra-Fs** [SteamTools-Team/SteamTools#317]
### 🚑 其他信息(Other Information)

如题 现在是为所有用户启动

**Comment by AigioL** [comment]
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop.Windows/Services/Implementation/WindowsDesktopPlatformServiceImpl.cs#L121

LogonTrigger 有一个 UserId 指定 用户名

在计算机管理的 UI 上查看，这个用户名，好像是 计算机名\用户名
这么个格式，斜杠会不会受到区域或语言影响？像某些区域使用 $ 做路径分隔符

如果要指定用户名的话，就得多个 TaskDefinition，那么是不是建个文件夹放里面比较合适？放进去的话，之前的 Q&A 文档也要对应改一下。

**Comment by AigioL** [comment]
Gets or sets The identifier of the user. For example, "MyDomain\MyName" or for
a local account, "Administrator".
This property can be in one of the following formats:
• User name or SID: The task is started when the user logs on to the computer.
• NULL: The task is started when any user logs on to the computer.

看来是 这个计算机名如果加入了 AD域 也会变成 域名 

```Environment.MachineName``` 与· ```Environment.UserName```  这两个 API 应该能拿到对应需要的值

MachineName 在加入 AD 域的机子上返回的可能还是机器名

**Comment by Lutra-Fs** [comment]
使用SID即可

参考 https://social.msdn.microsoft.com/Forums/vstudio/en-US/16209a1f-e874-464b-85ad-7a2c33e3ffdb/get-current-user-sid?forum=csharpgeneral
2021年7月3日 +1000 00:31 Aigio L ***@***.***>，写道：

**Comment by AigioL** [comment]
### 实施方案

在 ST.Client.Desktop.Windows 项目中添加包引用
https://www.nuget.org/packages/System.DirectoryServices.AccountManagement/5.0.0

使用正式版的包，不用 6.0预览版的

```string sid = UserPrincipal.Current.Sid.ToString();```
https://docs.microsoft.com/zh-cn/dotnet/api/system.directoryservices.accountmanagement.userprincipal.current?view=dotnet-plat-ext-5.0
https://docs.microsoft.com/zh-cn/dotnet/api/system.directoryservices.accountmanagement.principal.sid?view=dotnet-plat-ext-5.0

**Comment by Lutra-Fs** [comment]
其实我本来想开个pr 可vs怎么都调不好...

**Comment by AigioL** [comment]
![3G8H5}$_FBM2KLWD6UIIXJ6](https://user-images.githubusercontent.com/24450093/124385771-b40b0f80-dd09-11eb-8f9c-0db36b9ac0f1.png)

这个 SID 获取用了 18 秒！这方案肯定不行。

**Comment by AigioL** [comment]
更新下个版本后，需要将 开机自启开关，关闭再开启才会生效。

**Comment by AigioL** [comment]
2.4.9 已发布
