### ISSUE TITLE
在Linux上如何通过编译源码安装

### ISSUE THREAD

**Issue by 20070404zk** [SteamTools-Team/SteamTools#324]

**Comment by AigioL** [comment]
克隆仓库与子模块
[安装 .NET SDK 6.0.100-preview.5](https://docs.microsoft.com/zh-cn/dotnet/core/install/)

#### 在 Windows 上通过 Visual Studio 发布 linux-x64 或 linux-arm64
1. 使用 Visual Studio 打开 SteamToolsV2+.sln
2. 左上角 解决方案配置 切换到 Release，如果当前选择的项为 Debug 时
3. 在解决方案资源管理器中重新生成 ```ST.Client.Desktop.Linux``` 项目
4. 右键 ```ST.Client.Desktop.Avalonia.App``` 项目 选择发布
5. 在发布页左上角选择 ```linux-x64``` 或 ```linux-arm64``` 点击发布

#### 在 Linux 上通过 命令行发布 linux-x64 或 linux-arm64
1. 在 ```src\ST.Client.Desktop.Avalonia.App``` 中打开终端
2. 输入 ```dotnet publish -p:PublishProfile=linux-x64``` 或 ```dotnet publish -p:PublishProfile=linux-arm64```

**Comment by 8MiYile** [comment]
@AigioL https://paste.ubuntu.com/p/RtnnbdN98g/
项目好像有些问题 子模块还在使用.NET 5导致编译失败 报错的输出在上面

**Comment by AigioL** [comment]
https://github.com/SteamTools-Team/ArchiSteamFarm/blob/main/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj#L101

TFM 为 net48 时才引用的，上面的 TFMs 中并没有 net48
https://github.com/SteamTools-Team/ArchiSteamFarm/blob/main/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj#L10

不过 HintPath 这个应该可以删掉

唯一的错误可能是这个，应该是 sdk 的 bug
```
/home/???/dotnet/sdk/6.0.100-preview.5.21302.13/Microsoft.Common.CurrentVersion.targets(1717,5): error : 项目“../../references/ArchiSteamFarm/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj”指向“net5.0”。它不能被指向“.NETStandard,Version=v2.1”的项目引用。 [/media/???/???/GitLib/SteamTools/src/ST.Client/ST.Client.csproj]   
```

**Comment by AigioL** [comment]
在 Windows 上通过 Visual Studio 发布是能成功的

[linux-x64.7z.zip](https://github.com/SteamTools-Team/SteamTools/files/6780857/linux-x64.7z.zip)
文件格式是7z，github 只能上传 zip 后缀

目前 Linux 平台上还有很多未实现的平台内容，导致目前很多功能不可用
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/Services/IDesktopPlatformService.cs
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop.Windows/Services/Implementation/WindowsDesktopPlatformServiceImpl.cs
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop.Linux/Services/Implementation/LinuxDesktopPlatformServiceImpl.cs

**Comment by rmbadmin** [comment]
Linux版本目前已发布
