### ISSUE TITLE
🧐[Question] 是否有上架Win11商店的计划

### ISSUE THREAD

**Issue by zhanghua000** [SteamTools-Team/SteamTools#326]
### 🧐 问题描述(Description)
目前微软Win11商店已经可以上架传统Win32应用，个人觉得这样上架了也许可以方便下载分发？如果现在没有计划的话，若Win11发布正式版之后是否有相应计划？

**Comment by AigioL** [comment]
实际上是可以通过桌面桥上 应用商店的 最低需要 Win10 1809/17763，但是因为我们项目有多个独立的exe，桥接项目的支持与案例较少，没整成功，所以也没能发布。

ST.Client.Desktop.Avalonia.App.Bridge.Package

**Comment by zhanghua000** [comment]
了解了，感谢dalao解释
