### ISSUE TITLE
🐛[BUG] 令牌顺序不能调整 那个上移  下移调整的一塌糊涂啊

### ISSUE THREAD

**Issue by gdf159159** [SteamTools-Team/SteamTools#329]
令牌顺序不能调整 那个上移  下移调整的一塌糊涂啊

点上移没有反应  刷新之后前移一格  

在点上移  刷新 之后又回去了

**Comment by AigioL** [comment]
上下移的功能还没做好，之前忘记屏蔽就发布了。

预计于下个版本中修复

**Comment by AigioL** [comment]
2.4.9 已发布
