### ISSUE TITLE
👑[Enhancement] 建议不要将host文件全部重写

### ISSUE THREAD

**Issue by Elflare** [SteamTools-Team/SteamTools#330]
### 🥰 需求描述(Description)

这个软件直接将host文件全部覆盖了, 我里面还有很多其他host配置全部没了

### 🧐 解决方案(Solution)

建议在host文件后面添加而不是整个覆盖

**Comment by AigioL** [comment]
目前版本没有并没有覆盖已有的 hosts 纪录，你用的哪个版本？

如果确定目前最新版本还有覆盖的问题，可以吧原 hosts 文件上传上来。

ST.Client.UnitTest 单元测试可以跑一下

**Comment by Elflare** [comment]
> 目前版本没有并没有覆盖已有的 hosts 纪录，你用的哪个版本？
> 
> 如果确定目前最新版本还有覆盖的问题，可以吧原 hosts 文件上传上来。
> 
> ST.Client.UnitTest 单元测试可以跑一下

今天测试没问题了, 可能是我自己的问题
