### ISSUE TITLE
👑[Enhancement] 希望能访问google搜索

### ISSUE THREAD

**Issue by SnowMeteors** [SteamTools-Team/SteamTools#331]
### 🚑 其他信息(Other Information)

本人重度依赖google搜索，特别是在搜索关于技术方面的问题时，百度搜出来的答案简直浪费我时间。请求能访问google搜索，在此感谢

**Comment by AigioL** [comment]
本地反代的实现原理不能实现像 Google 这类的加速，所以没办法做，建议使用 cn.bing.com 代替或者买个香港服务器自用。
