### ISSUE TITLE
🐛[BUG] 本地令牌确认交易，一直显示“正在登陆中”

### ISSUE THREAD

**Issue by lb-fes** [SteamTools-Team/SteamTools#332]
本地令牌确认交易，输入账号密码后一直显示“正在登陆中”
- 程序版本(Program Version):2.4.1

**Comment by lb-fes** [comment]
开了社区加速再登录的

**Comment by lb-fes** [comment]
关掉steam++和steam客户端，过了几分钟，重新打开steam++，没打开steam客户端，又可以登录了。。。

**Comment by rmbadmin** [comment]
问题已经发现，将在下个版本修复。
