### ISSUE TITLE
👑[Enhancement] 希望能直接右键托盘图标复制令牌

### ISSUE THREAD

**Issue by Mr54233** [SteamTools-Team/SteamTools#334]
### 🥰 需求描述(Description)

能否在托盘的小图标上加入一个直接复制令牌的选项
### 🧐 解决方案(Solution)

![image](https://user-images.githubusercontent.com/46802509/124857532-0afd3700-dfdf-11eb-8e56-20ff17158db3.png)
我jio的可以这样做

**Comment by Mr54233** [comment]
或者也可以直接把本地令牌换成账号1和账号2，再减少一步操作
![image](https://user-images.githubusercontent.com/46802509/124857896-aee6e280-dfdf-11eb-8e08-8c3bef6afd61.png)

**Comment by rmbadmin** [comment]
谢谢，很好的建议，之后有时间会按照展开二级菜单的方式来做，顺便账号切换和本地令牌都可以这么做。

**Comment by rmbadmin** [comment]
2.4.12已经支持此功能
