### ISSUE TITLE
🐛[BUG] 开机自启动失效

### ISSUE THREAD

**Issue by yanxiatao** [SteamTools-Team/SteamTools#336]
### 🐛 描述(Description)

在设置启用开机自启动失效，开机时没有自启
### 📷 复现步骤(Steps to Reproduce)

1. 在设置启用开机自启动，启动时最小化到，启动时自动检查更新。
2. 
3. 

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.4.1
- 系统版本号(OS Version):  Windows 10.19042.985

**Comment by AigioL** [comment]
Duplicate of #308

**Comment by huntersxy** [comment]
我也是 win11 和win10最新版 都是如此

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
