### ISSUE TITLE
steam++貌似会让我win11蓝屏(其实是绿屏)崩溃🧐[Question] 

### ISSUE THREAD

**Issue by EasyRain** [SteamTools-Team/SteamTools#339]
我更新win11之后每次开机都得绿屏死几次机才能开，现在受不了了就去拿windows生成的蓝屏dmp文件拿去分析，虽然通篇下了看得我一脸懵逼，但是最后面看到了steam++.exe这个字眼。
![image](https://user-images.githubusercontent.com/46843500/125614119-c0877a16-38ec-4ab1-bf4a-f7ad9f0dba25.png)

**Comment by EasyRain** [comment]
需要的话我可以提供dmp文件

**Comment by rmbadmin** [comment]
目前经过反馈确实是会在win11上蓝屏，但是因为我们这边并没有人使用windows11开发所以暂时没有去寻找原因。
因为暂时嫌装win11进行开发调试很麻烦，所以可能要一段时间之后才会尝试解决win11上面出现的问题。

**Comment by EasyRain** [comment]
> 没有经过反馈确实会在win11上蓝屏，但是因为我们之前没有人使用windows11开发暂时没有去寻找原因。
> 因为暂时嫌装win11进行开发调试很麻烦，所以可能以后可能会遇到问题win11上面出现的问题。

可能是自启动的原因，毕竟系统启动后再开steam++是能正常使用的，我关掉开机启动试试，过两天来看看是不是自启动的原因

**Comment by EasyRain** [comment]
> 目前经过反馈确实是会在win11上蓝屏，但是因为我们这边并没有人使用windows11开发所以暂时没有去寻找原因。
> 因为暂时嫌装win11进行开发调试很麻烦，所以可能要一段时间之后才会尝试解决win11上面出现的问题。

破案了，就是自启动的原因，试了很多次，关了steam++的自启动win11开机就没有再绿屏过，因为登录账户进入系统后再启动是没问题的，可以试试把自启动设置在完全进入系统之后再运行

**Comment by AigioL** [comment]
目前 2.4.x 中 开机自启的任务计划触发器中条件为所有用户登录时，可能是这个原因引发的，比如 SYSTEM 用户登录时运行了可能导致了蓝屏，可以在 任务计划 中改为 **仅当前用户** 再试试。

**Comment by EasyRain** [comment]
> 目前 2.4.x 中 开机自启的任务计划触发器中条件为所有用户登录时，可能是这个原因引发的，比如 SYSTEM 用户登录时运行了可能导致了蓝屏，可以在 任务计划 中改为 **仅当前用户** 再试试。

不知道是什么原因设置当前用户登录时启动后，登录windows之后程序并没有运行，任务计划里面状态是准备就绪且无法手动运行，是还需要其他操作吗
![image](https://user-images.githubusercontent.com/46843500/125774413-d8831cfc-feb0-4bbf-a631-001931845731.png)
![image](https://user-images.githubusercontent.com/46843500/125774450-35cef1f9-ffe7-4fdc-910f-1f3da3643dc6.png)

**Comment by AigioL** [comment]
> > 目前 2.4.x 中 开机自启的任务计划触发器中条件为所有用户登录时，可能是这个原因引发的，比如 SYSTEM 用户登录时运行了可能导致了蓝屏，可以在 任务计划 中改为 **仅当前用户** 再试试。
> 
> 不知道是什么原因设置当前用户登录时启动后，登录windows之后程序并没有运行，任务计划里面状态是准备就绪且无法手动运行，是还需要其他操作吗
> ![image](https://user-images.githubusercontent.com/46843500/125774413-d8831cfc-feb0-4bbf-a631-001931845731.png)
> ![image](https://user-images.githubusercontent.com/46843500/125774450-35cef1f9-ffe7-4fdc-910f-1f3da3643dc6.png)

没有其他操作了，没有运行也有可能是运行中闪退了或者其他未知原因。

**Comment by EasyRain** [comment]
> > > 目前 2.4.x 中 开机自启的任务计划触发器中条件为所有用户登录时，可能是这个原因引发的，比如 SYSTEM 用户登录时运行了可能导致了蓝屏，可以在 任务计划 中改为 **仅当前用户** 再试试。
> > 
> > 
> > 不知道是什么原因设置当前用户登录时启动后，登录windows之后程序并没有运行，任务计划里面状态是准备就绪且无法手动运行，是还需要其他操作吗
> > ![image](https://user-images.githubusercontent.com/46843500/125774413-d8831cfc-feb0-4bbf-a631-001931845731.png)
> > ![image](https://user-images.githubusercontent.com/46843500/125774450-35cef1f9-ffe7-4fdc-910f-1f3da3643dc6.png)
> 
> 没有其他操作了，没有运行也有可能是运行中闪退了或者其他未知原因。

直接启动exe倒是啥事没有，就是任务计划不能正常启动

**Comment by YogurtZebra** [comment]
我也是win11，没有这种问题，但是无法开机启动

**Comment by GamerNoTitle** [comment]
其实可以丢到自启动文件夹里面，按Win+R然后输入shell:startup，丢个快捷方式进去就好了

**Comment by shenyefan** [comment]
## 我也是win11，但是启动就会绿屏，用疑难解答之后依旧绿屏
<img width="1280" alt="屏幕截图 2021-08-03 103709" src="https://user-images.githubusercontent.com/33883543/127949206-1a61ab6d-f062-4287-a2f7-fadc3e667e44.png">

**Comment by shenyefan** [comment]
## 绿屏文件~
[080221-12375-01.zip](https://github.com/SteamTools-Team/SteamTools/files/6920689/080221-12375-01.zip)

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
