### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by li1251460882** [SteamTools-Team/SteamTools#341]
![BUG](https://user-images.githubusercontent.com/58551694/125779524-cee71bfe-7bec-4cc2-b762-e9a55f9fa2db.png)

无法完全显示名称   我在Steam名字后边备注的  四海兄弟 鬼谷八荒  没法玩全显示

**Comment by rmbadmin** [comment]
问题应该在2.4.11中解决。
