### ISSUE TITLE
🐛[错误]

### ISSUE THREAD

**Issue by Nonexistent01** [SteamTools-Team/SteamTools#343]
### 🐛 描述(Description)

<!-
详细地描述 bug，让大家都能理解

在开机后的第一次打开（不论开机多久）出现了软件空白页面的情况，然后等待一会就会闪退，具体触发方法未知，本地网络状况良好
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version):  19042.1110

### 🖼 截图(Screenshots)
![B9L5MI 1K6) IE2H6~O`}B5](https://user-images.githubusercontent.com/87530864/125949784-c2d98b2d-40ef-440b-a8a3-670918880845.png)

**Comment by rmbadmin** [comment]
这个问题将会在下个版本修复，目前你可以通过删除appdata文件夹下的config.mpo文件来重置配置恢复

**Comment by rmbadmin** [comment]
问题应该已经在2.4.11中解决
