### ISSUE TITLE
🐛[BUG] 点击"账号切换"程序闪退

### ISSUE THREAD

**Issue by zhzipu** [SteamTools-Team/SteamTools#344]
### 🐛 描述(Description)

点击左侧"账号切换"程序崩溃退出

### 📷 复现步骤(Steps to Reproduce)

最近使用账号切换功能时,程序会崩溃退出,即使重新安装steam++也无效

### 📄 [异常/日志]信息([Exception/Log] Information)
无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version):  Windows 10.19042.1110

### 🖼 截图(Screenshots)

![steam++闪退](https://user-images.githubusercontent.com/34237543/125975157-e81a6ce5-3513-4303-aa04-83b40499117d.gif)

**Comment by rmbadmin** [comment]
程序目录下logs文件夹有生成日志吗？

**Comment by zhzipu** [comment]
[nlog-all-2021-07-17.log](https://github.com/SteamTools-Team/SteamTools/files/6834860/nlog-all-2021-07-17.log)

**Comment by zhzipu** [comment]
[nlog-all-2021-07-17.log](https://github.com/SteamTools-Team/SteamTools/files/6834862/nlog-all-2021-07-17.log)

**Comment by zhzipu** [comment]
> 程序目录下logs文件夹有生成日志吗？

[nlog-all-2021-07-17.log](https://github.com/SteamTools-Team/SteamTools/files/6834865/nlog-all-2021-07-17.log)

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
