### ISSUE TITLE
🧐[Question] edge的联网问题

### ISSUE THREAD

**Issue by Qi-Hei0** [SteamTools-Team/SteamTools#345]
### 🧐 问题描述(Description)

一次异常退出后就只有edge浏览器出现代理服务器出现问题，并且只有加速后才可以正常使用
下方的三个都使用过，没用还是依旧是这样
### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/82273345/126034457-030eb5b9-dc29-45d9-a332-ad754cf5f132.png)
![image](https://user-images.githubusercontent.com/82273345/126034522-920a3a20-c291-4eba-8b0e-71ae016bc138.png)
![image](https://user-images.githubusercontent.com/82273345/126034570-300b035a-6bdd-451b-b996-ac81491b737d.png)
![image](https://user-images.githubusercontent.com/82273345/126034584-2ca6ced9-5cf2-4749-bed4-3297d7d6fae6.png)
![image](https://user-images.githubusercontent.com/82273345/126034599-ae6182fd-4c3f-4ce2-8a6d-6aeec220848a.png)

**Comment by rmbadmin** [comment]
这很奇怪，edge本身并没有使用代理服务器的功能，
使用的就是系统代理，我也不确定什么原因造成的，
尝试重启重置winsock后重启电脑？

我还是推荐使用hosts模式，这比windows代理模式更好。

**Comment by Qi-Hei0** [comment]
hosts模式我用不了，说443端口被占用
重启重置winsock试过了没用

**Comment by Qi-Hei0** [comment]
好了好了，之前重置过都没用的啊，刚才又重置了一下就可以了

**Comment by rmbadmin** [comment]
> hosts模式我用不了，说443端口被占用
> 重启重置winsock试过了没用

443被占用只要找到占用443端口的程序结束掉就行了，如果是VMware，可以在设置内更改一下端口号

**Comment by Qi-Hei0** [comment]
多谢，原来是VMware占用的443端口啊
