### ISSUE TITLE
🐛[BUG] 怎么样都-404无法登录账户

### ISSUE THREAD

**Issue by CHNVIP** [SteamTools-Team/SteamTools#347]
### 📷 复现步骤(Steps to Reproduce)
头像-steam登录-快速登录-获取登录状态失败-404-手动登录-提示检查社区代理（账户登陆成功，程序未登陆成功）-反复

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.1
- 系统版本号(OS Version):

**Comment by CHNVIP** [comment]
晕了，描述怎么丢失了。。。。。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
