### ISSUE TITLE
🐛[BUG] 内存溢出

### ISSUE THREAD

**Issue by huoyan1231** [SteamTools-Team/SteamTools#348]
### 🐛 描述(Description)
内存溢出

### 📷 复现步骤(Steps to Reproduce)

打开stream++
等

### 🚑 基本信息(Basic Information)

steam++2.4.1
windows 10 21H1 19043.1110
### 🖼 截图(Screenshots)

![QQ图片20210719185837](https://user-images.githubusercontent.com/53113734/126150086-c50c38ab-6f98-4319-9b60-41e4baf0ab5d.png)

**Comment by rmbadmin** [comment]
程序目录logs文件夹是否有日志文件可以提供

**Comment by huoyan1231** [comment]
> 程序目录logs文件夹是否有日志文件可以提供

[nlog-all-2021-07-19.92.log](https://github.com/SteamTools-Team/SteamTools/files/6848521/nlog-all-2021-07-19.92.log)

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
