### ISSUE TITLE
steam启动变慢

### ISSUE THREAD

**Issue by Amadeuscx** [SteamTools-Team/SteamTools#350]
我没有一直开启steam++的习惯。只是去创意工坊时才用。使用过steam++后（再不开启sdeam++时）steam启动就特别慢（今天干脆半天后弹登录不上，但网页端正常），点击图标后半天才出正在登陆的窗口，但游戏启动正常。推测是steam++改hosts使客户端无法正常连接更新服务器。

**Comment by rmbadmin** [comment]
steam++关闭时是会还原hosts的，你也可以检查hosts来验证这个推测。

如果出现客户端登陆不上的情况，steam目录内logs文件夹下connection_log和bootstrap_log是会记录对应的情况的。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
