### ISSUE TITLE
🐛[BUG] 无法在社区留言

### ISSUE THREAD

**Issue by zhuangzihan666666** [SteamTools-Team/SteamTools#351]
🐛 描述(Description)
当开启Hosts反代模式加速并在社区发言时，steam会显示  “抱歉，发生了某种错误： 讨论区在您的地区不可用。”

📷 复现步骤(Steps to Reproduce)
开启steam后随便在社区找到一个可以发言的地方发言

🚑 基本信息(Basic Information)
steam++2.4.1
Windows 10 Version 20H2

🖼 截图(Screenshots)
![1NRERF%GT5CCXD`B0Q4S 8R](https://user-images.githubusercontent.com/79187727/126922462-9c8f31d6-1e30-419d-895e-2ce23c1539eb.png)
![J(E VM8J~{~O6_QICR6JX%8](https://user-images.githubusercontent.com/79187727/126922463-950e215f-0934-439d-89d1-2270c5680390.png)
![RGCJ}V989S%P1W$(VXAZD}N](https://user-images.githubusercontent.com/79187727/126922464-132f94da-e1bc-4ffe-95bc-b9120584598d.png)
使用其他加速器可以正常留言

**Comment by rmbadmin** [comment]
本地反代不会改变你的ip地址，国内ip无法使用留言和讨论是steam服务端的限制，所以光靠反代是无法解决此问题的。

**Comment by zhuangzihan666666** [comment]
ok谢谢
