### ISSUE TITLE
👑[Enhancement] 为什么不选择用注册表项来自启？

### ISSUE THREAD

**Issue by gili-gili** [SteamTools-Team/SteamTools#356]
系统Win10工作站版，无计划任务项，绿色和安装版都试了，就是没有
所以为啥不用注册表项？这样稳点啊

**Comment by rmbadmin** [comment]
注册表会导致每次开机弹出UAC提示框，
任务计划实在没有的话只能自己手动加一个了。

**Comment by gili-gili** [comment]
那就把UAC关了（
行吧

**Comment by gili-gili** [comment]
等下，有是有的，但是
![QQ截图20210730160019](https://user-images.githubusercontent.com/53759426/127621266-f349d83a-e402-474f-a954-29d9e34a573e.png)

**Comment by gili-gili** [comment]
没改位置

**Comment by rmbadmin** [comment]
> 那就把UAC关了（
> 行吧

并不是所有用户都会关闭UAC提示，一般来说也不推荐关闭。

**Comment by gili-gili** [comment]
好的，那我把issue关了？

**Comment by rmbadmin** [comment]
> 好的，那我把issue关了？

没有问题的话就可以关了，如果还有问题可以随时恢复。

**Comment by gili-gili** [comment]
OK，超级感谢大佬的工具:)
