### ISSUE TITLE
🐛[BUG] Steam++开启加速后挂后台会自动关闭软件

### ISSUE THREAD

**Issue by kEv1nZ0** [SteamTools-Team/SteamTools#358]
### 🐛 描述(Description)

开启社区加速后，挂在后台一段时间后会自动闪退，进程自己就消失了

### 📷 复现步骤(Steps to Reproduce)

1.开启社区加速，使用Hosts模式
2. 挂在后台或最小化一段时间后（大约1小时）软件会自动闪退

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-08-03.log](https://github.com/SteamTools-Team/SteamTools/files/6921482/nlog-all-2021-08-03.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.3.0
- 系统版本号(OS Version): 

Windows 10 20H2 19042.1110

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
