### ISSUE TITLE
👑[Enhancement]  内置网页翻译

### ISSUE THREAD

**Issue by YOULINLING** [SteamTools-Team/SteamTools#359]
### 🥰 需求描述(Description)
希望大佬们能添加一个给steam内置网页翻译的功能，对于英语不好的玩家来说，创意工坊里面的大片英语只能复制出去翻译，太麻烦了：-）

**Comment by AigioL** [comment]
有一个划词翻译脚本会在下一个版本发布时上线，大概就这两周会发新版本了。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
