### ISSUE TITLE
🧐[Question] Win7 上无法运行程序

### ISSUE THREAD

**Issue by FRQB** [SteamTools-Team/SteamTools#360]
### 🧐 问题描述(Description)

如图
### 🚑 其他信息(Other Information)

![搜狗截图20210807211236](https://user-images.githubusercontent.com/88584910/128601387-4ce09d50-08c5-4514-ba8b-564eb209a6b4.png)

**Comment by FRQB** [comment]
有什么办法解决吗

**Comment by FRQB** [comment]
打开文件夹里的Steam++.Win7 就弹出个错误

**Comment by AigioL** [comment]
使用的是那个版本的 Steam++？
可以右键文件 ```Steam++.exe``` 在详细信息里看到产品版本

可以尝试下载并安装
- 如果使用的是 2.3.x
  - [Microsoft Visual C++ 2015-2019 Redistributable 32 位](https://aka.ms/vs/16/release/vc_redist.x86.exe)
  - [KB3063858](https://www.microsoft.com/download/details.aspx?id=47409)
- 如果使用的是 2.4.x
  - [Microsoft Visual C++ 2015-2019 Redistributable 64 位](https://aka.ms/vs/16/release/vc_redist.x64.exe)
  - [KB3063858](https://www.microsoft.com/download/details.aspx?id=47442)

之后再打开 ```Steam++.exe``` 试试

**Comment by FRQB** [comment]
![20210807212546](https://user-images.githubusercontent.com/88584910/128601751-e951493f-d095-4a6e-a4c2-47126654214b.png)
网上的方法能试的都试了

**Comment by FRQB** [comment]
> 使用的是那个版本的 Steam++？
> 可以保存文件`Steam++.exe`在详细信息里看到的产品版本
> 
> 可以尝试下载并安装
> 
> * 如果使用的是 2.3.x
>   
>   * [Microsoft Visual C++ 2015-2019 Redistributable 32位](https://aka.ms/vs/16/release/vc_redist.x86.exe)
>   * [KB3063858](https://www.microsoft.com/download/details.aspx?id=47409)
> * 如果使用的是 2.4.x
>   
>   * [Microsoft Visual C++ 2015-2019 Redistributable 64位](https://aka.ms/vs/16/release/vc_redist.x64.exe)
>   * [KB3063858](https://www.microsoft.com/download/details.aspx?id=47442)
> 
> 以后再打开`Steam++.exe`操作系统

**Comment by FRQB** [comment]
![20210807213000](https://user-images.githubusercontent.com/88584910/128601886-a564f94b-495b-4188-a6dd-660284ea0a0f.png)
更新不适用

**Comment by AigioL** [comment]
> ![20210807213000](https://user-images.githubusercontent.com/88584910/128601886-a564f94b-495b-4188-a6dd-660284ea0a0f.png)
> 更新不适用

在计算机上右键属性，截图看一下版本信息

**Comment by FRQB** [comment]
![20210807214558](https://user-images.githubusercontent.com/88584910/128602303-a70ae77f-93aa-4a6e-ac9a-d22005321ff1.png)

**Comment by AigioL** [comment]
需要安装 Service Pack 1 补丁包，可以按下面的文档中操作
https://support.microsoft.com/zh-cn/windows/%E5%AE%89%E8%A3%85-windows-7-service-pack-1-sp1-b3da2c0f-cdb6-0572-8596-bab972897f61

**Comment by AigioL** [comment]
> 需要安装 Service Pack 1 补丁包，可以按下面的文档中操作
> https://support.microsoft.com/zh-cn/windows/%E5%AE%89%E8%A3%85-windows-7-service-pack-1-sp1-b3da2c0f-cdb6-0572-8596-bab972897f61

这文档里链接都失效了，官方渠道也下不到 SP1 升级包了，补丁大概是 KB976932，看一下其他途径能否下载到，或者装 win7sp1 版的系统，或升级到更高版本的系统，毕竟 **[对 Windows 7 的支持已于 2020 年 1 月 14 日结束](https://support.microsoft.com/zh-cn/windows/windows-7-%E6%94%AF%E6%8C%81%E4%BA%8E-2020-%E5%B9%B4-1-%E6%9C%88-14-%E6%97%A5%E7%BB%88%E6%AD%A2-b75d4580-2cc7-895a-2c9c-1466d9a53962)**

**Comment by AigioL** [comment]
有一些系统原版镜像iso的资源，可以用迅雷或者其他软件下载
- Windows 7 Ultimate with Service Pack 1 (x64) - DVD (Chinese-Simplified)

| 文件名  | cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso |
|  ----  |  ----  |
| SHA1  | 2CE0B2DB34D76ED3F697CE148CB7594432405E23 |
| 文件大小  | 3.19GB |
| 发布时间  | 2011-05-12 |
| 下载地址  | ed2k://|file|cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso|3420557312|B58548681854236C7939003B583A8078|/ |

- Windows 10 (business edition), version 21H1 (updated Jul 2021) (x64) - DVD (Chinese-Simplified)

| 文件名  | zh-cn_windows_10_business_editions_version_21h1_updated_jul_2021_x64_dvd_f49026f5.iso |
|  ----  |  ----  |
| MD5  | B1AE323962A6ED10D0447091A8A26C69 |
| SHA1  | BD964057E812C20E821D5B4DD034B59AFC495C09 |
| SHA256  | 8E786E7CE9483528A50E748CC3AC21447D1E17DECC794B7ACD7B406EA679A1A2 |
| 文件大小  | 5.29GB |
| 发布时间  | 2021-07-22 |
| 下载地址(ED2K)  | ed2k://|file|zh-cn_windows_10_business_editions_version_21h1_updated_jul_2021_x64_dvd_f49026f5.iso|5682900992|D68E08920C0BD9295B8CA31FF72F1308|/ |
| 下载地址(BT)  | magnet:?xt=urn:btih:AB78595A7854DCF9E270C877DD6D94019B3360F6&dn=zh-cn_windows_10_business_editions_version_21h1_updated_jul_2021_x64_dvd_f49026f5.iso&xl=5682900992 |

**Comment by AigioL** [comment]
有一些系统原版镜像iso的资源，可以用迅雷或者其他软件下载
- Windows 7 Ultimate with Service Pack 1 (x64) - DVD (Chinese-Simplified)

| 文件名  | cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso |
|  ----  |  ----  |
| SHA1  | 2CE0B2DB34D76ED3F697CE148CB7594432405E23 |
| 文件大小  | 3.19GB |
| 发布时间  | 2011-05-12 |
| 下载地址  | ed2k://|file|cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso|3420557312|B58548681854236C7939003B583A8078|/ |

- Windows 10 (business edition), version 21H1 (updated Jul 2021) (x64) - DVD (Chinese-Simplified)

| 文件名  | zh-cn_windows_10_business_editions_version_21h1_updated_jul_2021_x64_dvd_f49026f5.iso |
|  ----  |  ----  |
| MD5  | B1AE323962A6ED10D0447091A8A26C69 |
| SHA1  | BD964057E812C20E821D5B4DD034B59AFC495C09 |
| SHA256  | 8E786E7CE9483528A50E748CC3AC21447D1E17DECC794B7ACD7B406EA679A1A2 |
| 文件大小  | 5.29GB |
| 发布时间  | 2021-07-22 |
| 下载地址(ED2K)  | ed2k://|file|zh-cn_windows_10_business_editions_version_21h1_updated_jul_2021_x64_dvd_f49026f5.iso|5682900992|D68E08920C0BD9295B8CA31FF72F1308|/ |
| 下载地址(BT)  | magnet:?xt=urn:btih:AB78595A7854DCF9E270C877DD6D94019B3360F6&dn=zh-cn_windows_10_business_editions_version_21h1_updated_jul_2021_x64_dvd_f49026f5.iso&xl=5682900992 |

**Comment by FRQB** [comment]
![20210807224723](https://user-images.githubusercontent.com/88584910/128604096-f350e3c1-a56f-4006-aeaa-b306c1440ec0.png)
没能解决

**Comment by FRQB** [comment]
真的得上win10吗？我的洋垃圾pc用win10各种问题

**Comment by AigioL** [comment]
> 真的得上win10吗？我的洋垃圾pc用win10各种问题

倒是不至于一定得 10
我在虚拟机上是可以跑的
你可以确认下这张截图里的东西，是不是有遗漏的？

![Windows 7 x64-2021-08-07-22-52-40](https://user-images.githubusercontent.com/24450093/128604279-eb70bf62-727e-4f40-a3d3-106473399a21.png)

**Comment by FRQB** [comment]
我重装一下你给的系统吧

**Comment by FRQB** [comment]
能用了 感谢
