### ISSUE TITLE
🧐[Question] 关于代理设置的问题

### ISSUE THREAD

**Issue by idontwashmyhair** [SteamTools-Team/SteamTools#361]
### 🧐 问题描述(Description)
不知道算不算bug，特意注册来反馈一下

目前使用中遇到的唯一一个问题，就是Steam++会接管（？）我电脑的代理地址的问题，我使用的vpn是直接在“Internet 选项”→“连接”选项卡→局域网设置 中填写pac地址的，但是使用过Steam++的加速功能后，“局域网设置”的选项会直接灰掉，显示由管理员管理，并且在win10设置→代理设置 中的脚本被固定无法修改，导致我只能用openVPN魔法上网，平添了很多步骤……不知道后续的版本会不会避免掉这个问题
### 🚑 其他信息(Other Information)

![1628634773(1)](https://user-images.githubusercontent.com/88749413/128943460-2d1e121d-8e90-472e-89cf-74a2a3a80af6.png)
![1628634793(1)](https://user-images.githubusercontent.com/88749413/128943466-427c8c88-1434-424c-8a1e-01638332550c.jpg)

**Comment by rmbadmin** [comment]
你使用的是steam++的系统代理模式吗？

**Comment by idontwashmyhair** [comment]
> 你使用的是steam++的系统代理模式吗？

不是，就是hosts代理模式

**Comment by rmbadmin** [comment]
v2.4.12更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)
