### ISSUE TITLE
🐛[BUG] hosts文件中含GB2312编码字符时有乱码问题

### ISSUE THREAD

**Issue by Nepartak** [SteamTools-Team/SteamTools#362]
### 🐛 描述(Description)

我的hosts文件内原本含有一些其他应用生成的GB2312编码的中文注释，使用Steam++的一键加速功能后hosts文件会出现锟斤拷乱码。只是一个小问题，也没有带来实质困扰，维持现状也没什么影响，但如果能相应优化一下就更好了。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.3.0
- 系统版本号(OS Version): Windows 10.19043.1165

**Comment by AigioL** [comment]
保存文件使用的 [File.WriteAllText](https://docs.microsoft.com/zh-cn/dotnet/api/system.io.file.writealltext?view=net-5.0#System_IO_File_WriteAllText_System_String_System_String_) 没有指定编码，应该是使用的 [Encoding.Default](https://docs.microsoft.com/zh-cn/dotnet/api/system.text.encoding.default?view=net-5.0)
这个在 .net 6 上应该是 utf-8 无 bom
https://github.com/SteamTools-Team/SteamTools/blob/develop/src/ST.Client.Desktop/Services/Implementation/HostsFileServiceImpl.cs#L448

没什么好办法判断文件之前是什么编码的，要能判断文件编码才能改成调用 [WriteAllText(String, String, Encoding)](https://docs.microsoft.com/zh-cn/dotnet/api/system.io.file.writealltext?view=net-5.0#System_IO_File_WriteAllText_System_String_System_String_System_Text_Encoding_)

**Comment by Nepartak** [comment]
我使用另一款应用的频率很低，所以我手动转一下编码就好了。谢谢回复。
