### ISSUE TITLE
历史最低价格查询脚本失效🐛[BUG] 

### ISSUE THREAD

**Issue by frankjoe7** [SteamTools-Team/SteamTools#363]
### 🐛 描述(Description)
进入游戏商店界面后，价格下方显示正在读取历史最低价格然后这几个字就消失了就没有下文了。刷新以后还是这样

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):

**Comment by frankjoe7** [comment]
![image](https://user-images.githubusercontent.com/36319321/129133541-6b7856ae-7f2e-4e15-bbbb-03db8d302130.png)
![image](https://user-images.githubusercontent.com/36319321/129133546-6f5c7029-18b9-49ea-b63d-f25b222d3a13.png)

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
