### ISSUE TITLE
账号备注并不能成功保存🐛[BUG] 

### ISSUE THREAD

**Issue by Dioneason** [SteamTools-Team/SteamTools#364]
### 🐛 描述(Description)

就是给账号备注的时候你退出去了，重启软件，备注无了

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):

**Comment by AigioL** [comment]
已经修复了，下个版本正在测试中，最近几天就可以发了。
