### ISSUE TITLE
👑[Enhancement] 

### ISSUE THREAD

**Issue by LISH-RES** [SteamTools-Team/SteamTools#367]
### 🥰 需求描述(Description)
Android版本启动速度优化，以及稳定性改进
Android版本启动速度缓慢，有些时间只是想看个令牌，结果甚至没有原本的steam客户端启动快，还有一些稳定性问题，比如我添加了令牌后，有概率直接卡死，添加成功后没有任何提示，我以为卡了，一直点，结果是返回首页后出现一堆令牌，令牌的载入速度很慢

**Comment by AigioL** [comment]
启动速度目前已经是优化到最快了，代码执行耗时大概耗时在 2~3秒，实际上因为其他原因导致整体时间比这个长。
相比其他 App 确实是启动很慢，后续会添加 [应用微件](https://developer.android.google.cn/guide/topics/appwidgets/overview?hl=zh-cn) 这种桌面小部件的方式来暂时缓解这个问题。
其他稳定性问题最近也在修复。
因为用了一些加密的算法存储令牌数据在本地，目前这些算法在 Android 平台上的实现，性能确实很拉，所以第一次加载很慢，也许之后换 .Net 6 会有所改进，目前确实没有很好的办法。

之前网盘的 apk 文件是比较早期的版本，传错了文件，那个版本启动时间更长，目前的发行版本是已经优化过一次的了。
