### ISSUE TITLE
Android 减少 Steam 换绑令牌冷却时长

### ISSUE THREAD

**Issue by gsuckerp** [SteamTools-Team/SteamTools#368]
### 🥰 需求描述(Description)
steam换绑令牌可以只要3天cd

在目标设备的steam手机版登录，在令牌填写页面选择请求协助，再选使用此设备，可以将令牌换绑cd降至3天

**Comment by rmbadmin** [comment]
后续会在Discussions中归档一下教程类的问题，现在暂时关闭。
