### ISSUE TITLE
库存游戏列表找不到一些游戏

### ISSUE THREAD

**Issue by ad52825196** [SteamTools-Team/SteamTools#37]
目前主要通过库存游戏页面的解锁成就功能来模拟运行游戏，从而挂卡，但是发现库里的有些游戏在这个列表中并没有列出，无法搜索到，即便手动刷新了游戏列表缓存依然如此，但是在 Steam 徽章页面是有列出的。
例如：BlackSoul Extended Edition （ID: 264480）可能与该游戏已在 Steam 下架有关，商店页面不可用

**Comment by rmbadmin** [comment]
确实与游戏下架有关，
不过可以之后库存游戏列表支持手动添加对应appid的游戏

后续也会尝试添加一个从steam客户端缓存的数据来读取游戏列表的方式来解决这个问题

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。

**Comment by ad52825196** [comment]
确认在2.0.8版本中，下架游戏已经可以显示在列表里了，真棒
