### ISSUE TITLE
🐛[BUG] 加速页面文字重叠

### ISSUE THREAD

**Issue by Mr54233** [SteamTools-Team/SteamTools#370]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/46802509/129891639-c2485d73-1dde-45d0-9b78-263a638f9cce.png)

**Comment by SeasonG-CN** [comment]
**附议**

**Comment by AigioL** [comment]
当前最新版本 2.4.11 已修复。
