### ISSUE TITLE
🧐[Question] Arch Linux Startup Catch

### ISSUE THREAD

**Issue by RimuruW** [SteamTools-Team/SteamTools#371]
### 🧐 问题描述(Description)

项目 README、官网并未介绍 Linux 用户 release 下 Linux-x64 文件的使用方法，还请补充。

**Comment by AigioL** [comment]
Linux 上解压 7z 包后双击 Steam++ 就能启动了

https://user-images.githubusercontent.com/24450093/129894871-55e3ffef-4586-49be-8211-9fd89287048e.mp4

**Comment by RimuruW** [comment]
Arch Linux + GNOME 双击无响应，执行 ./Steam++ 执行报错如图所示
![图片](https://user-images.githubusercontent.com/59136309/129897405-13246467-c2e7-4d0e-bc36-fd24a54f8f44.png)

**Comment by RimuruW** [comment]
补一下错误输出
[Steam++_err_launch.log](https://github.com/SteamTools-Team/SteamTools/files/7007511/Steam%2B%2B_err_launch.log)

**Comment by AigioL** [comment]
看上去是字体管理初始化时默认字体为 null 引发的异常

https://github.com/AvaloniaUI/Avalonia/issues/4427
https://github.com/AvaloniaUI/Avalonia/issues/5774

可以试试 ```sudo apt-get install ttf-mscorefonts-installer```

**Comment by RimuruW** [comment]
Arch Linux 使用的是 Pacman, 不是 apt...
另外，建议 `打包` 或 `使用其他的开源字体` 而不是 Microsoft 的闭源字体。由于商业协议及其他原因，Linux 上使用这些闭源字体并不方便，而且不适合加入官方软件仓库和 AUR。

**Comment by rmbadmin** [comment]
实际上我们是没有打包任何MicroSoft的字体的，
这个错误来源于使用的UI框架 avalonia
不过看起来有办法修复它
