### ISSUE TITLE
🐛[BUG] Arch-Linux + kde 无法启动 

### ISSUE THREAD

**Issue by zhezhic** [SteamTools-Team/SteamTools#372]
### 🐛 描述(Description)
无法启动

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 📄 [异常/日志]信息([Exception/Log] Information)
Unhandled exception: System.Reflection.TargetInvocationException: Arg_TargetInvocationException
 ---> System.TypeInitializationException: TypeInitialization_Type, System.Application.UI.ViewModels.SettingsPageViewModel
 ---> System.InvalidOperationException: Default font family name can't be null or empty.
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):last
- 系统版本号(OS Version):

**Comment by AigioL** [comment]
Duplicate #371
可以试试 ```sudo apt-get install ttf-mscorefonts-installer```
