### ISSUE TITLE
🐛[BUG] Steam++ Android 6.0上显示logo后闪退

### ISSUE THREAD

**Issue by Raining-Studio** [SteamTools-Team/SteamTools#374]
### 🐛 描述(Description)

Steam++显示logo后闪退

### 📷 复现步骤(Steps to Reproduce)

1. 安装完软件（32位版）
2. 打开软件
3. 显示logo后闪退，清除数据也没用

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.5.0
- 系统版本号(OS Version): Android 6.0.1

**Comment by keria-minseok** [comment]
我的64位 之前也闪退 清缓存就好了

**Comment by Raining-Studio** [comment]
> 我的64位之前也闪退清了就好了

我都说过清过了。。。

**Comment by AigioL** [comment]
32位 64位切换安装有缓存应该不会有任何影响，可能用了什么高于 6.0 版本的 API 导致在低版本上闪退，之后排查一下。

**Comment by AigioL** [comment]
当前最新版本 2.4.11 已修复。
