### ISSUE TITLE
QQ无法在firefox上登录🐛[BUG] 

### ISSUE THREAD

**Issue by unx123475** [SteamTools-Team/SteamTools#382]
### 🐛 描述(Description)
试图用QQ登录steam++，跳转到firefox，选择QQ号，授权成功，进入加载状态，无法正常登录
如下图所示，一直处于加载状态

切换到edge浏览器秒登录成功

### 📷 复现步骤(Steps to Reproduce)
![image](https://user-images.githubusercontent.com/60565965/130018221-71397fa2-5b2c-4e89-9912-32e2130c6d0d.png)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.9
- 系统版本号(OS Version): win 10
-

**Comment by Mossimos** [comment]
更换其他库，下个版本正常登录。
