### ISSUE TITLE
Steam无法在firefox上登录🐛[BUG] 

### ISSUE THREAD

**Issue by EVAyo** [SteamTools-Team/SteamTools#384]
### 🐛 描述(Description)

试图用steam登录steam++，跳转到firefox，进入steamapi界面，授权成功，进入加载状态，无法正常登录，一直处于加载状态

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.9
- 系统版本号(OS Version): win10

**Comment by Mossimos** [comment]
测试是可以登录的啊，Firefox版本号提供下
![0Z4VG 8RDPGM}` NWB$D68A](https://user-images.githubusercontent.com/26396340/130188016-56dd21dd-e557-4782-99ee-91393d2cd3d0.png)

**Comment by Mossimos** [comment]
更换其他库，下个版本正常登录。
