### ISSUE TITLE
🧐[Question] 打開庫存顯示遊戲並非我所有 且已安裝版塊無顯示

### ISSUE THREAD

**Issue by CcIm1975** [SteamTools-Team/SteamTools#385]
### 🧐 问题描述(Description)

遊戲列表一刷新之後就不能再刷新 且遊戲庫不是我本身的遊戲庫 點開已安裝遊戲版塊說是沒有獲取到任何遊戲數據

**Comment by rmbadmin** [comment]
最新版已经修复此问题
