### ISSUE TITLE
安卓版闪退🐛[BUG] 

### ISSUE THREAD

**Issue by sdudfuhfgu** [SteamTools-Team/SteamTools#390]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![截屏_20210820_151610](https://user-images.githubusercontent.com/89243704/130195183-faa27f8a-5425-441e-97a3-5076eb86f0af.jpg)

**Comment by AigioL** [comment]
当前最新版本 2.4.11 已修复。
