### ISSUE TITLE
👑[Enhancement] 加速模式增加SOCKS5代理模式

### ISSUE THREAD

**Issue by cucengineer** [SteamTools-Team/SteamTools#391]
### 🥰 需求描述(Description)

1. Hosts代理模式虽然可以实现steam社区加速，但效果并不理想
2. 解决[steam++希望能与代理共存](https://github.com/SteamTools-Team/SteamTools/issues/255#issue-900197042)的问题
### 🧐 解决方案(Solution)

- steam++客户端增加**SOCKS5**代理模式选项
![image](https://user-images.githubusercontent.com/45850252/130197354-75897252-c2dd-4543-90d3-bf4740222226.png)
可以实现像IDM一样的**代理配置**
![image](https://user-images.githubusercontent.com/45850252/130197609-967633ee-b7b6-4c2e-9f02-f72a397c32fb.png)
- 用户可以对加速软件进行修改实现**个性化加速**，例如：
 1. 开启加速软件（SSR）的“直连模式”
 2. 开启加速软件的“选项设置”的“本地代理”
![image](https://user-images.githubusercontent.com/45850252/130198628-61506caa-8b8f-43fd-b90b-550b920746e3.png)

**Comment by rmbadmin** [comment]
v2.4.12更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)
