### ISSUE TITLE
🐛[BUG]  管理成就無法開啟

### ISSUE THREAD

**Issue by typs99765** [SteamTools-Team/SteamTools#393]
### 🐛 描述(Description)

**管理成就有些無法開啟，會卡在啟動中(已有打開商店頁面確認)，且有(卡住)或(無成就)都顯示 :啟動中，很難確認(SAM 7.0 使用正常)**

**QQ綁定(Chrome)昨天登入完 會卡住，今天可正常綁定**

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.4.9
- 系统版本号(OS Version): 
- **Windows 10 家用版-21H1 - Steam bete Update**

**Comment by rmbadmin** [comment]
程序目录下logs文件夹有日志吗，管理成就点击后观察下新的steam++进程是否有启动

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
