### ISSUE TITLE
🐛[BUG] macOS版本挂时长提示steam未启动

### ISSUE THREAD

**Issue by MerakW** [SteamTools-Team/SteamTools#395]
### 📷 复现步骤(Steps to Reproduce)

1. 使用挂时长工具
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):macOS 2.4.9 β
- 系统版本号(OS Version): macOS Monterey 12.0 Beta版(21A5304g)

**Comment by MerakW** [comment]
[![fjmNm4.png](https://z3.ax1x.com/2021/08/20/fjmNm4.png)](https://imgtu.com/i/fjmNm4)

**Comment by Mossimos** [comment]
MacOS下这个挂时长是无法使用的忘记屏蔽了
得等后面ASF方式挂机
