### ISSUE TITLE
🐛[BUG] 快速登录websocket连接丢失

### ISSUE THREAD

**Issue by 2957283601** [SteamTools-Team/SteamTools#396]
###  复现步骤(Steps to Reproduce)

1. 点击steam++登录
2. 使用steam登录
3. 跳出网页登录
4. 点击登录
5. 提示：错误!
与程序的连接丢失，点击重试或重新在程序内点击快速登录。
点击此处重试

###  基本信息(Basic Information)

- 程序版本(Program Version):2.4.9 for Windows (X64)
- 系统版本号(OS Version): Windows 10 专业版19043.1110

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/58629875/130260589-f90ffa4c-c228-472b-9510-88e6b9bf3db1.png)

**Comment by Mossimos** [comment]
已经更换方式且添加了手动输入登录token方式
