### ISSUE TITLE
🐛[BUG] 加速后显示重叠

### ISSUE THREAD

**Issue by Billchyi** [SteamTools-Team/SteamTools#398]
### 🐛 描述(Description)

一键加速后，加速时间和加速模式重叠，并且底下提示加速成功的字也消失了

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/62125888/130312064-eba413fb-7494-42f1-919e-2e17c88a7e02.png)

**Comment by rmbadmin** [comment]
重复 #386
