### ISSUE TITLE
🐛[BUG] v2.4.9 ui错位

### ISSUE THREAD

**Issue by Greenball233** [SteamTools-Team/SteamTools#399]
### 🐛 描述(Description)
2.4.1更新到2.4.9就出现了这个bug

### 📷 复现步骤(Steps to Reproduce)

1. 将2.4.1版本更新到2.4.9
2. 启动加速

### 🚑 基本信息(Basic Information)

- 屏幕分辨率&DPI: 1920*1080 125%
- 程序版本(Program Version): 2.4.9
- 系统版本号(OS Version): Windows 10.19042.1165

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/74454079/130312615-e997b07f-2166-4722-be47-5acaba942498.png)

**Comment by rmbadmin** [comment]
重复 #398 #386
