### ISSUE TITLE
🐛[BUG] steam++加速，自动启动steam提示服务器连接失败

### ISSUE THREAD

**Issue by sakuradrop** [SteamTools-Team/SteamTools#405]
###  描述(Description)

steam++软件启动加速，自动启动steam后，显示要我重新输入密码，输入正确密码和安全令后提示服务器连接失败，重新连接依旧无法连接服务器
重启steam后再次登录，输入正确密码后提示密码输入错误，之后重启电脑，重置网络，问题依旧存在

###  复现步骤(Steps to Reproduce)

1. 
2. 
3. 

###  基本信息(Basic Information)

- 程序版本(Program Version):2.4.9 for Windows (X64)
- 系统版本号(OS Version): Windows 10 家庭中文版 20H2 19042.1165

###  截图(Screenshots)

![steam](https://user-images.githubusercontent.com/89341878/130444842-84348dba-e09f-4b10-bee1-65fb68c8c518.png)
![steam 1](https://user-images.githubusercontent.com/89341878/130444883-234d27ce-d3fd-4b53-8eae-03d82cd3b7ab.png)

**Comment by rmbadmin** [comment]
1、检查C:\Windows\System32\drivers\etc\hosts文件是否还原。
2、检查系统设置-网络和Internet设置-代理-使用代理服务器开关是否关闭。
3、开始→运行→输入:CMD 点击确定(或按回车键),打开命令提示符窗口。
在命令提示符中输入:netsh winsock reset (按回车键执行命令)

**Comment by rmbadmin** [comment]
同时查看steam目录下的logs文件夹connection_log.txt文件，查找链接失败的原因

**Comment by sakuradrop** [comment]
重新安装了一下软件，现在好用了

**Comment by sakuradrop** [comment]
![图片](https://user-images.githubusercontent.com/89341878/131488792-3fd5545f-8a4c-4705-912c-bf6103aea026.png)
emmmmm，又出问题了

**Comment by rmbadmin** [comment]
> ![图片](https://user-images.githubusercontent.com/89341878/131488792-3fd5545f-8a4c-4705-912c-bf6103aea026.png)
> emmmmm，又出问题了

steam目录下的logs文件夹connection_log.txt文件
发上来好分析下原因,
以及按照我上面所说的执行修复网络的步骤之后在观察是否解决

**Comment by sakuradrop** [comment]
[connection_log.txt](https://github.com/SteamTools-Team/SteamTools/files/7083680/connection_log.txt)

**Comment by sakuradrop** [comment]
[hosts.txt](https://github.com/SteamTools-Team/SteamTools/files/7083698/hosts.txt)

**Comment by sakuradrop** [comment]
![图片](https://user-images.githubusercontent.com/89341878/131499139-35228119-3623-4ddb-b791-8bfe6470c82b.png)

**Comment by sakuradrop** [comment]
他现在是好的，当时我看这边无法连接服务器，上报完之后我把加速关掉登陆了两次steam，然后就能登上了

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
