### ISSUE TITLE
👑[Enhancement] 解锁成就界面请把隐藏游戏离得和管理成就远一点

### ISSUE THREAD

**Issue by Fruuuit** [SteamTools-Team/SteamTools#406]
### 🥰 需求描述(Description)

解锁成就界面，“隐藏游戏”和“管理成就”靠的太近，容易误点。

### 🚑 其他信息(Other Information)

![屏幕截图 2021-08-24 094743](https://user-images.githubusercontent.com/89231189/130542588-e3c18b69-f5b3-4e6f-ba91-a26eaa96a86a.png)

**Comment by AigioL** [comment]
当前最新版本 2.4.11 已改进。

**Comment by Fruuuit** [comment]
感谢感谢！大佬认真对待我的提案，感激不尽！另外问下团队怎么盈利？现在都找不到捐赠入口了。
