### ISSUE TITLE
🐛[BUG] 手机版staem++导入令牌后无反馈导致的重复令牌导入，以及令牌不应允许重复导入

### ISSUE THREAD

**Issue by Endermy** [SteamTools-Team/SteamTools#409]
### 🥰 需求描述(Description)

手机版steam++
导入令牌后并没有导入成功或者之类的提示
导致用户重复导入
同时，令牌拥有唯一性，不应该重复记录

### 🧐 解决方案(Solution)

在导入后增加'导入成功'的弹窗
检测steam ID， 不记录重复的令牌

**Comment by rmbadmin** [comment]
重复令牌是允许添加的，提示没有弹出来是弹提示这边有BUG，2.4.10版本发布会修复

**Comment by AigioL** [comment]
2.4.10 目前已经在 GitHub/Gitee 中发布，已可下载。

**Comment by rmbadmin** [comment]
关闭一些最新版可能已解决的历史问题，如果问题依然存在可自行恢复。
