### ISSUE TITLE
依然无法正常开机自启动！点《更新日志》闪退

### ISSUE THREAD

**Issue by heibaigame** [SteamTools-Team/SteamTools#41]
1、之前重新配置了配置文件，当时重启后正常启动，到今天电脑开机，发现自启动又失效了
2、手动打开提示新版本，然后更新，点击《更新日志》后软件崩溃退出
<a href="https://sm.ms/image/nqxuRHy6YkZjoN4" target="_blank"><img src="https://i.loli.net/2021/01/13/nqxuRHy6YkZjoN4.jpg" ></a>

**Comment by rmbadmin** [comment]
这个报错应该是升级的时候下载报的错，自动更新做的很仓促还没做好。
手动下载1.0.6在试一下吧

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
