### ISSUE TITLE
👑[Enhancement] 关于启动图的建议

### ISSUE THREAD

**Issue by Pcodcsja** [SteamTools-Team/SteamTools#415]
### 🥰 需求描述(Description)
在使用Android端最新版时，将应用设置成黑暗主题后启动图仍然是默认状态

### 🧐 解决方案(Solution）
可以将应用设置成启动图随应用主题变化而变化，或者新增一个选项使用户自行选择启动图是否跟随应用主题，或是一直保持默认/黑暗状态

### 🚑 其他信息(Other Information)
昨晚23：55受到了GitHub的邮件，说我提交的bug 已被修复…当时人都傻了💦💦💦还是希望开发者大大们多多休息，注意身体！♥️♥️♥️

**Comment by AigioL** [comment]
SplashActivity 在深色主题下背景是黑色的，在非深色主题下背景是白色的，不知道你用的是那个版本的 Android 系统。

深色主题是 Android 10 提供的，在低版本中也有一些厂商 ROM 实现了这个功能，在 MIUI 10 & Android 9 上测试是正常的。

![dark](https://user-images.githubusercontent.com/24450093/130720656-69dfcae0-caf0-4981-a01a-e0c68ff2c8fb.gif)

**Comment by Pcodcsja** [comment]
绷住了…我这个是安卓7.0…emui5.1.3😰😰😰

**Comment by rmbadmin** [comment]
低版本android暂无法实现
