### ISSUE TITLE
打开报错

### ISSUE THREAD

**Issue by Apricot-feiya** [SteamTools-Team/SteamTools#42]
从1.0.5就开始报错了= =1.0.4没有这个问题
![pic](https://user-images.githubusercontent.com/58616907/104410986-74f2d180-55a4-11eb-8c1c-3e5687d439d3.jpg)

Steam++ 1.0.6 Error
System.Exception: Could not install certificate as it is null or empty.
在Titanium.Web. Proxy.Network.CertificateManager.installCertificate(StoreName
storeName, StoreLocation storeLocation)
在
Titanium.Web. Proxy.Network.CertificateManager.TrustRootCertificate(Boolean
machineTrusted)
在Titanium.Web.Proxy.Network. CertificateManager.EnsureRooCertificate0
在SteamTool.Proxy.HttpProxy. SetupCertificate0
在SteamTool.Proxy.HttpProxy.StartProxy(Boolean IsProxyGOG)
在SteamTools.Services. ProxyService.set ProxyStatus(Boolean value)
在SteamTools.Services. ProxyService.Initialize0
在SteamTools.App.OnStartup(StartupEventArgs e)
在System.Windows. Application. <.ctor>b_ 1. 0(Object unused)
在System.Windows.Threading. ExceptionWrapper.InternalRealcall(Delegate
callback, Object args, Int32 numArgs)
在System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rmbadmin** [comment]
证书安装失败了，可以尝试手动安装一下程序根目录的pfx证书，安装到受信任的根证书位置，密码为空

**Comment by Apricot-feiya** [comment]
> 证书安装失败了，可以尝试手动安装一下程序根目录的pfx证书，安装到受信任的根证书位置，密码为空.
> 至于1.0.4没有问题，因为1.0.5改了生成证书的方式，可以尝试一下删除证书，然后删除程序路径下的pfx和cer文件，在重启程序安装下证书

根目录下没有证书

**Comment by rmbadmin** [comment]
那可以把1.0.4的证书文件复制到1.0.6目录下试试，同时可以尝试关掉自动启动代理服务程序应该不会在出现这个错误，然后在1.0.6里面启用日志，之后在安装证书，看看日志文件里有没有什么有用的错误日志反馈一下。

**Comment by Apricot-feiya** [comment]
> 那可以把1.0.4的证书文件复制到1.0.6目录下试试，同时可以尝试关掉自动启动代理服务程序应该不会在出现这个错误，然后在1.0.6里面启用日志，之后在安装证书，看看日志文件里有没有什么有用的错误日志反馈一下。

2021-01-13 14:48:03,850 ERROR >> System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 SteamTool.Core.HttpServices.<SendAsync>d__9.MoveNext()
2021-01-13 14:48:10,142 ERROR >> Steam++ Run Error : 

System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.Exception: Could not install certificate as it is null or empty.
   在 Titanium.Web.Proxy.Network.CertificateManager.installCertificate(StoreName storeName, StoreLocation storeLocation)
   在 Titanium.Web.Proxy.Network.CertificateManager.TrustRootCertificate(Boolean machineTrusted)
   在 Titanium.Web.Proxy.Network.CertificateManager.EnsureRootCertificate()
   在 SteamTool.Proxy.HttpProxy.SetupCertificate()
   在 SteamTools.ViewModels.CommunityProxyPageViewModel.SetupCertificate_OnClick()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Livet.Behaviors.MethodBinder.Invoke(Object targetObject, String methodName)
   在 Livet.Behaviors.LivetCallMethodAction.Invoke(Object parameter)
   在 Microsoft.Xaml.Behaviors.TriggerBase.InvokeActions(Object parameter)
   在 Microsoft.Xaml.Behaviors.EventTriggerBase.OnEvent(EventArgs eventArgs)
   在 Microsoft.Xaml.Behaviors.EventTriggerBase.OnEventImpl(Object sender, EventArgs eventArgs)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   在 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   在 System.Windows.Controls.Button.OnClick()
   在 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   在 System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   在 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   在 System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   在 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   在 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   在 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   在 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   在 System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   在 System.Windows.Input.InputManager.ProcessStagingArea()
   在 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   在 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   在 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   在 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
