### ISSUE TITLE
🐛[BUG] Linux 下hosts代理无法正常工作

### ISSUE THREAD

**Issue by Cai1Hsu** [SteamTools-Team/SteamTools#422]
### 🐛 描述(Description)

Linux 下hosts代理无法正常工作
我通过sudo启动Steam++后使用本地反代，然后尝试访问steam社区，但是无法打开。当我查看/etc/hosts时，我发现127.0.0.1 steamcommunity.com等类似的内容并没有被写入，于是我手动写入后重新访问steam社区，结果正常工作了。我已经给了Steam++ root权限，但hosts的内容未被写入，这似乎是程序没有定位到hosts文件。
### 📷 复现步骤(Steps to Reproduce)

1. sudo ./Steam++
2. 尝试访问steam社区  -> 打不开
3. 向 /etc/hosts 写入 127.0.0.1 steamcommunity.com 和 127.0.0.1 www.steamcommunity.com
4. 再次尝试访问steam社区  -> 打开

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.4.11
- 系统版本号(OS Version):  Pop os 21.04

### 🖼 截图(Screenshots)

![2021-08-25 22-57-29 的屏幕截图](https://user-images.githubusercontent.com/47081443/130815060-388ba253-a7b6-432b-9df4-5fd6f97064f2.png)
![2021-08-25 22-59-42 的屏幕截图](https://user-images.githubusercontent.com/47081443/130815093-af3d9b99-3d43-409e-9aed-00ed6e928bc0.png)

**Comment by rmbadmin** [comment]
在最新2.4.12，该问题应该已修复。
