### ISSUE TITLE
🧐[Question] 请问解锁成就的功能需要在这个程序里登陆 steam 帐号吗？

### ISSUE THREAD

**Issue by Cooky-12** [SteamTools-Team/SteamTools#427]
### 🧐 问题描述(Description)

只需要解锁成就的功能，其他的不是很需要

### 🚑 其他信息(Other Information)

另外点“管理成就”，显示“正在启动”然后就没动静了

Archlinux，Steam 已在运行

**Comment by rmbadmin** [comment]
linux和mac暂时没有做成就解锁的功能

目前只有windows支持

**Comment by Cooky-12** [comment]
> linux和mac暂时没有做成就解锁的功能
> 
> 目前只有windows支持

好的，谢谢，我开虚拟机试试
