### ISSUE TITLE
👑[Enhancement] 更简洁的游戏库存

### ISSUE THREAD

**Issue by 960012** [SteamTools-Team/SteamTools#430]
### 🥰 需求描述(Description)
更简洁的游戏库存 
建议steam++里的游戏库存可以像steam游戏库那样从游戏库中移除游戏，或者自动屏蔽已经从steam游戏库移除的游戏，因为我steam游戏库里只有67款游戏，而steam++游戏库里显示我有260款游戏，所以我建议减少steam++显示游戏库存的数量

**Comment by rmbadmin** [comment]
下个版本开始在steam启动时不会有这么多游戏了，
目前是因为完全加载了整个steam缓存的游戏.

移除游戏就是右键游戏封面之后的隐藏游戏，你可以隐藏不想看到的游戏
