### ISSUE TITLE
🐛[BUG] 加速功能代理的Http状态错误时会导致内存溢出

### ISSUE THREAD

**Issue by Mr54233** [SteamTools-Team/SteamTools#437]
### 🐛 描述(Description)

内存溢出，直接吃掉一条内存
### 📷 复现步骤(Steps to Reproduce)

1. 未知步骤导致
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎8/‎9
操作系统内部版本	19043.1165
体验	Windows Feature Experience Pack 120.2212.3530.0

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/46802509/131768943-faa0008d-09ad-4ae8-ade9-625633acaa7b.png)

**Comment by rmbadmin** [comment]
麻烦说一下程序版本，和提交一下logs文件夹日志

**Comment by Mr54233** [comment]
> 麻烦说一下程序版本，和提交一下logs文件夹日志

2.4.9版本 
https://www.aliyundrive.com/s/YYUYiK4Shfo

**Comment by rmbadmin** [comment]
> > 麻烦说一下程序版本，和提交一下logs文件夹日志
> 
> 2.4.9版本
> https://www.aliyundrive.com/s/YYUYiK4Shfo

使用的是系统代理模式吗？
看日志是访问了某个http状态码不正常的地址，并且一直无限在重试连接。
不过日志没记录下到底是访问了什么地址造成的问题，所以暂不清楚具体原因。

**Comment by Mr54233** [comment]
> > > 麻烦说一下程序版本，和提交一下logs文件夹日志
> > 
> > 
> > 2.4.9版本
> > https://www.aliyundrive.com/s/YYUYiK4Shfo
> 
> 使用的是系统代理模式吗？
> 看日志是访问了某个http状态码不正常的地址，并且一直无限在重试连接。
> 不过日志没记录下到底是访问了什么地址造成的问题，所以暂不清楚具体原因。

不是，用的host，貌似是和魔法有冲突

**Comment by rmbadmin** [comment]
v2.4.12更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)
