### ISSUE TITLE
👑[Enhancement] 和壁纸引擎联动

### ISSUE THREAD

**Issue by zhanghua000** [SteamTools-Team/SteamTools#438]
### 🥰 需求描述(Description)
当存在壁纸引擎的时候将程序的背景图片同步为壁纸引擎的内容

### 🚑 其他信息(Other Information)
参考一个C#写出来的Minecraft启动器BakaXL：
![image](https://user-images.githubusercontent.com/17194552/131933747-32d8199f-c8ca-450c-bcbe-073f671cab41.png)
此时Wallpaper Engine的壁纸是Bilibili音频响应那张动态壁纸，被加上亚克力效果后作为BakaXL的背景

**Comment by rmbadmin** [comment]
我大概能想到思路做到，不过暂时先做功能性的更新了。
外观方面的改动暂时不整了。

**Comment by rmbadmin** [comment]
功能已经实现，但是因为使用的avalonia库目前在窗口透明上有BUG所以该功能暂时不可用。

**Comment by rmbadmin** [comment]
下个版本发布时上线该功能。

**Comment by TT702** [comment]
太荣幸了…
居然能看见BakaXL的某个小功能可以被用户喜爱并建议给其他软件实现…
我大受震撼…
