### ISSUE TITLE
Kubuntu 21.04 多种问题🐛[BUG] 

### ISSUE THREAD

**Issue by RainbowFunny826** [SteamTools-Team/SteamTools#439]
🐛 描述(Description)

普通用户bug
   无法使用任何代理模式
      无法启动Hosts代理
   点击编辑hosts文件无效果
root用户bug
   无法显示Steam信息
   Hosts加速不会往/etc/hosts写入重定向信息
   点击编辑hosts文件会用终端vim启动 而不是系统默认程序(Kate)
Hosts代理bug
   代理时会显示证书错误(即使已经把 ./AppData/SteamTools.Certificate.* 都复制到/usr/local/share/ca-certificates)
   浏览器添加证书也会显示证书错误
通用bug
   点击证书设置的任何子选项都无效果
   设置内通用设置 任何 (打开 * 文件夹) 都无效果
   系统代理模式无法使用
账户登录bug
   打开系统浏览器无用(KDE会显示启动浏览器 但是没结果)

📷 复现步骤(Steps to Reproduce)

普通用户启动方式
   双击Steam++(可执行文件)
root用户启动方式
   sudo ./Steam++

📄 [异常/日志]信息([Exception/Log] Information)
无异常日志

🚑 基本信息(Basic Information)

Steam++版本 : Alpha Version: 2.4.11 α for Linux (X64)
浏览器: Microsoft Edge Dev(93.0.933.1)
操作系统： Kubuntu 21.04
KDE Plasma 版本： 5.21.4
KDE 框架版本： 5.80.0
Qt 版本： 5.15.2
内核版本： 5.11.0-31-generic
操作系统类型： 64-位
图形平台： X11
处理器： 4 × Intel® Core™ i5-3317U CPU @ 1.70GHz
内存： 3.7 GiB 内存
图形处理器： Mesa DRI Intel® HD Graphics 4000

🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/53068513/131996114-35533d17-0d8a-4bfc-bf03-317e0781ceaf.png)

**Comment by Mossimos** [comment]
2.4.12应该已经都修复了,我这边都测试过了
![QQ截图20210911190807](https://user-images.githubusercontent.com/26396340/132945873-befd87dd-040c-4736-8791-d9437357cb6c.png)
