### ISSUE TITLE
🐛[BUG] win10版添加阿服的steam账号令牌，显示各种网络的异常。

### ISSUE THREAD

**Issue by Sunkentoko** [SteamTools-Team/SteamTools#440]
### 🐛 描述(Description)
添加阿服的steam账号令牌，显示各种网络的异常，详见截图。

今日7点左右，在win10版添加steam账号的令牌，已经启动了阿服的代理ip节点，并确认网络通畅。在软件内点击新增，登录后，提示网络异常，详见截图。初步认为不是代理节点的丢包问题，具体还需要大佬排查。
### 📷 复现步骤(Steps to Reproduce)
1、启动阿区的代理节点；2、启动steam++，且不启动steam++的网络加速；3、在本地令牌→点新增，在弹出的界面中填写阿区的账号密码。等待3-5秒，弹窗网络异常报错，详见截图。

1. 启动阿区的代理节点；
2. 启动steam++，且不启动steam++的网络加速；
3. 在本地令牌→点新增，在弹出的界面中填写阿区的账号密码。
4. 等待3-5秒，弹窗网络异常报错，详见截图。

### 📄 [异常/日志]信息([Exception/Log] Information)
详见截图
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.11 for Windows (X64)
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/51468471/132077202-c886ee17-f044-4403-b33a-e0639f046641.png)

**Comment by double0wind** [comment]
你好这个问题是怎么解决的呀
