### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by died23333** [SteamTools-Team/SteamTools#441]
### 🐛 描述(Description)

- 程序版本 2.4.11
- 系统版本号 Windows 10 20h2
 
游戏库中的游戏部分是之前游玩过deem一类的，但是steam++错误的把本体放入了游戏库
steam++长时间在后台会自动关闭自己

**Comment by rmbadmin** [comment]
更新最新的2.4.12，问题应该已经修复
