### ISSUE TITLE
🐛[BUG] 安卓版开屏暴击 提示错误 MIUI12.5

### ISSUE THREAD

**Issue by SEER232** [SteamTools-Team/SteamTools#447]
### 🐛 描述(Description)
安卓版开屏暴击 提示错误

### 📷 复现步骤(Steps to Reproduce)

1. 打开app
2. 看到提示
3. 完

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.5.0
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)
![b4498355b6a575b64ca9b671878aadb](https://user-images.githubusercontent.com/66045190/132313669-2de0fba6-e3ef-4349-a53c-98d73f76474f.jpg)

**Comment by AigioL** [comment]
这个客户端错误 1006 是因为无法联网

后面这个系统的弹窗是因为目前没上架小米应用商店，所以也没有经过应用商店的审核，没在他的白名单内自然就出现了这个

**Comment by SEER232** [comment]
ok
