### ISSUE TITLE
👑[Enhancement] 能否把linux版本中需要sudo权限的相关命令拆出来呢？

### ISSUE THREAD

**Issue by Neutron3529** [SteamTools-Team/SteamTools#449]
### 🥰 需求描述(Description)

在linux环境下，程序一般应该用普通权限运行。
运行root权限的程序相当危险（特别是这种可以下载js脚本并执行的程序）

比如，如果脚本服务器被黑，黑客往脚本服务器上放有害代码，程序本体有root权限基本上代表电脑沦陷

于是我想问一下，有没有什么以常规权限运行，在必要时候手动输入sudo命令的方法

（没记错gentoo可以没有sudo）

### 🧐 解决方案(Solution)

将一些涉及特权命令的代码（比如打开端口，修改/etc/hosts）改成命令行，而不是给程序设置suid（比如`sudo sed -i 's/127.0.0.1/127.0.0.1  steamcommunity.com/g' /etc/hosts`可以把 steamcommunity.com加入反代名单）

类似的，也可以在windows下如此操作

### 🚑 其他信息(Other Information)

除了改hosts之外，还有什么地方需要root权限吗？

**Comment by Mossimos** [comment]
无root 权限443端口无法监听。只能使用系统代理模式。
修改host 要么像 Mac那样每次输入密码执行替换。
另外脚本仅下载读取字符插入浏览器执行，如果浏览器没有sudo启动一般不会有这种情况。
都是用 link插入进去的

**Comment by Neutron3529** [comment]
@Mossimos 感谢回复，我不太熟悉linux的代理（如果熟悉，我大概就手写nginx反代配置文件了），稍微查看了一下，这些问题（大概）是有解决方案的

> 无root 权限443端口无法监听。
可以监听大于1000的端口，使用iptables或者ssh完成从443到监听端口的本地转发
用自己搭的overleaf测试了一下
```
ssh -L 8000:localhost:10086 overleaf@server -N
```
之后就可以使用localhost:8000访问服务器的overleaf服务
同时我尝试了同时转发和监听443端口，都没有报错（不知道为什么第一行必须sudo）
```
sudo ssh -L 443:localhost:8001 localhost -N -i ~/.ssh/id_ecdsa # 只执行这一条应该足够
ssh -L 8000:localhost:443 root@localhost -N # 我怕有其他需求，又加了这句话
```
（因为linux图形界面卡死过几次，我开启了sshd服务（用于手机ssh进来自救），这么做最多会因为没有配置好免密（谁会免密登录自己啊）而询问一次密码，在配置免密之后连输密码的工作都可以免了）

同时，我查到了这一条命令：
```
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8443
```

看上去在linux下的确可以以普通权限+root启动脚本/服务来完成相应工作。

> 修改host 要么像 Mac那样每次输入密码执行替换。

hosts可以借助vim之类的程序修改，只要知道怎么改大家都可以一次性改好，不必设置suid，更不必每次程序结束之后主动改回来（反正下次还要改……）

> 另外脚本仅下载读取字符插入浏览器执行，如果浏览器没有sudo启动一般不会有这种情况。

我比较害怕suid的问题，linux版本是设置了chmod 4755加上suid的，用这个suid，会视为以root身份运行，
我不确定程序有没有其他方法强制放弃root权限
（我只是害怕）

---

如果方便的话，可以把监听443端口改成监听任意端口，这样应当可以绕过必须root才能监听的限制。

带着suid的程序，我真的害怕出问题（一个使用带suid的`/usr/bin/find`提权的脚本如下）
```
cp /usr/bin/find . # 放到内存盘里面，用完就删！
sudo chown root:root ./find 
sudo chmod 4755 ./find
./find . -type f -name find -exec whoami \; # 显示root
touch bad_guy # 现在
./find . -type f -name bad_guy -exec chown root:root {} \;
./find . -type f -name bad_guy -exec chmod 4777 {} \; # 现在你已经可以为所欲为了……
sudo rm -rf find bad_guy # 请千万不要在/usr/bin目录下执行这句话
```
我就不卖弄改`/etc/sudoers`的脚本了……
应当注意的是，这里借助find执行的sleep（`./find . -type f -name find -exec /usr/bin/sleep 100 \;`）也是root（也就是，root带suid的程序打开的子程序都是root，而不是当前用户）
这可能导致严重漏洞（至少网上说得都很吓人）

**Comment by Mossimos** [comment]
新版本应该已经加过自定义端口监听了点击界面上的设置就行。(代理设置 本机监听ip-端口 【好像还没开放出来之后改下】)
修改host使用vim也需要sudo权限启动不然无法保存
改成mac那样弹出提示框自己动手复制命令去中断执行也可以。程序只有这2个地方需要root权限（root下托盘有BUG显示不了）

`同时我尝试了同时转发和监听443端口，都没有报错（不知道为什么第一行必须sudo）`
必须sudo就是因为无root权限无法更改这些相关的设置

`iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8443`
这些都必须sudo才能去执行 要么像mac那样操作弹窗让用户自己执行该命令或者输入密码程序写入 sh脚本执行 （ps：程序直接执行sudo指令都被被拦截之前尝试过 echo \"密码\" | sudo -S {脚本内容} 全都被拦截了）
![QQ截图20210913140954](https://user-images.githubusercontent.com/26396340/133032305-1c46cafa-d902-421a-aa23-1d5d69299c6b.png)

1.开发设置监听端口
2.修改host无root运行弹命令复制窗口
修改完这2个应该就可以在非root下运行了。

**Comment by Mossimos** [comment]
[https://pan.mossimo.net:5212/api/v3/file/get/2456/linux-x64.7z?sign=m4wh_4VMYqaoGmeR0hd-BmzttOsg3Y7Lq1ZvMfmZ1cw%3D%3A0](url)
可以在这里下载测试程序
我这iptables 映射一直不成功。
系统代理倒是能直接使用了

**Comment by Neutron3529** [comment]
感谢dalao！！！

0. `cat /proc/sys/net/ipv4/ip_forward`, 应该返回1，至少我在执行`sudo iptables`之前是这么做的。虽然之后改成了`0`之后代理仍然有效，因此我不确定修改这一点是否必要（理论上我应该重启电脑再试试，问题是电脑正在跑mprime，在内存里有7G左右的.residues文件不想来回复制于是不准备重启……）
1. 执行`sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443 ; sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -o lo -j REDIRECT --to-port 8443`，这两条命令是从`https://blog.frickjack.com/2012/01/iptables-nat-port-forward-443-https-to.html`找到的。
2. 测试https://steamcommunity.com/，至少我这里的连接是正常的

感谢dalao！！！

BTW，能在程序里检测hosts有没有被修改吗？
每次弹窗有点难受，如果程序在开启加速的时候使用ping检测地址是否指向127.0.0.1，大概可以免去每次弹窗的苦恼

以及，如果dalao需要的话，可以用这段脚本
```
[ "0$_STEAMPP_HTTPS_PORTS_" -le "1000" ] && export _STEAMPP_HTTPS_PORTS_=8443 # 读取环境变量，或者设置默认监听端口
echo "请输入管理员密码以启动端口转发，如果你已经设置端口转发请自行修改脚本取消这里的sudo"
sudo echo "密码验证完成"
echo "使用iptables进行端口映射"
sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443 && sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -o lo -j REDIRECT --to-port 8443 && echo "端口映射成功"
./Steam++ # 程序因此可以读取_STEAMPP_HTTPS_PORTS_进行端口映射
```

**Comment by Mossimos** [comment]
检测是可以检测的 Host读取是有权限的只是没有修改权限，这个版本也是临时改了测试下。后面会优化一下到2.5一起发布。
明天改个修改弹窗的先用着吧。
iptables  端口映射 我在  kubuntu-21.04-desktop-amd64
和 deepin-desktop-community-20.2.3-amd64 
这2个下都没效果 但是之前搜索的都只有1条，明天再试试你的这个脚本。

**Comment by Mossimos** [comment]
早上试了下确实没效果
`sudo sysctl -w net.ipv4.ip_forward=1`
`修改/etc/sysctl.conf 配置文件 而且 sysctl -p`
然后执行
`sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443 && sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -o lo -j REDIRECT --to-port 8443 && echo "端口映射成功"`
还是没效果

**Comment by Neutron3529** [comment]
我明天重启一下电脑再试试好了

现在CPU正在算mprime的PRP不方便重启
明天我大概也可以试试虚拟机能不能成。

（话说，有没有可能是虚拟机不支持端口映射的问题呢？）

对了，我用的系统是：
```
$ uname -a
Linux DR722 5.13.12-1-MANJARO #1 SMP PREEMPT Wed Aug 18 08:06:42 UTC 2021 x86_64 GNU/Linux
```

**Comment by Mossimos** [comment]
我这的版本好像都比你的低  （明天我也去实体机上试试） 这2个都是hyper建的虚拟机
![QQ图片20210915000633](https://user-images.githubusercontent.com/26396340/133293721-60c99d81-3376-4621-8063-d195a936d7e5.png)

**Comment by Neutron3529** [comment]
...出了点意外
不知道是哪里设置错了……现在我的manjaro刚刚重装完成

不过这样正好排除一切干扰进行端口转发测试：）

**Comment by Neutron3529** [comment]
实体机验证成功：
```
[neutron@DR722 me]$ sudo echo "密码验证完成"
[sudo] neutron 的密码：
密码验证完成
[neutron@DR722 me]$ sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443 && sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -o lo -j REDIRECT --to-port 8443 && echo "端口映射成功"
端口映射成功
[neutron@DR722 me]$ cd linux-x64/
[neutron@DR722 linux-x64]$ ./Steam++
bash: ./Steam++: 权限不够
[neutron@DR722 linux-x64]$ chmod +x ./Steam++
[neutron@DR722 linux-x64]$ ./Steam++ # 现在已经能用了
kf.coreaddons: no metadata found in "/usr/lib/qt/plugins/kf5/kio/desktop.so" "Failed to extract plugin meta data from '/usr/lib/qt/plugins/kf5/kio/desktop.so'"
kf.coreaddons: no metadata found in "/usr/lib/qt/plugins/kf5/kio/applications.so" "Failed to extract plugin meta data from '/usr/lib/qt/plugins/kf5/kio/applications.so'"
```

验证失败的原因可能是443端口被其他命令转发到了其他位置
比如之前我试过把`sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443 && sudo iptables -t nat -A OUTPUT -p tcp --dport 443 -o lo -j REDIRECT --to-port 8443 && echo "端口映射成功"`这里的8443改成8009
可能是因为我已经把443映射到了8443，这一条命令不报错，也不真正执行映射。
这直接导致第二次端口映射失败。
