### ISSUE TITLE
软件无法正常启动

### ISSUE THREAD

**Issue by j999yp** [SteamTools-Team/SteamTools#45]
中午还能正常使用，晚上就不行了，报错如图
![image](https://user-images.githubusercontent.com/38547892/104598273-55959a80-56b1-11eb-886e-78ab614996df.png)

**Comment by rmbadmin** [comment]
配置文件读取失败了，到 %HOMEPATH%\AppData\Local\rmbgame.net\Steam++路径下看看settings.json文件内容是否有问题，如果没有令牌重要数据担心的话，可以删除配置文件重置配置

**Comment by j999yp** [comment]
> 配置文件读取失败了，到 %HOMEPATH%\AppData\Local\rmbgame.net\Steam++路径下看看settings.json文件内容是否有问题，如果没有令牌重要数据担心的话，可以删除配置文件重置配置

只有一个settings.json.bak的备份文件，更改扩展名打开后发现是空文件；将整个配置文件夹删除后软件依然不能启动

**Comment by YogurtZebra** [comment]
Win7同样有问题，Win10还未测试
![image](https://user-images.githubusercontent.com/57581480/104709437-e758e280-5759-11eb-992f-e38aace80501.png)

**Comment by j999yp** [comment]
@rmbadmin 删除配置文件后重新打开软件并没有自动生成新的配置文件，报错依旧

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
