### ISSUE TITLE
🧐[Question] hosts代理出现问题

### ISSUE THREAD

**Issue by SnowMeteors** [SteamTools-Team/SteamTools#452]
### 🧐 问题描述(Description)

选择hosts代理模式，点击一键加速，出现提示加速服务启动失败，443端口被占用。
Steam++版本 2.4.12 for Windows(x64)

**Comment by rmbadmin** [comment]
找到占用443端口的程序结束掉就行了，
如果安装了 VMware 参考：https://steampp.net/faq#NoWork80443
