### ISSUE TITLE
🐛[BUG] Win11最新预览版任务栏中不显示Steam++图标

### ISSUE THREAD

**Issue by Nova-Noir** [SteamTools-Team/SteamTools#453]
### 🐛 描述(Description)

Win11最新预览版任务栏中不显示Steam++图标

### 📷 复现步骤(Steps to Reproduce)

1. 升级到Windows 11 22454.1000 rs_prerelease dev版本

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.4.12
- 系统版本号(OS Version): 
- Windows 11 22454.1000 rs_prerelease dev

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/68760718/133009814-04c21528-9ec6-4259-93e0-d84513f97734.png)

**Comment by Seaborn-Nova** [comment]
在某次重启后任务栏又出现了steam++的图标，其间未对任务栏进行任何改动，复现方法待测。

**Comment by AigioL** [comment]
当前 2.6.1 版本已修复。
