### ISSUE TITLE
🐛[BUG] steam++账号一键切换功能无法正常使用

### ISSUE THREAD

**Issue by A1Panda** [SteamTools-Team/SteamTools#457]
### 📷 复现步骤(Steps to Reproduce)

1. 打开steam++点击账号切换功能 
2. 在另一个帐号处点击一键登录steam后 
3. steam被重启但账号并不会被切换（还是之前的哪一个账号登录

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-09-13.log](https://github.com/SteamTools-Team/SteamTools/files/7155296/nlog-all-2021-09-13.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.4.12 β for Windows Desktop Bridge (X64)
- 系统版本号(OS Version):

**Comment by rmbadmin** [comment]
目前已发现问题，正在处理中

**Comment by Yangjam** [comment]
遇到了同样的问题。upw版

**Comment by RicardoScofileld** [comment]
同样的问题

**Comment by RicardoScofileld** [comment]
貌似是微软商店版的吧，之前的好像没这个问题

**Comment by rmbadmin** [comment]
微软商店版最新2.4.13版本应该已经修复
