### ISSUE TITLE
👑[Enhancement] 程序内所有窗口都能通过点击按钮打开好几个

### ISSUE THREAD

**Issue by huanfeiiiii** [SteamTools-Team/SteamTools#458]
### 🥰 需求描述(Description)

程序内所有窗口都能通过点击按钮打开好几个
![Snipaste_2021-09-13_23-42-41](https://user-images.githubusercontent.com/41602338/133114795-71453113-052f-43e4-aa13-c3aecaf0248e.png)
感觉设置只能打开一个更好点

**Comment by rmbadmin** [comment]
其实不做这个限制的原因是因为我本来觉得没必要，想开几个是自己选择的，
但看来现在必须限制一下了。
总有人喜欢多点几个出来吗😂

**Comment by AigioL** [comment]
已经限制了 #451

**Comment by AigioL** [comment]
当前 2.6.1 版本已改进.
