### ISSUE TITLE
特性请求: Gist访问支持以及Github release下载加速

### ISSUE THREAD

**Issue by YogurtZebra** [SteamTools-Team/SteamTools#46]
Git似乎只需要挂上Hosts就能访问，羽翼城大佬的[UsbEam Hosts Editor](https://www.dogfight360.com/blog/475/)里面就有这个
以及建议给代理页面加一个分组，例如将Steam, Github单独成组，可以一键开启或关闭，看着也比较舒服

**Comment by rmbadmin** [comment]
git的访问具体是指什么？，代理整个git？
分组的话，可以考虑之后增加

**Comment by YogurtZebra** [comment]
对不起写错了，是gist

**Comment by YogurtZebra** [comment]
顺便请求一个Github release下载加速

**Comment by rmbadmin** [comment]
github release 的加速只能靠尝试连到速度更快离国内更近的cdn来尝试一下，不能保证肯定有效

**Comment by YogurtZebra** [comment]
github release 加速的话似乎有一个叫[fastgit](https://doc.fastgit.org/zh-cn/)的速度比较快，使用起来也比较简单

**Comment by rmbadmin** [comment]
> github release 加速的话似乎有一个叫[fastgit](https://doc.fastgit.org/zh-cn/)的速度比较快，使用起来也比较简单

好的👌，感谢告知，我会了解一下看看的

**Comment by rmbadmin** [comment]
release下载加速目前发现有对应脚本所以暂时就不考虑做了，之后会尝试直接支持对应的脚本
