### ISSUE TITLE
🐛[BUG] 划词翻译功能不显示翻译内容

### ISSUE THREAD

**Issue by guraismy** [SteamTools-Team/SteamTools#467]
### 🐛 描述(Description)

系统版本：21h1 程序版本：2.4.12

### 🖼 截图(Screenshots)
![QQ图片20210922064737](https://user-images.githubusercontent.com/89929325/134257674-f6636179-f77a-4b35-9fb8-e56633fac541.png)

**Comment by Mossimos** [comment]
http://translate.google.cn/translate_a/single?client=gtx
这个API接口被强制跳转
http://translate.google.com
然后被墙了 得后期更换接口了。

**Comment by Mossimos** [comment]
已修改更换有道翻译API
更新3.5.4即可
