### ISSUE TITLE
新特性请求：希望能在账号切换选项卡中的用户名称后面增加一个所在的steam区。

### ISSUE THREAD

**Issue by vaecebyZ** [SteamTools-Team/SteamTools#47]
账号一多确实不太容易记得住哪个号是哪个区的😂

**Comment by rmbadmin** [comment]
主要是没有好的办法获取到账号所在steam区的数据，所以这个功能没有办法实现，实现的话只能靠自己手写给每个账号记录一个备注用来显示。

**Comment by vaecebyZ** [comment]
> 主要是没有好的办法获取到账号所在steam区的数据，所以这个功能没有办法实现，实现的话只能靠自己手写给每个账号记录一个备注用来显示。

这个也是可以的，给一个备注区⭐。

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
