### ISSUE TITLE
🐛[BUG] 库存游戏无法正常加载

### ISSUE THREAD

**Issue by SNAphoneVI** [SteamTools-Team/SteamTools#473]
### 🐛 描述(Description)

库存游戏无法正常加载
### 📷 复现步骤(Steps to Reproduce)

点击库存游戏功能，一直显示正在加载游戏列表。刷新、开启加速后问题依旧。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.12 for Windows(x64)
- 系统版本号(OS Version): Windows 10.19042.1237

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/61557259/135379927-5dbfe697-891d-4800-a7d3-5eca53c1bf19.png)

**Comment by AigioL** [comment]
当前 2.6.1 版本已修复。

**Comment by Jason-gao3** [comment]
我这里2.8.6仍存在此问题

**Comment by z1vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv** [comment]
2.8.6此问题依旧出现，各种方法尝试都不行
