### ISSUE TITLE
👑[Enhancement] 建议把 Linux 版打成软件包

### ISSUE THREAD

**Issue by YidaozhanYa** [SteamTools-Team/SteamTools#475]
### 🥰 需求描述(Description)

建议把本工具的 Linux 版打成软件包（如deb），这样方便管理。

**Comment by MasterOfStar** [comment]
附议
Debian系.deb，Arch系.pkg.tar.zst，RHEL系.rpm 预编译这三种格式基本就够了（一般来说预编译x86_64 aarch64就够了）
顺便arch系可以上个AUR，ubuntu可以上个PPA，方便直接命令行安装。

**Comment by AigioL** [comment]
目前最新版本 2.6.1 已支持 deb rpm 包。
