### ISSUE TITLE
👑[Enhancement] 灰常建议为本地令牌加入搜索功能

### ISSUE THREAD

**Issue by Rona1do** [SteamTools-Team/SteamTools#476]
### 🥰 需求描述(Description)
**本地令牌很多的话，寻找起来就很不方便，如果可以加入Ctrl + F进行搜索索引的功能，可以大大提升用户体验及效率**

**Comment by Rona1do** [comment]
![image](https://user-images.githubusercontent.com/51991178/135605493-5b3f5af0-56dc-49db-b9d8-6ce226aa7e5c.png)

**Comment by Rona1do** [comment]
可以参考tcno这个

**Comment by AigioL** [comment]
目前最新版本 2.6.1 已加入此功能
