### ISSUE TITLE
启动社区加速服务失败

### ISSUE THREAD

**Issue by Summer-sn0w** [SteamTools-Team/SteamTools#48]
无法启动服务 提示证书安装失败或443端口占用 但查询443端口并未占用并且证书安装成功

**Comment by rmbadmin** [comment]
可能是检测端口占用有bug，之后考虑去除这个检测可以再试试

**Comment by rmbadmin** [comment]
可以测试下新版1.1版本是否解决问题

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
