### ISSUE TITLE
库存游戏一直加载不出来🐛[BUG] 

### ISSUE THREAD

**Issue by Teviey** [SteamTools-Team/SteamTools#486]
### 📷 复现步骤(Steps to Reproduce)

1. 挂时长
2. 不息屏
3. 打开一看库存游戏就一直在加载了

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.0
- 系统版本号(OS Version):

**Comment by rmbadmin** [comment]
duplicate #473
