### ISSUE TITLE
🐛[BUG] Win10任务栏中不显示Steam++图标

### ISSUE THREAD

**Issue by superbigsteam** [SteamTools-Team/SteamTools#487]
### 📷 复现步骤(Steps to Reproduce)

1. 系统更新到Windows10.19042.1266后开机任务栏没有steam++ 的图标

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.12
- 系统版本号(OS Version):
- Windows10.19042.1266

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/84577396/136643981-79a2f776-a001-486e-bd23-f1a089a7a1e6.png)

**Comment by superbigsteam** [comment]
> ### 🐛 描述(Description)
> ### 📷 复现步骤(Steps to Reproduce)
> 系统更新到Windows10.19042.1266后开机任务栏没有steam++ 的图标
> ### 📄 [异常/日志]信息([Exception/Log] Information)
> ### 🚑 基本信息(Basic Information)
> * 程序版本(Program Version):2.4.12
> * 系统版本号(OS Version):
> * Windows10.19042.1266
> 
> ### 🖼 截图(Screenshots)
> ![image](https://user-images.githubusercontent.com/84577396/136643981-79a2f776-a001-486e-bd23-f1a089a7a1e6.png)

**Comment by superbigsteam** [comment]
刚刚排查了一下，发现当程序设置为开机自启后下次开机任务栏没有图标。

**Comment by sceraser** [comment]
win11也遇到了

**Comment by AigioL** [comment]
与 #453 类似，当前 2.6.1 版本已修复。
