### ISSUE TITLE
需要帮助

### ISSUE THREAD

**Issue by Jack6811** [SteamTools-Team/SteamTools#50]
# 我已确定我这边的问题与软件本身无关，如无法帮助请Close
软件按照正常方式解压安装与D盘，启动本地反代后,经测试hosts文件成功重定向于127.0.0.1
但是在访问被代理的网站时谷歌浏览器返回 ```该网页无法正常运作steamcommunity.com 未发送任何数据。```
![谷歌浏览器](https://i.loli.net/2021/01/17/jqk3R8uAzdvO4FC.png)
steam内置的浏览器返回 ```-324```错误
![steam](https://i.loli.net/2021/01/17/BHqyLGO1WcsDUwi.png)
本地80端口未占用，但本地开启了 微软IIS服务。目前在其他机子上测试正常，所以只可能是我自己的问题，有没有方法可以帮助一下？

**Comment by rmbadmin** [comment]
80端口的占用只是为了便于跳转http访问到https上，主要代理的过程是必须依靠于443端口的https协议才能办到，所以如果80端口未被代理就要确定一下访问的地址必须是https。
开启了iis服务是可能会影响本地反代的端口监听的，可以尝试关闭iis尝试一下或者修改iis不要占用443端口

代理的过程其实不用依赖监听443端口，如果确实要在有挂网站需求的服务器上运行此程序的反代功能，之后可能会考虑增加一种使用windows系统代理的方式来可供选择，这样可以避免反代功能与本机需要挂一些网站服务的需求冲突。

**Comment by Jack6811** [comment]
[20210204.log](https://github.com/rmbadmin/SteamTools/files/5924430/20210204.log)
错误日志

**Comment by rmbadmin** [comment]
1.1.4已经更新了系统代理的方式，可以不再占用443端口
