### ISSUE TITLE
🐛[BUG] 库存游戏一直加载

### ISSUE THREAD

**Issue by AmityEX** [SteamTools-Team/SteamTools#578]
### 🐛 描述(Description)
库存游戏一直加载
一直正在加载游戏列表

### 📷 复现步骤(Steps to Reproduce)
基本常现

1. 打开steam++
2. 打开库存
3. 正在加载

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.12 for Windows (X64)
- 系统版本号(OS Version): 
- 版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎9/‎11
操作系统内部版本	19043.1288
体验	Windows Feature Experience Pack 120.2212.3920.0

- 是否为应用商店版本(Store Version): No

**Comment by rmbadmin** [comment]
duplicate #473
