### ISSUE TITLE
cpu占用异常

### ISSUE THREAD

**Issue by Aymp-zjz** [SteamTools-Team/SteamTools#58]
1.0.6版本
在后台无操作的情况下，cpu占用异常
![QQ截图20210125115201](https://user-images.githubusercontent.com/46621088/105659624-262e2b80-5f04-11eb-9e1c-57c0d592c22a.png)

**Comment by rmbadmin** [comment]
能详细描述一下这个状况时启用了哪些功能吗？

**Comment by Aymp-zjz** [comment]
只开启了社区加速，该现象会不定时复现

**Comment by rmbadmin** [comment]
加速启用了哪些代理服务，是否启用了脚本?
电脑cpu型号是?

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
这个问题应该已经解决，应该是反代中出了死循环。
