### ISSUE TITLE
游戏功能的使用问题

### ISSUE THREAD

**Issue by CHminggao** [SteamTools-Team/SteamTools#59]
选择窗口和显示隐藏的功能容易导致GG……
复现方式：
先选择一个窗口，然后点击隐藏；
在选择一个窗口
接下来把第一步隐藏的那个窗口显示出来（盲猜你也办不到

**Comment by rmbadmin** [comment]
嗯，这一块功能做的比较简单，并没有去考虑复杂的使用场景，所有的操作按钮都是只针对目前获取信息的窗口生效的。
如果是专门要用隐藏和显示功能来实现老板键那样的情况的话，以后可能会考虑往这方面做得更完善一些。

**Comment by CHminggao** [comment]
我建议现阶段可以再增加一个还原按钮，点击还原后重置窗口（其实主要是为了让窗口显示出来……不然只能到任务管理器里结束进程），然后才可以选新的窗口

嗯，只是个建议

**Comment by rmbadmin** [comment]
> 我建议现阶段可以再增加一个还原按钮，点击还原后重置窗口（其实主要是为了让窗口显示出来……不然只能到任务管理器里结束进程），然后才可以选新的窗口
> 
> 嗯，只是个建议

如果不重新选择新窗口的话，应该是可以直接用显示按钮来还原的吧？是需要还原之前所有选择隐藏了的窗口吗？

**Comment by CHminggao** [comment]
> > 我建议现阶段可以再增加一个还原按钮，点击还原后重置窗口（其实主要是为了让窗口显示出来……不然只能到任务管理器里结束进程），然后才可以选新的窗口
> > 嗯，只是个建议
> 
> 如果不重新选择新窗口的话，应该是可以直接用显示按钮来还原的吧？是需要还原之前所有选择隐藏了的窗口吗？

是的，毕竟不小心点了下选择窗口那就gg了……（它把自己选中了

**Comment by rmbadmin** [comment]
关闭一些可能已解决的历史问题，如果问题依然存在可自行恢复。
