### ISSUE TITLE
🐛[BUG] 安装版卸载出错，找不到卸载程序

### ISSUE THREAD

**Issue by ZEQAnderson** [SteamTools-Team/SteamTools#598]
### 🐛 描述(Description)

安装版卸载出错，找不到卸载程序

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.12 for Windows (X64)

### 🖼 截图(Screenshots)
![屏幕截图 2021-10-20 224922](https://user-images.githubusercontent.com/66764781/138220273-c73aa0b5-8c9b-4c05-b628-229ef3dc5122.png)

**Comment by Mossimos** [comment]
[uninst.zip](https://github.com/SteamTools-Team/SteamTools/files/7386386/uninst.zip)
之前打包忘记吧这个文件压缩进去了下载这个解压到程序目录下运行（该卸载程序会删除当前文件夹下全部文件主要不要放错地方了）

**Comment by 2337485431** [comment]
已解决
