### ISSUE TITLE
游戏列表-成就解锁 使用时可看到在游玩游戏

### ISSUE THREAD

**Issue by Laplacence** [SteamTools-Team/SteamTools#6]
建议改成成就浏览，浏览时不游玩游戏，修改时才游玩游戏。

**Comment by rmbadmin** [comment]
关于这一点虽然可以修改，但是目前并不好改，因为现在的成就数据是要先连接steam进入游玩中状态才能获取到成就数据。

**Comment by Laplacence** [comment]
可以通过社区页面获取已获得的成就列表吗？

**Comment by rmbadmin** [comment]
> 可以通过社区页面获取已获得的成就列表吗？

当然可以，我的思路也是这样，不过这样修改会影响成就的加载速度和稳定性，以及改动量较大，所以目前不会考虑更改。

**Comment by Laplacence** [comment]
可以第一次扫描已获得的成就，之后设置个trap，获得新成就后自动更新（获得成就必然是在游戏过程中，这时候就可以直接获得成就数据）。

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
