### ISSUE TITLE
打开社区加速后steam提示Invalid SSL Certificate 并且无法正常加速

### ISSUE THREAD

**Issue by Summer-sn0w** [SteamTools-Team/SteamTools#60]
并且软件退出时候提示为引用对象的实例
![uTools_1611653654708](https://user-images.githubusercontent.com/52886465/105827606-28c07c00-5ffd-11eb-9447-7edb636da560.png)
![uTools_1611653629520](https://user-images.githubusercontent.com/52886465/105827619-2cec9980-5ffd-11eb-8bdf-5fb3db421d5e.png)

**Comment by rmbadmin** [comment]
浏览器访问社区页的话是否正常？是否安装了vmware虚拟机占用443端口？

**Comment by Summer-sn0w** [comment]
确实安装了vm虚拟机 我卸载一下试试 游览器访问社区页面是正常的

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
