### ISSUE TITLE
开启本地反代之后创意工坊订阅的东西会重新下载

### ISSUE THREAD

**Issue by Kremore** [SteamTools-Team/SteamTools#62]
开启本地反代之后创意工坊订阅的东西会重新下载 (wallpaper,Garry's mod....)

**Comment by rmbadmin** [comment]
出现这个情况使用了哪些代理服务?应该不可能会影响创意工坊订阅的物品的，完全没有相关联的地方啊。

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
