### ISSUE TITLE
关于系统代理的问题

### ISSUE THREAD

**Issue by xzsk2** [SteamTools-Team/SteamTools#64]
问题描述：

代理软件和steam++均设置开机启动，代理软件开启系统代理，在开机时有几率steam++比代理先启动，就会显示如下错误
![Snipaste_2021-02-02_10-15-59](https://user-images.githubusercontent.com/20642596/106543198-349dc800-6540-11eb-8283-7eda416d2c9c.png)

建议：

添加steam++的代理选择，可选择不使用代理服务器/使用系统代理等

**Comment by rmbadmin** [comment]
看报错是因为令牌同步服务器数据时连到了代理上，，这可能确实与代理软件刚启动有关，之后我处理一下。steam++的反代功能应该是不会与梯子冲突的。

**Comment by mao23333** [comment]
抱歉，我不知道怎么弄就冒昧的在这里写了
我发现的一些小问题是从库存游戏界面打开“讨论组”会无法打开（在启动加速的情况下）
之后用uu加速器试了一下是可以打开的
ps：我是个不懂编程的小白，如果是我的错误，万分抱歉

**Comment by rmbadmin** [comment]
> 抱歉，我不知道怎么弄就冒昧的在这里写了
> 我发现的一些小问题是从库存游戏界面打开“讨论组”会无法打开（在启动加速的情况下）
> 之后用uu加速器试了一下是可以打开的
> ps：我是个不懂编程的小白，如果是我的错误，万分抱歉

本地反代这个功能代理后你的ip依然是本机，讨论组是steam服务端的限制，所以讨论组访问不了这是本地反代无法解决情况

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
