### ISSUE TITLE
🧐[Question] hosts代理出现了问题，显示文件访问被拒绝，没有限权

### ISSUE THREAD

**Issue by mc10086** [SteamTools-Team/SteamTools#646]
### 🧐 问题描述(Description)

hosts代理需要443端口，但是我443端口不见了，用netstat -ano找不到

### 🚑 其他信息(Other Information)

![70U DCQX`41{T1)`W74SQYX](https://user-images.githubusercontent.com/26983061/139542861-33d907c5-817d-495f-ac5c-61e006a03fde.png)
![Q FLLQ2G%MPA(D6 Y759D}E](https://user-images.githubusercontent.com/26983061/139543068-fc055071-0c84-44f9-a644-9c441a9e410c.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Store Version):

**Comment by rmbadmin** [comment]
看不到则表示没有被占用

**Comment by rmbadmin** [comment]
这个错误是说明没有权限操作hosts而不是443端口的问题

**Comment by mc10086** [comment]
> 这个错误是说明没有权限hosts而不是443端口操作的问题



> 这个错误是说明没有权限hosts而不是443端口操作的问题，
> 
> 如果女王不知道如何更改权限，可以尝试删除主机文件启动加速，让自己程序创建一个主机。

是删除hosts吗？

> 这个错误是说明没有权限主机而不是443端口操作的问题，
> 
> 如果爱不知道如何更改权限，可以尝试删除主机文件启动加速，让自己程序创建一个主机。

是删除hosts吗？

**Comment by mc10086** [comment]
> 这个错误是说明没有权限操作hosts而不是443端口的问题，
> 
> 如果实在不知道如何更改权限，可以尝试删掉hosts文件启动加速，让程序自己创建一个hosts。

我在想是不是我的加速器冲突了？

**Comment by rmbadmin** [comment]
> > 这个错误是说明没有权限操作hosts而不是443端口的问题，
> > 如果实在不知道如何更改权限，可以尝试删掉hosts文件启动加速，让程序自己创建一个hosts。
> 
> 我在想是不是我的加速器冲突了？

加速器冲突一般是占用了hosts文件没有释放导致的，关掉加速器就可以解决，这个提示只可能是没有权限或者杀毒软件拦截

**Comment by mc10086** [comment]
> > > 这个错误是说明没有权限操作hosts而不是443端口的问题，
> > > 如果实在不知道如何更改权限，可以尝试删掉hosts文件启动加速，让程序自己创建一个hosts。
> > 
> > 
> > 我在想是不是我的加速器冲突了？
> 
> 加速器冲突一般是占用了hosts文件没有释放导致的，关掉加速器就可以解决，这个提示只可能是没有权限或者杀毒软件拦截

我现在没开加速器，没有杀毒软件，防火墙也关了，hosts也删了还是一样

**Comment by rmbadmin** [comment]
确定没有删错文件么正常删除了hosts文件么？
还是一样的话，那你的hosts文件也没法新建出来，你在手动新建个试试？

**Comment by mc10086** [comment]
> 确定没有删错文件么正常删除了hosts文件么？ 还是一样的话，那你的hosts文件也没法新建出来，你在手动新建个试试？

我好像发现问题了，hosts被隐藏了，而且勾选查看隐藏也显示不出来

**Comment by rmbadmin** [comment]
> > 确定没有删错文件么正常删除了hosts文件么？ 还是一样的话，那你的hosts文件也没法新建出来，你在手动新建个试试？
> 
> 我好像发现问题了，hosts被隐藏了，而且勾选查看隐藏也显示不出来

这种系统相关问题你只能尝试自己解决了，我也并不了解。

**Comment by mc10086** [comment]
> > > 确定没有删错文件么正常删除了hosts文件么？ 还是一样的话，那你的hosts文件也没法新建出来，你在手动新建个试试？
> > 
> > 
> > 我好像发现问题了，hosts被隐藏了，而且勾选查看隐藏也显示不出来
> 
> 这种系统相关问题你只能尝试自己解决了，我也并不了解。

谢谢

**Comment by mc10086** [comment]
> > > 确定没有删错文件么正常删除了hosts文件么？ 还是一样的话，那你的hosts文件也没法新建出来，你在手动新建个试试？
> > 
> > 
> > 我好像发现问题了，hosts被隐藏了，而且勾选查看隐藏也显示不出来
> 
> 这种系统相关问题你只能尝试自己解决了，我也并不了解。

虽然最后解决不了，但还是谢谢了

**Comment by mc10086** [comment]
最后的解决方法居然是在其它地方新建一个hosts文件然后复制过去替换就可以了，我人都傻了

**Comment by rmbadmin** [comment]
> 最后的解决方法居然是在其它地方新建一个hosts文件然后复制过去替换就可以了，我人都傻了

嗯，解决了就行，其原理与删除一样最后都用新的文件权限直接覆盖了旧的文件权限。
