### ISSUE TITLE
软件读取不到游戏，并且闪退

### ISSUE THREAD

**Issue by lgynpy** [SteamTools-Team/SteamTools#65]
![image](https://user-images.githubusercontent.com/78403962/106561320-6d02cd80-6563-11eb-9b03-9bc7059ca832.png)
软件读取不到库存游戏，而且在启动的时候会闪退

**Comment by rmbadmin** [comment]
读取不到游戏参考 #1 

闪退可以打开设置里的日志记录，反馈下错误日志，也可以反馈Windows日志

**Comment by rmbadmin** [comment]
手贱点错不小心关了。。

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
