### ISSUE TITLE
内存异常占用并导致无响应退出

### ISSUE THREAD

**Issue by cyb233** [SteamTools-Team/SteamTools#66]
![屏幕截图 2021-02-02 175527](https://user-images.githubusercontent.com/39186981/106584575-52d7e800-6581-11eb-8537-6adb51c5d3d6.png)
![屏幕截图 2021-02-02 173016](https://user-images.githubusercontent.com/39186981/106584620-5ec3aa00-6581-11eb-8b9a-a642e20aba2a.png)

**Comment by rmbadmin** [comment]
内存溢出大概率与社区反代功能有关，可能有访问到一个没有被代理的本机地址造成了死循环，可以用抓包软件观测一下具体情况。

**Comment by cyb233** [comment]
![屏幕截图 2021-02-03 115105](https://user-images.githubusercontent.com/39186981/106701075-08a64380-6621-11eb-9368-240dc39d2013.png)
我认为网络质量差或无网络的情况非常应该被纳入考虑……前面都没问题，从开始访问个人资料页开始内存增长，直到1200MB左右停止并卡死

**Comment by cyb233** [comment]
> 内存溢出大概率与社区反代功能有关，可能有访问到一个没有被代理的本机地址造成了死循环，可以用抓包软件观测一下具体情况。

新增，令牌功能在没网时不仅不显示令牌且甚至会报错，为啥`功能参考WinAuth开发`，却不会像WinAuth一样随时可用啊🤔

**Comment by rmbadmin** [comment]
> > 内存溢出大概率与社区反代功能有关，可能有访问到一个没有被代理的本机地址造成了死循环，可以用抓包软件观测一下具体情况。
> 
> 新增，令牌功能在没网时不仅不显示令牌且甚至会报错，为啥`功能参考WinAuth开发`，却不会像WinAuth一样随时可用啊🤔

因为之前为了快，忽略了很多地方，现在2.0应该是没有此问题了

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
