### ISSUE TITLE
👑[Enhancement] 点击本地令牌后输入密码需要手动点击输入框

### ISSUE THREAD

**Issue by wsjwqq** [SteamTools-Team/SteamTools#660]
### 点击本地令牌后输入密码需要手动点击输入框

点击本地令牌后需要再手动点击弹出的输入框才能输入密码。

![Snipaste_2021-11-04_13-29-51](https://user-images.githubusercontent.com/57908320/140262856-0c6d90e0-f017-4d2d-b105-f0e6171b8dde.png)

**Comment by rmbadmin** [comment]
这个只是暂时使用弹出框，之后会优化这里使用全新的UI不需要弹框来输入密码的。

**Comment by AigioL** [comment]
当前 2.6.1 版本已改进。
