### ISSUE TITLE
👑[Enhancement] Linux 下数据存储应该遵循 XDG 标准

### ISSUE THREAD

**Issue by zhanghua000** [SteamTools-Team/SteamTools#666]
### 🥰 需求描述(Description)

XDG 标准已被 Linux 下大多数桌面环境支持，目前为止 Steam++ 似乎会把数据文件创建在程序文件夹下，将程序打包为发行版的软件包安装到根文件系统后以非 root 用户运行时将由于缺少创建文件的权限而不能正常启动程序。将数据按照 XDG 标准保存在用户文件夹后将没有这个问题。
附上 XDG 标准的相关要求：
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by AigioL** [comment]
目前最新版本 2.6.1 已改进
