### ISSUE TITLE
👑[Enhancement] .net6正式版已出，能否出一个不带框架的版本

### ISSUE THREAD

**Issue by lvzhenbo** [SteamTools-Team/SteamTools#687]
### 🥰 需求描述(Description)

.net6正式版出了，这是lts版本大部分.net5的软件应该都会更新，所以我准备直接给电脑装上。出一个不带框架的版本，直接使用已经安装的框架节省空间，也节省更新包大小

### 🧐 解决方案(Solution)

我记得没错的话，编译的时候是能够选择不带框架的。

**Comment by rmbadmin** [comment]
嗯，目前程序已经完全升级至.NET RTM，发布时会考虑发布一个不依赖框架版本的

**Comment by AigioL** [comment]
还需要更改服务端支持 FDE 模式下的更新

https://github.com/SteamTools-Team/SteamTools/commit/5cf56e1be9ce88bed71d51b52dc3bfa4a6eaff73#diff-40e5ae22bd1ab1984f8062b064b07903ae6728055e2b56fb7b050a520e82101eR7

https://github.com/SteamTools-Team/SteamTools/commit/5cf56e1be9ce88bed71d51b52dc3bfa4a6eaff73#diff-5e8cbcfd5c1ff21ca42588a7740eeca120f661bbeab876022049ad6c33b5458aR63

**Comment by AigioL** [comment]
目前最新版本 2.6.1 已加入此功能

**Comment by lvzhenbo** [comment]
![image](https://user-images.githubusercontent.com/32427677/143405803-a78a9987-6adc-447c-8e6f-d4d4646946f5.png)
我已经装了框架，但怎么还要求安装

**Comment by AigioL** [comment]
因为需要的是 [ASP.NET Core Runtime 6.0.0 x64](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-6.0.0-windows-x64-installer)

你安装的是 .NET Desktop Runtime 6.0.0

**Comment by lvzhenbo** [comment]
好的，谢谢
