### ISSUE TITLE
👑[Enhancement] 关于应用本身界面改进的一些建议

### ISSUE THREAD

**Issue by Gaoyifei1011** [SteamTools-Team/SteamTools#692]
Some suggestions for improving the interface of the app itself
关于应用本身界面改进的一些建议

1.目前应用的动画流畅性上有些欠缺，希望未来的版本中能够优化一下动画流畅性。例如，在打开左侧的汉堡菜单时，就有些卡顿，不是很流畅。

Currently, the animation fluency of the app is a little lacking. I hope the animation fluency can be improved in the future version. For example, when you open the burger menu on the left, it's a bit sluggish and not very smooth.

2.I want to be able to have the same text size and icon Settings in this part of the screen as in other screens. Currently, apps display slightly larger ICONS and text.
希望能够在这一部分界面与其他界面有相同的文字大小和图标设置。目前应用显示的图标和文字略大。
![image](https://user-images.githubusercontent.com/49179966/141812295-fbaff1e3-736b-46b5-9f8a-ab0fa2b980e8.png)

**Comment by AigioL** [comment]
目前最新版本 2.6.1 已改进
