### ISSUE TITLE
🐛[BUG] 加速页面菜单展开后功能区错位

### ISSUE THREAD

**Issue by xitieshiz2** [SteamTools-Team/SteamTools#707]
### 🐛 描述(Description)

加速页面菜单展开后功能区错位
### 📷 复现步骤(Steps to Reproduce)

1. 开启加速
2.展开侧菜单 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.1
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/75575551/143583907-079760ab-bcb5-4eac-9bf9-550bf3a8187d.png)

**Comment by AigioL** [comment]
看上去主窗口的最低宽度值还需要设大一点。

**Comment by rmbadmin** [comment]
> 看上去主窗口的最低宽度值还需要设大一点。

其实不用，这里后续会更改左侧菜单在过小宽度上的展开逻辑变为浮动，就不会影响布局了
