### ISSUE TITLE
👑[Enhancement] 希望实现开机全自动后台运行

### ISSUE THREAD

**Issue by FolStone** [SteamTools-Team/SteamTools#710]
记得之前羽大的steam302实现了开机无需确认自动运行

**Comment by AigioL** [comment]
现在有什么需要确认的阻止了开机全自动后台运行？

**Comment by FolStone** [comment]
> 

……难道是我这边的问题吗，就是打开软件时候会有账户控制的弹窗需要确认，安装版换到商店版都有

![image](https://user-images.githubusercontent.com/8793672/143764136-783c403d-b2f2-4445-82af-21e663e9c307.png)

**Comment by AigioL** [comment]
这个是 UAC 弹窗，你可以在控制面板中关闭这个弹窗，就不会有了

在 ```控制面板\用户帐户\用户帐户``` 更改用户账户控制设置 左侧滑块拉到底部
![@OE}FG%F5_OP_H$NBO46XOI](https://user-images.githubusercontent.com/24450093/143766202-c580ef77-c2ab-41cf-84f3-7792e814a90d.png)

**Comment by rmbadmin** [comment]
使用计划任务方式启动是可以不弹这个窗的，但是商店版没有办法使用计划任务的方式来启动，安装版应该是没有的。

**Comment by FolStone** [comment]
好吧，可能我之前用的安装版太老了或者是用的便携版，确实最新安装版没有弹窗了…另外请问下附带的asf导入机器人会卡在二次验证最后失败（我也不知道是不是机器人太久没登陆才出现的问题），不知道有没有办法在要求二次验证输令牌的时候暂停来手动输入？

**Comment by rmbadmin** [comment]
> 好吧，可能我之前用的安装版太老了或者是用的便携版，确实最新安装版没有弹窗了…另外请问下附带的asf导入机器人会卡在二次验证最后失败（我也不知道是不是机器人太久没登陆才出现的问题），不知道有没有办法在要求二次验证输令牌的时候暂停来手动输入？

失败后你可以在bot配置的界面点一下绿色的开关按钮即可再此启用，输入密码和输入令牌的等待时间默认是30秒，如果30秒未输入则会默认失败且停用bot，需要手动重启bot。

**Comment by FolStone** [comment]
> > 好吧，可能我之前用的安装版太老了或者是用的便携版，确实最新安装版没有弹窗了…另外请问下附带的asf导入机器人会卡在二次验证最后失败（我也不知道是不是机器人太久没登陆才出现的问题），不知道有没有办法在要求二次验证输令牌的时候暂停来手动输入？
> 
> 失败后你可以在bot配置的界面点一下绿色的开关按钮即可再此启用，输入密码和输入令牌的等待时间默认是30秒，如果30秒未输入则会默认失败且停用bot，需要手动重启bot。

好吧……不知道是不是商店版问题，之前一直都不能输入令牌来着……
