### ISSUE TITLE
🐛[BUG] [外观] 库存游戏栏封面大小调节，从小变大时会相互折叠

### ISSUE THREAD

**Issue by Acpear** [SteamTools-Team/SteamTools#711]
BUG描述：使用库存游戏一栏的封面大小调节功能，调小后封面均变小（此处正常），但再调大时封面会原地变大（而不会重新排列，换行），导致图片相互折叠。
<img width="796" alt="BUG REPORT" src="https://user-images.githubusercontent.com/84609589/143765776-6320d005-2b2b-4e0f-864f-67b48d177253.png">

**Comment by AigioL** [comment]
这也许与 DPI 缩放有关，你的设置中 DPI 缩放是否不为 100% ？
在 ```设置 - 系统 - 显示 - 缩放与布局``` 中

**Comment by Acpear** [comment]
在没有重启电脑的情况下，我刚才调整缩放为100%，但还是出现了上述问题，我会在重启后再试试这个方法。
测试环境：Win11-Dev-22504-1010，缩放比150%。

**Comment by rmbadmin** [comment]
这是个已知问题，目前暂时没有去解决，你可以在调整后切换一下左侧菜单或者刷新一下库存来重绘界面以使显示正常。

**Comment by Acpear** [comment]
好的
