### ISSUE TITLE
已经开启了相关steam hosts加速，但脚本还是无法使用。

### ISSUE THREAD

**Issue by yuehongcheng** [SteamTools-Team/SteamTools#745]
问题描述

已经开启了相关steam hosts加速，但脚本还是无法使用。

其他信息

![image](https://user-images.githubusercontent.com/48173817/144545972-4b4860d1-672c-4183-987c-735fde0afdb6.png)
![image](https://user-images.githubusercontent.com/48173817/144545989-8d63002e-a48d-4a48-b8f9-81a53eaedc72.png)

- 程序版本:2.6.1 x61
- 系统版本号: Windows 10.19043.1348
- 是否为应用商店版本: 否

**Comment by Mossimos** [comment]
开启代理后又重启Steam或者浏览器吗 ，没有重启的话浏览器有缓存 先打开过再开加速的话不会走 Host文件的 IP解析直接访问缓存的ip了

**Comment by yuehongcheng** [comment]
我勾选了只对steam客户端内浏览器生效，steam客户端的话。因为我浏览器已经使用油猴安装了相关插件。
steam客户端重启的话，试过了。没有任何效果，脚本还是不会生效。
如果不勾选steam客户端内浏览器生效的话。   我使用谷歌浏览器，steam++的脚本也不会生效，只会生效我自己在油猴安装的脚本。
steam++我是从1.几的版本一直替换升级和自动升级到2.6.1版本的。  是否可能是版本遗留文件造成的这种BUG？
如果我想重新安装的话，需要保留那些文件以备份我的令牌和登录账号信息？

**Comment by Mossimos** [comment]
麻烦检查下 设置-通用设置- 打开Cache文件夹 下面的Scripts里面脚本内容是啥样的。如果是空的话删除脚本重下 或者 点击刷新缓存按钮 （脚本）开关后的刷新 。应该会正常。如果是空的请回复下。 后面我会去找找为啥为空了

**Comment by yuehongcheng** [comment]
有内容，删除相关脚本，重启steam++/刷新缓存。脚本依旧无效。

**Comment by Mossimos** [comment]
是啥内容贴一个截图看看

**Comment by rmbadmin** [comment]
> 

我这边在和他私聊找问题原因了

**Comment by xinbiaoqian** [comment]
我这里也遇到了同样的问题，不知道是否可以分享一下解决办法，谢谢

**Comment by Mossimos** [comment]
> 我这里也遇到了同样的问题，不可以分享一下解决办法，谢谢知道

请先检查下是否安装了Gm.js 然后清空下Cache 下的Script 文件夹下的脚本文件然后重启软件试试

**Comment by xinbiaoqian** [comment]
> 
我尝试了清空Cache 下的Script 文件夹 重启软件和steam
也尝试清空整个Cache文件夹之后重启电脑 
但是都没有解决问题
![_20220703140435](https://user-images.githubusercontent.com/39876086/177027099-db7d8695-36c2-4ad2-91a3-7d023d776b92.png)

**Comment by rmbadmin** [comment]
@xinbiaoqian 
等待新版本更新，这个问题将会在新版本发布时修复

**Comment by xinbiaoqian** [comment]
> @xinbiaoqian 等待新版本更新，这个问题将会在新版本发布时修复

好的谢谢
