### ISSUE TITLE
🐛[BUG] 把鼠标悬浮在系统代理模式上会有win的提示信息而不是mac的提示

### ISSUE THREAD

**Issue by TNTinMinecraft** [SteamTools-Team/SteamTools#746]
### 🐛 描述(Description)

非常不合理的bug

### 📷 复现步骤(Steps to Reproduce)

1. 把鼠标悬浮在系统代理模式上会有win的提示信息而不是mac的提示 
2. 鼠标悬浮在提示上时开启启动台提示会一直残留到退出启动台时

### 📄 [异常/日志]信息([Exception/Log] Information)

无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):v2.6.1
- 系统版本号(OS Version): macos Big Sur11.5 Beta版(20G5042c)
- 是否为应用商店版本(Whether it is a Store version): N

### 🖼 截图(Screenshots)

<img width="901" alt="截屏2021-12-04 15 53 32" src="https://user-images.githubusercontent.com/48472338/144702158-bb99dcb0-71e7-40c1-89d6-e632d786937b.png">

https://user-images.githubusercontent.com/48472338/144703060-45b494a1-61a0-404e-a47a-895217005ff2.mp4

**Comment by AigioL** [comment]
已由 https://github.com/SteamTools-Team/SteamTools/commit/dfaf48ccd8b17d9b8df499f8a82a4e9a775f75d6#diff-b347021acfc719362b7d2f1f0551420cea156e60180c8ea0b3a939326af8a13dR433 修复

**Comment by AigioL** [comment]
Tooltip 会一直显示不消失是 UI 框架的问题，暂时没有很好的解决办法
