### ISSUE TITLE
希望增加本地挂游戏时长的功能

### ISSUE THREAD

**Issue by Move2win** [SteamTools-Team/SteamTools#76]
之前用过一些挂卡网站，里面有一个挂游戏时长的功能，可以在不实际启动任何游戏的前提下同时挂30多个游戏的时长（具体数量好像是由steam限制的）

能否在本地实现类似的功能？也就是不关电脑开着工具在不实际启动任何游戏的前提下同时挂多个游戏的时长？

**Comment by rmbadmin** [comment]
会和挂卡功能一起出

**Comment by rmbadmin** [comment]
挂时长功能在2.0版本已经上线。
