### ISSUE TITLE
🐛[BUG] asf 控制台输入 restart 后整个软件点不了，必须强制停止

### ISSUE THREAD

**Issue by XTsat** [SteamTools-Team/SteamTools#770]
### 🐛 描述(Description)
ASF 控制台输入 restart 后软件卡住不能点击

### 📷 复现步骤(Steps to Reproduce)

1. 点击自动挂卡
2. 启动 ASF
3. 输入指令 restart

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):Steam++ v2.6.1
- 系统版本号(OS Version): 版本	Windows 10 家庭中文版
版本号	21H2
安装日期	‎2020/‎12/‎13
操作系统内部版本	19044.1387
体验	Windows Feature Experience Pack 120.2212.3920.0

- 是否为应用商店版本(Whether it is a Store version):No 

### 🖼 截图(Screenshots)
![Snipaste_2021-12-07_19-42-31](https://user-images.githubusercontent.com/44708609/145024019-8343042e-047c-4f69-a39b-4879fd395858.png)

**Comment by XTsat** [comment]
我第3次复现的时候输入 restart 后Steam++直接退出了，前两次复现还是卡死

**Comment by AigioL** [comment]
嵌入的 ASF 应该不支持 restart 这个命令吧 @rmbadmin
