### ISSUE TITLE
创建证书失败

### ISSUE THREAD

**Issue by Acerie** [SteamTools-Team/SteamTools#78]
在社区加速界面的反代配置栏中，点击安装证书按钮后提示
"System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。([如图](https://imgchr.com/i/ygtLz4))" ，而后软件停止工作。

如果在安装证书时同时勾选了"自动启动代理服务"，非但出现上述现象，且将导致软件无法再启动与运行，提示"System.NullReferenceException: 未将对象引用设置到对象的实例。([如图](https://imgchr.com/i/ygtqWF))".
需手动删除%localappdata%\rmbgame.net\Steam++\settings.json文件才能恢复正常。

附日志。
[20210217.log](https://github.com/rmbadmin/SteamTools/files/5991452/20210217.log)

**Comment by rmbadmin** [comment]
可以再试试1.1.3版本是否正常

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
