### ISSUE TITLE
用代理看Twtich直播时很卡顿，但是看直播回放速度很快，能达到6M

### ISSUE THREAD

**Issue by 1-Ace-bit** [SteamTools-Team/SteamTools#81]
不知道怎么可以解决看直播卡顿

**Comment by rmbadmin** [comment]
这是取决于自己的网络的，因为本地反代没有经过任何服务器中转。想要解决只能连上更快的cdn或许有办法。
因为除了使用服务器中转目前没有好的方案，所以暂时关闭此问题。
