### ISSUE TITLE
开启局域网代理的情况下脚本失效

### ISSUE THREAD

**Issue by guystone233** [SteamTools-Team/SteamTools#83]
连接局域网下的代理时，脚本失效（如图）
![屏幕截图 2021-02-17 154410](https://user-images.githubusercontent.com/26193222/108171988-374f0e80-7137-11eb-8ecf-1ec0f66ec6f6.png)
但是使用clash客户端开启本地代理时，问题不复现（如图）
![屏幕截图 2021-02-17 154744](https://user-images.githubusercontent.com/26193222/108172246-8e54e380-7137-11eb-9880-5da6e636c3c6.png)

**Comment by rmbadmin** [comment]
嗯..因为开了代理以后请求都直接走代理了，就没有走steam++的本地反代了

**Comment by rmbadmin** [comment]
更新了加速的代理设置功能，支持启用本地socks5代理，给第三方代理工具配置二级代理。
或者在steam++内使用二级代理，来兼容使用自己的代理。
![QQ截图20210907051732](https://user-images.githubusercontent.com/12234359/132261003-b18727c8-f411-4289-808f-4ea1072a9357.png)
