### ISSUE TITLE
steamworks.net相关测试是遗留的吗

### ISSUE THREAD

**Issue by Akarinnnnn** [SteamTools-Team/SteamTools#84]
看到了，好奇问一下

**Comment by zhuangzihan666666** [comment]
[
![06N6H7YRRB6E%JJL~LRTCEQ](https://user-images.githubusercontent.com/79187727/108192393-2a3e1980-714f-11eb-8c85-2022e1841a3f.png)
](url)

**Comment by rmbadmin** [comment]
是的，并没有使用到，只是测试用。

**Comment by zhuangzihan666666** [comment]
好的谢谢，加油

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
