### ISSUE TITLE
你好大佬，有考虑过做个linux 版本的嘛

### ISSUE THREAD

**Issue by TaxicoYin** [SteamTools-Team/SteamTools#85]
有考虑过做个linux版本的吗，现在linux上关于这种工具非常稀少，反代也就一个ascf能用，要是能出个linux版的就太好了，虽然估计大概率不会移植 ( ‘  v  ’ ).

**Comment by 8MiYile** [comment]
附议

**Comment by AigioL** [comment]
duplicate #31

**Comment by AigioL** [comment]
2.4.9 已发布 Alpha 版本
