### ISSUE TITLE
steam令牌导入失败

### ISSUE THREAD

**Issue by Hdm980129** [SteamTools-Team/SteamTools#86]
我使用Steam Desktop Authenticator完成了steam令牌认证，然后安装steam++里的要求导入maFiles文件夹里的mafiles的文件，但导入后显示以下图片内容
![image](https://user-images.githubusercontent.com/36358015/108279216-32ca3a80-71b7-11eb-8084-3dae60405380.png)

然后软件未响应自动关闭了

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
