### ISSUE TITLE
库存游戏无显示，尝试过重启steam，重启软件，刷新游戏列表缓存！

### ISSUE THREAD

**Issue by RightHF** [SteamTools-Team/SteamTools#87]
如题！
![Steam++ 2021_2_18 10_57_23](https://user-images.githubusercontent.com/79238241/108299166-de37b700-71d8-11eb-89b6-92c81f78978b.png)

**Comment by RightHF** [comment]
另外刷新游戏列表缓存时提示“未检测到steam运行”

**Comment by domesticjy** [comment]
哥们，你重新安装一下steam，应该是注册表掉了

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
