### ISSUE TITLE
无法开机启动 手动创建任务计划后读取脚本目录异常

### ISSUE THREAD

**Issue by gdf159159** [SteamTools-Team/SteamTools#9]
无法开机启动 手动创建任务计划后读取脚本目录异常

- [ ] 
![QQ截图20201222104432](https://user-images.githubusercontent.com/8487256/102842795-c810b300-4442-11eb-9350-1f6b539c6abc.png)

![QQ截图20201222104613](https://user-images.githubusercontent.com/8487256/102842874-f5f5f780-4442-11eb-8959-a170dbe0ccf8.png)

**Comment by rmbadmin** [comment]
可能是因为程序现在使用的相对路径所以导致定位到C盘了，之后我会把路径全部替换成绝对路径避免这个问题，

任务计划的话，在这个操作编辑操作时，可以将设置项《起始于(可选)》 路径填写上程序的根目录应该可以解决。

**Comment by rmbadmin** [comment]
能试一下1.0.5版本还有这个问题吗？已经将所有路径都改为绝对路径的读取方式

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
