### ISSUE TITLE
解锁区域限制功能无法正常使用

### ISSUE THREAD

**Issue by wk333** [SteamTools-Team/SteamTools#92]
![图片](https://user-images.githubusercontent.com/30464860/108495299-96518680-72e3-11eb-803a-fd3d91be47c2.png)
![图片](https://user-images.githubusercontent.com/30464860/108495425-bda85380-72e3-11eb-8641-b0aa818fd339.png)

如图，一直在转圈，1.1.2版本，功能是开启的

**Comment by rmbadmin** [comment]
解锁区域限制这个脚本还没有适配，确实是无法使用的

**Comment by LemonPAKA** [comment]
> 解锁区域限制这个脚本还没有适配，确实是无法使用的

这脚本在油猴的确是生效的，在STEAM客户端无论如何都没反应

**Comment by wk333** [comment]
好的，希望以后能适配吧，steam真的绝了，买了游戏给下架

**Comment by rmbadmin** [comment]
因为steam最新的政策更新，该功能已经无法在实现了
