### ISSUE TITLE
脚本问题

### ISSUE THREAD

**Issue by Opikamsoal** [SteamTools-Team/SteamTools#93]
尝试导入了CSGO市场工具脚本发现并不可用（导入到浏览器的油猴正常可用），并尝试导入多个脚本（取消勾选启用某脚本），软件右下角仍然显示已启用X个脚本，（把所有脚本删除只剩下GM仍然显示已启用X个脚本，启用/禁用脚本按钮和启用/停止加速两个按钮反复尝试按过了，并没有什么用才意识到应该是遇到bug了）

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
