### ISSUE TITLE
iOS添加steam++ 本地令牌方法（需越狱）

### ISSUE THREAD

**Issue by zeerdeer** [SteamTools-Team/SteamTools#95]
用 Filza 打开 /var/mobile/Containers/Data/Application/6831DF0E-320D-4B6A-9B43-4C6629CE5F60/Documents 数字串位置为Steam 数据文件夹，可能不一样，Filza会显示为“Steam”，用文本方式打开Steamguard-xxxxxxxxxxxxxxxx，到最下面找到 otpauth 那一栏粘贴到 Steam++ 即可。
![7CC338A7-FAF8-4770-AC85-2AF95DCDF030](https://user-images.githubusercontent.com/10573857/108644613-b69f6200-74ea-11eb-81c1-ccdc66c73c7d.jpeg)
补充：复制的otpauth在电脑上新建TXT文本再导入到winauth即可。

**Comment by L1cardo** [comment]
请问这个是二步验证是怎么处理的？
我将这个二步验证倒入第三方2FA工具，只能出来数字验证码，但是Steam验证码是包含字母的

**Comment by L1cardo** [comment]
没越狱的参考这个办法 #299

**Comment by imx1n** [comment]
导入进去了 但是代码与手机不一致怎么办

**Comment by xbajiu** [comment]
目前3.9.0没有Steamguard文件了
