### ISSUE TITLE
能否设置反代的端口 不要占用443端口。

### ISSUE THREAD

**Issue by baiuu** [SteamTools-Team/SteamTools#96]
能否设置反代的端口 不要占用443端口
开放设置占用端口编号不再是默认且只能占用443端口
我有web服务需要在443端口发布

**Comment by rmbadmin** [comment]
因为现在是用hosts来转发监听本机请求，如果不用443就只能换成本地代理服务监听的方式了，等之后更新可以支持。

**Comment by rmbadmin** [comment]
1.1.4已经更新了系统代理的方式

**Comment by AigioL** [comment]
duplicate #77
