### ISSUE TITLE
win8系统无法运行

### ISSUE THREAD

**Issue by steam-huangzhehao** [SteamTools-Team/SteamTools#97]
我用的是windows8，系统我这几天下载了steam++，想运行一下，逛逛社区。虽然UAC给了警报提示，但**界面没有弹出**。

**Comment by AigioL** [comment]
是 Windows 8 不是 Windows 8.1 吗？

**Comment by rmbadmin** [comment]
有安装.net 4.7.2框架吗

**Comment by AigioL** [comment]
建议升级到 Win8.1
https://support.microsoft.com/zh-cn/windows/%E4%BB%8E-windows-8-%E6%9B%B4%E6%96%B0%E5%88%B0-windows-8-1-17fc54a7-a465-6b5a-c1a0-34140afd0669

因为目前 微软已对 Win8 停止支持 
https://docs.microsoft.com/zh-cn/lifecycle/products/windows-8

以及程序使用的 .net4.7.2 不支持 Win8 
https://docs.microsoft.com/zh-cn/dotnet/framework/migration-guide/versions-and-dependencies#net-framework-472
