### ISSUE TITLE
不知道hosts哪里占用了。

### ISSUE THREAD

**Issue by govmoe** [SteamTools-Team/SteamTools#98]
![Steam___QafY77EboH.png](https://i.loli.net/2021/02/23/86NLuOWiXtrghTG.png)

1.1.3以上的版本会出现这个问题，以下版本不会。

**Comment by rmbadmin** [comment]
使用查找占用的功能或程序也无法找到占用吗

**Comment by govmoe** [comment]
> 使用查找占用的功能或程序也无法找到占用吗

找不到哎。。。

**Comment by govmoe** [comment]
现在只能使用1.1.3以下的版本了。

**Comment by rmbadmin** [comment]
已经在忙着彻底重做v2了，之后重做v2会改写hosts这一块逻辑确保没有这个问题

**Comment by govmoe** [comment]
> 已经在忙着彻底重做v2了，之后重做v2会改写hosts这一块逻辑确保没有这个问题

好耶(

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
