### ISSUE TITLE
为什么会有System做命名空间的前缀啊

### ISSUE THREAD

**Issue by Akarinnnnn** [SteamTools-Team/SteamTools#99]
这就跟写java用java.lang做包名前缀一样奇怪

**Comment by AigioL** [comment]
因为这样项目里可以少一些using
例如不用 using System; 这一行
而且在 Common 库中 可以直接扩展 .net BCL
例如 
https://github.com/SteamTools-Team/SteamTools/blob/develop/System.Common.CoreLib/Random2.cs#L11
https://github.com/SteamTools-Team/SteamTools/blob/develop/System.Common.CoreLib/Collections/Generic/SortedList.cs#L7

**Comment by AigioL** [comment]
未来在 Android 平台上也有可能会用 Java.XXX 作为 namespace 

https://github.com/SteamTools-Team/SteamTools/blob/develop/System.Common.ClientLib.Droid/Extensions/JavaExtensions.cs#L12

**Comment by rmbadmin** [comment]
已经发布2.0版本所以清理一遍问题，如果问题依然存在，可以随时恢复。
